from economy import Economy
economy = Economy(id="BASIC_ARCTIC",
                  cargos = ['alcohol',
                            'chemicals',
                            'clay',
                            'engineering_supplies',
                            'farm_supplies',
                            'fish',
                            'food',
                            'goods',
                            'grain',
                            'iron_ore',
                            'livestock',
                            'mail',
                            'manufacturing_supplies',
                            'oil',
                            'paper',
                            'passengers',
                            'petrol',
                            'wood'])
