from economy import Economy
economy = Economy(id = "BASIC_TEMPERATE",
                  cargos = ['alcohol',
                            'chemicals',
                            'clay',
                            'coal',
                            'engineering_supplies',
                            'farm_supplies',
                            'food',
                            'fruits',
                            'goods',
                            'iron_ore',
                            'livestock',
                            'mail',
                            'manufacturing_supplies',
                            'metal',
                            'milk',
                            'passengers',
                            'sand',
                            'scrap_metal'])
