from economy import Economy
economy = Economy(id = "BASIC_TROPIC",
                  # keep cargos alphabetised - bump the min. compatible version if list changed
                  cargos = ['bauxite',
                            'beans',
                            'chemicals',
                            'coffee',
                            'engineering_supplies',
                            'farm_supplies',
                            'food',
                            'fruits',
                            'goods',
                            'livestock',
                            'mail',
                            'manufacturing_supplies',
                            'nitrates',
                            'oil',
                            'passengers',
                            'sugarcane',
                            'vehicle_parts',
                            'wool'])
