from economy import Economy
economy = Economy(id = "FIRS",
                  cargos = ['alcohol',
                            'bauxite',
                            'building_materials',
                            'chemicals',
                            'clay',
                            'coal',
                            'engineering_supplies',
                            'farm_supplies',
                            'fish',
                            'food',
                            'fruits',
                            'goods',
                            'grain',
                            'iron_ore',
                            'livestock',
                            'lumber',
                            'mail',
                            'manufacturing_supplies',
                            'metal',
                            'milk',
                            'oil',
                            'passengers',
                            'petrol',
                            'plant_fibres',
                            'recyclables',
                            'sand',
                            'scrap_metal',
                            'stone',
                            'sugar_beet',
                            'wood',
                            'wool'])
