from economy import Economy

economy = Economy(
    id="MILD_MILD_WEST",
    numeric_id=6,
    cargos=[
        "aggregates",
        "alcohol",
        "aluminia",
        "aluminium",
        "ammonia_and_nitric_products",
        "apples",
        "bitumen",
        "cement",
        "chemical_intermediates",
        "coal",
        "coke",
        "components",
        "concrete_products",
        "engineering_supplies",
        "explosives",
        "farm_supplies",
        "fish",
        "flour",
        "food",
        "food_additives",
        "frozen_food",
        "fruits",
        "glass",
        "goods",
        "grain",
        "hardware",
        "industrial_carbons",
        "industrial_gases",
        "iron_ore",
        "kaolin",
        "light_hydrocarbons",
        "limestone",
        "livestock",
        "logs",
        "mail",
        "meat",
        "methanol",
        "milk",
        "molasses",
        "oil",
        "packaging",
        "passengers",
        "petroleum_fuels",
        "phosphate",
        "phosphoric_acid",
        "plastics",
        "plant_and_machinery",
        "potash",
        "process_chemicals",
        "quicklime",
        "salt",
        "scrap_metal",
        "slag",
        "steel",
        "sulphur",
        "sulphuric_acid",
        "timber",
        "tin",
        "tinplate",
        "vegetables",
        "wood_pulp",
        "zinc",
        "zinc_ore",
    ],
    cargoflow_graph_tuning={
        "wormhole_industries": [
            "liquids_terminal",
            "port",
            "wharf",
        ],
        "cargos_with_individual_produce_nodes": [
            "goods",
            "livestock",
            "process_chemicals",
        ],
        "cargos_with_individual_accept_nodes": [
            "ammonia_and_nitric_products",
            "chemical_intermediates",
            "limestone",
            "light_hydrocarbons",
            "logs",
            "petroleum_fuels",
            "phosphoric_acid",
            "process_chemicals",
            "steel",
            "sulphuric_acid",
            "wood_pulp",
        ],
        "group_edges_subgraphs": [],
        "ranking_subgraphs": [],
        "clusters": [
            # {"nodes": [], "rank": "", "color": ""},
        ],
    },
)
