from economy import Economy

economy = Economy(
    id="MILD_MILD_WEST",
    numeric_id=6,
    cargos=[
        "acetic_acid",
        "alcohol",
        "ammonia",
        "apples",
        "bitumen",
        "cement",
        "chemical_intermediates",
        "coal",
        "coke",
        "engineering_supplies",
        "farm_supplies",
        "fish",
        "food",
        "food_additives",
        "glass",
        "grain",
        "iron_ore",
        "kaolin",
        "limestone",
        "livestock",
        "logs",
        "lumber",
        "mail",
        "milk",
        "molasses",
        "naphtha",
        "nuclear_fuel",
        "nuclear_waste",
        "oil",
        "packaging",
        "paper",
        "paper_chemicals",
        "passengers",
        "petrol",
        "phosphate",
        "phosphoric_acid",
        "plastics",
        "potash",
        "pulp_wood",
        "quicklime",
        "salt",
        "scrap_metal",
        "slag",
        "steel_sections",
        "steel_sheet",
        "steel_wire_rod",
        "sulphuric_acid",
        "tin",
        "tinplate",
        "vegetables",
        "vehicles",
        "yeast",
        "zinc",
        "zinc_ore",
    ],
    cargoflow_graph_tuning={
        "group_edges_subgraphs": [],
        "ranking_subgraphs": [],
        "clusters": [
            # {"nodes": [], "rank": "", "color": ""},
        ],
    },
)
