from economy import Economy

economy = Economy(
    id="MILD_MILD_WEST",
    numeric_id=6,
    cargos=[
        "acetic_acid",
        "aggregates",
        "alcohol",
        "aluminia",
        "aluminium",
        "ammonia",
        "apples",
        "bitumen",
        "cement",
        "chemical_intermediates",
        "coal",
        "coke",
        "engineering_supplies",
        "explosives",
        "farm_supplies",
        "fish",
        "flour",
        "food",
        "food_additives",
        "glass",
        "goods",
        "grain",
        "hardware",
        "iron_ore",
        "kaolin",
        "limestone",
        "liquefied_petroleum_gas",
        "livestock",
        "logs",
        "mail",
        "milk",
        "molasses",
        "naphtha",
        "nitric_acid",
        "nuclear_fuel",
        "nuclear_waste",
        "oil",
        "packaging",
        "paper",
        "process_chemicals",
        "passengers",
        "petcoke",
        "petrol",
        "phosphate",
        "phosphoric_acid",
        "plastics",
        "potash",
        "quicklime",
        "salt",
        "scrap_metal",
        "slag",
        "steel_sheet",
        "steel_wire_rod",
        "structural_steelwork",
        "sulphuric_acid",
        "timber",
        "tin",
        "tinplate",
        "vegetables",
        "vehicles",
        "zinc",
        "zinc_ore",
    ],
    cargoflow_graph_tuning={
        "wormhole_industries": [
            "liquids_terminal",
            "port",
            "wharf",
        ],
        "cargos_with_individual_produce_nodes": [
            "livestock",
        ],
        "cargos_with_individual_accept_nodes": [
            "limestone",
            "naphtha",
            "petrol",
            "process_chemicals",
        ],
        "group_edges_subgraphs": [],
        "ranking_subgraphs": [],
        "clusters": [
            # {"nodes": [], "rank": "", "color": ""},
        ],
    },
)

# some deliberate overlapping of biomes for mixing at boundaries
economy.add_biome(
    "far_far_west",
    min_x_percent=80,
    max_x_percent=100,
    min_y_percent=0,
    max_y_percent=100,
)
economy.add_biome(
    "moors_and_levels",
    min_x_percent=60,
    max_x_percent=85,
    min_y_percent=0,
    max_y_percent=100,
)
economy.add_biome(
    "severnside",
    min_x_percent=30,
    max_x_percent=70,
    min_y_percent=0,
    max_y_percent=100,
)
economy.add_biome(
    "valleys_and_marches",
    min_x_percent=15,
    max_x_percent=40,
    min_y_percent=0,
    max_y_percent=100,
)
economy.add_biome(
    "fake_cumbria",
    min_x_percent=0,
    max_x_percent=20,
    min_y_percent=0,
    max_y_percent=100,
)
