from economy import Economy
economy = Economy(id = "MISTAH_KURTZ",
                  # keep cargos alphabetised - bump the min. compatible version if list changed
                  cargos = ['alcohol',
                            'building_materials',
                            'coffee',
                            'copper_ore',
                            'diamonds',
                            'engineering_supplies',
                            'farm_supplies',
                            'fish',
                            'food',
                            'fruits',
                            'goods',
                            'grain',
                            'mail',
                            'manufacturing_supplies',
                            'oil',
                            'passengers',
                            'plant_fibres',
                            'rubber',
                            'sugar',
                            'sugarcane',
                            'wood'])
