from economy import Economy
economy = Economy(id = "MISTAH_KURTZ",
                  numeric_id = 3,
                  # as of May 2015 the following cargos must have fixed positions if used by an economy:
                  # passengers: 0, mail: 2, goods 5, food 11
                  # keep the rest of the cargos alphabetised
                  # bump the min. compatible version if this list changes
                  cargos = ['passengers',
                            'alcohol',
                            'mail',
                            'building_materials',
                            'cassava',
                            'goods',
                            'chemicals',
                            'clay',
                            'coffee',
                            'copper',
                            'copper_ore',
                            'food',
                            'diamonds',
                            'edible_oil',
                            'engineering_supplies',
                            'farm_supplies',
                            'fruits',
                            'livestock',
                            'lumber',
                            'maize',
                            'manganese',
                            'nuts',
                            'oil',
                            'petrol',
                            'phosphate',
                            'rubber',
                            'sand',
                            'stone',
                            'wood'])
