# This file defines the principal settings for this project

REPO_NAME          := FIRS Industry Replacement Set
GRF_ID             := F1 25 00 20

MAIN_FILENAME_SRC  := firs.pnfo
MAIN_TARGET        := firs.grf

# If everything is default, you don't need the rest:

# comment out those dirs which are not in use
SRC_DIR            := sprites
DOC_DIR            := docs
SCRIPT_DIR         := scripts
# Add any dirs which shall be bundled in a source release additionally
# to the dirs mentioned above.
EXTRA_DIRS         := templates

# separate dirs for the nfo and pcx files (must be a subdir of 
# or the same as the SRC_DIR )
NFO_DIR            := $(SRC_DIR)/nfo
PCX_DIR            := $(SRC_DIR)/pcx

# Documentation files:
README_FILENAME_SRC    := $(DOC_DIR)/readme.ptxt
LICENSE_FILENAME_SRC   := $(DOC_DIR)/license.txt
CHANGELOG_FILENAME_SRC := $(DOC_DIR)/changelog.txt

# file extentions which indicate plain text source files, 
# parsable by a text editor
FILE_SRC_EXTENSIONS = pnfo template

# file extensions which indicate binary source files
FILE_INC_EXTENSIONS = wav pcx

# Replacement strings in the source and in the documentation
# You may only change the values, not add new definitions
# (unless you know where to add them in other places, too)
REPO_TITLE_DUMMY      := {{GRF_TITLE}}
GRF_ID_DUMMY          := {{GRF_ID}}
REPO_REVISION_DUMMY   := {{REPO_REVISION}}
OUTPUT_FILENAME_DUMMY := {{FILENAME}}
GRF_MD5SUM_DUMMY      := {{GRF_MD5}}

# List of all files which will get shipped
# DOC_FILES = readme, changelog and license
# GRF_FILENAME = MAIN_FILENAME_SRC with the extention .grf
# Add any additional, not usual files here, too, including
# their relative path to the root of the repository
BUNDLE_FILES           = $(MAIN_TARGET) $(DOC_FILES)

CLEAN_ADD = sprites/nfo/cargos.pnfo sprites/nfo/cargo_schemes.pnfo docs/readme.txt
