# This file defines the principal settings for this project

REPO_NAME          := FIRS Industry Replacement Set

BASE_FILENAME      := firs

# Documentation files:
DOC_FILES := docs/changelog.txt docs/readme.txt docs/license.txt

# comment out those dirs which are not in use
SCRIPT_DIR         := scripts

# Offset of default branch (increase, if there is a new release branch)
REPO_BRANCH_VERSION := 0

# If everything is default, you don't need the rest:

NML_MIN_REVISION    := 2044
NML_MIN_VERSION     := 030
