from firs import Cargo

cargo = Cargo(id = 'mail',
              number = '2',
              type_name = '17',
              unit_name = '49',
              type_abbreviation = '145',
              sprite = 'NEW_CARGO_SPRITE',
              weight = '0.25',
              station_list_colour = '15',
              cargo_payment_list_colour = '15',
              is_freight = '1',
              cargo_classes = 'bitmask(CC_MAIL)',
              cargo_label = '"MAIL"',
              town_growth_effect = 'TOWNGROWTH_MAIL',
              town_growth_multiplier = '1.0',
              units_of_cargo = '81',
              items_of_cargo = '113',
              penalty_lowerbound = '6',
              single_penalty_length = '24',
              price_factor = '143.869400024')
