from firs import Cargo

cargo = Cargo(id = 'passengers',
              number = '0',
              type_name = '15',
              unit_name = '47',
              type_abbreviation = '143',
              sprite = 'NEW_CARGO_SPRITE',
              weight = '0.0625',
              station_list_colour = '152',
              cargo_payment_list_colour = '152',
              is_freight = '0',
              cargo_classes = 'bitmask(CC_PASSENGERS)',
              cargo_label = '"PASS"',
              town_growth_effect = 'TOWNGROWTH_PASSENGERS',
              town_growth_multiplier = '1.0',
              units_of_cargo = '79',
              items_of_cargo = '111',
              penalty_lowerbound = '0',
              single_penalty_length = '22',
              price_factor = '101.749420166')
