import importlib

registered_industries = []

# keep these alphabetised for ease of maintaining
industry_module_names = [
    "appliance_factory",
    "arable_farm",
    "assembly_plant",
    "bar_and_section_mill",
    "basic_oxygen_furnace",
    "blast_furnace",
    "body_plant",
    "brewery",
    "builders_yard",
    "carbon_black_plant",
    "cement_plant",
    "chemical_plant",
    "chlor_alkali_plant",
    "cider_mill",
    "clay_pit",
    "coal_mine",
    "coffee_estate",
    "coke_oven",
    "precision_parts_plant",
    "copper_mine",
    "copper_smelter",
    "cryo_plant",
    "dairy",
    "dairy_farm",
    "diamond_mine",
    "dredging_site",
    "elastomer_products_plant",
    "electric_arc_furnace",
    "engine_plant",
    "farm",
    "flour_mill",
    "fish_farm",
    "fishing_grounds",
    "fishing_harbour",
    "food_processor",
    "forest",
    "foundry",
    "fruit_plantation",
    "general_store",
    "glass_works",
    "hardware_factory",
    "hardware_store",
    "hotel",
    "herding_coop",
    "integrated_steel_mill",
    "iron_ore_mine",
    "lime_kiln",
    "limestone_mine",
    "liquids_terminal",
    "tracked_machine_factory",
    "manganese_mine",
    "metal_workshop",
    "nitrate_mine",
    "oil_wells",
    "oil_rig",
    "orchard_piggery",
    "paper_mill",
    "peatlands",
    "petrol_pump",
    "phosphate_mine",
    "pipework_fabricator",
    "plate_mill",
    "port",
    "power_plant",
    "potash_mine",
    "concrete_plant",
    "pyrite_mine",
    "pyrite_smelter",
    "quarry",
    "ranch",
    "rubber_plantation",
    "sawmill",
    "scrap_yard",
    "slag_grinding_plant",
    "soda_ash_mine",
    "stockyard",
    "strip_mill",
    "supply_yard",
    "timber_yard",
    "trading_post",
    "tube_and_pipe_mill",
    "tyre_plant",
    "vehicle_distributor",
    "vineyard",
    "wharf",
    "wire_rod_mill",
]


package_name = "industries"
for industry_module_name in industry_module_names:
    industry_module = importlib.import_module("." + industry_module_name, package_name)
    industry_module.industry.register()
