from industry import IndustryPrimaryNoSupplies, TileLocationChecks

industry = IndustryPrimaryNoSupplies(
    id="fishing_grounds",
    accept_cargo_types=[],
    prod_cargo_types_with_multipliers=[
        ("FISH", 8),
    ],
    prob_in_game="14",
    prob_map_gen="14",
    substitute="5",
    map_colour="160",
    life_type="IND_LIFE_TYPE_EXTRACTIVE",
    special_flags=[
        "IND_FLAG_BUILT_ON_WATER",
        "IND_FLAG_NO_PRODUCTION_INCREASE",
        "IND_FLAG_AI_CREATES_AIR_AND_SHIP_ROUTES",
    ],
    location_checks=dict(
        cluster=[60, 5], location_check_industry_disallow_too_far_from_coast=True
    ),
    prospect_chance="0.75",
    name="string(STR_IND_FISHING_GROUND)",
    nearby_station_name="string(STR_STATION_SHOALS)",
    fund_cost_multiplier="88",
)

industry.enable_in_economy(
    "BASIC_TEMPERATE",
)
industry.enable_in_economy(
    "BASIC_TROPIC",
)
industry.enable_in_economy(
    "BASIC_ARCTIC",
)

# ['IN_A_HOT_COUNTRY'].enabled = True

industry.add_tile(
    id="fishing_grounds_tile_1",
    location_checks=TileLocationChecks(
        disallow_industry_adjacent=True, disallow_slopes=True
    ),
)

sprite_ground = industry.add_sprite(
    sprite_number="GROUNDSPRITE_WATER",
)
spriteset_ground_empty = industry.add_spriteset(type="empty")
spriteset_1 = industry.add_spriteset(
    sprites=[(10, 10, 64, 31, -31, 0)],
)
spriteset_2 = industry.add_spriteset(
    sprites=[(80, 10, 64, 31, -31, 0)],
)
spriteset_3 = industry.add_spriteset(
    sprites=[(150, 10, 64, 31, -31, 0)],
)
spriteset_4 = industry.add_spriteset(
    sprites=[(220, 10, 64, 31, -31, 0)],
)
spriteset_5 = industry.add_spriteset(
    sprites=[(290, 10, 64, 31, -31, -32)],
)

industry.add_spritelayout(
    id="fishing_grounds_spritelayout_1",
    tile="fishing_grounds_tile_1",
    ground_sprite=sprite_ground,
    ground_overlay=spriteset_ground_empty,
    building_sprites=[spriteset_1],
)
industry.add_spritelayout(
    id="fishing_grounds_spritelayout_2",
    tile="fishing_grounds_tile_1",
    ground_sprite=sprite_ground,
    ground_overlay=spriteset_ground_empty,
    building_sprites=[spriteset_2],
)
industry.add_spritelayout(
    id="fishing_grounds_spritelayout_3",
    tile="fishing_grounds_tile_1",
    ground_sprite=sprite_ground,
    ground_overlay=spriteset_ground_empty,
    building_sprites=[spriteset_3],
)
industry.add_spritelayout(
    id="fishing_grounds_spritelayout_4",
    tile="fishing_grounds_tile_1",
    ground_sprite=sprite_ground,
    ground_overlay=spriteset_5,
    building_sprites=[spriteset_4],
)

industry.add_industry_layout(
    id="fishing_grounds_industry_layout_1",
    layout=[
        (0, 0, "spritelayout_null_water"),
        (0, 1, "spritelayout_null_water"),
        (0, 2, "spritelayout_null_water"),
        (0, 3, "spritelayout_null_water"),
        (0, 4, "spritelayout_null_water"),
        (0, 5, "spritelayout_null_water"),
        (0, 6, "spritelayout_null_water"),
        (1, 0, "spritelayout_null_water"),
        (1, 1, "spritelayout_null_water"),
        (1, 2, "spritelayout_null_water"),
        (1, 3, "spritelayout_null_water"),
        (1, 4, "spritelayout_null_water"),
        (1, 5, "spritelayout_null_water"),
        (1, 6, "spritelayout_null_water"),
        (2, 0, "spritelayout_null_water"),
        (2, 1, "spritelayout_null_water"),
        (2, 2, "spritelayout_null_station"),
        (2, 3, "spritelayout_null_station"),
        (2, 4, "spritelayout_null_water"),
        (2, 5, "spritelayout_null_water"),
        (2, 6, "spritelayout_null_water"),
        (3, 0, "spritelayout_null_water"),
        (3, 1, "spritelayout_null_water"),
        (3, 2, "fishing_grounds_spritelayout_1"),
        (3, 3, "fishing_grounds_spritelayout_4"),
        (3, 4, "fishing_grounds_spritelayout_2"),
        (3, 5, "spritelayout_null_water"),
        (3, 6, "spritelayout_null_water"),
        (4, 0, "spritelayout_null_water"),
        (4, 1, "spritelayout_null_water"),
        (4, 2, "spritelayout_null_water"),
        (4, 3, "fishing_grounds_spritelayout_3"),
        (4, 4, "spritelayout_null_water"),
        (4, 5, "spritelayout_null_water"),
        (4, 6, "spritelayout_null_water"),
        (5, 0, "spritelayout_null_water"),
        (5, 1, "spritelayout_null_water"),
        (5, 2, "spritelayout_null_water"),
        (5, 3, "spritelayout_null_water"),
        (5, 4, "spritelayout_null_water"),
        (5, 5, "spritelayout_null_water"),
        (5, 6, "spritelayout_null_water"),
        (6, 0, "spritelayout_null_water"),
        (6, 1, "spritelayout_null_water"),
        (6, 2, "spritelayout_null_water"),
        (6, 3, "spritelayout_null_water"),
        (6, 4, "spritelayout_null_water"),
        (6, 5, "spritelayout_null_water"),
        (6, 6, "spritelayout_null_water"),
    ],
)
industry.add_industry_layout(
    id="fishing_grounds_industry_layout_2",
    layout=[
        (0, 0, "spritelayout_null_water"),
        (0, 1, "spritelayout_null_water"),
        (0, 2, "spritelayout_null_water"),
        (0, 3, "spritelayout_null_water"),
        (0, 4, "spritelayout_null_water"),
        (0, 5, "spritelayout_null_water"),
        (0, 6, "spritelayout_null_water"),
        (1, 0, "spritelayout_null_water"),
        (1, 1, "spritelayout_null_water"),
        (1, 2, "spritelayout_null_water"),
        (1, 3, "spritelayout_null_water"),
        (1, 4, "spritelayout_null_water"),
        (1, 5, "spritelayout_null_water"),
        (1, 6, "spritelayout_null_water"),
        (2, 0, "spritelayout_null_water"),
        (2, 1, "spritelayout_null_water"),
        (2, 2, "spritelayout_null_water"),
        (2, 3, "spritelayout_null_station"),
        (2, 4, "spritelayout_null_station"),
        (2, 5, "spritelayout_null_water"),
        (2, 6, "spritelayout_null_water"),
        (3, 0, "spritelayout_null_water"),
        (3, 1, "spritelayout_null_water"),
        (3, 2, "fishing_grounds_spritelayout_1"),
        (3, 3, "fishing_grounds_spritelayout_2"),
        (3, 4, "fishing_grounds_spritelayout_4"),
        (3, 5, "spritelayout_null_water"),
        (3, 6, "spritelayout_null_water"),
        (4, 0, "spritelayout_null_water"),
        (4, 1, "spritelayout_null_water"),
        (4, 2, "spritelayout_null_water"),
        (4, 3, "spritelayout_null_water"),
        (4, 4, "fishing_grounds_spritelayout_3"),
        (4, 5, "spritelayout_null_water"),
        (4, 6, "spritelayout_null_water"),
        (5, 0, "spritelayout_null_water"),
        (5, 1, "spritelayout_null_water"),
        (5, 2, "spritelayout_null_water"),
        (5, 3, "spritelayout_null_water"),
        (5, 4, "fishing_grounds_spritelayout_3"),
        (5, 5, "spritelayout_null_water"),
        (5, 6, "spritelayout_null_water"),
        (6, 0, "spritelayout_null_water"),
        (6, 1, "spritelayout_null_water"),
        (6, 2, "spritelayout_null_water"),
        (6, 3, "spritelayout_null_water"),
        (6, 4, "spritelayout_null_water"),
        (6, 5, "spritelayout_null_water"),
        (6, 6, "spritelayout_null_water"),
        (7, 0, "spritelayout_null_water"),
        (7, 1, "spritelayout_null_water"),
        (7, 2, "spritelayout_null_water"),
        (7, 3, "spritelayout_null_water"),
        (7, 4, "spritelayout_null_water"),
        (7, 5, "spritelayout_null_water"),
        (7, 6, "spritelayout_null_water"),
    ],
)
industry.add_industry_layout(
    id="fishing_grounds_industry_layout_3",
    layout=[
        (0, 0, "spritelayout_null_water"),
        (0, 1, "spritelayout_null_water"),
        (0, 2, "spritelayout_null_water"),
        (0, 3, "spritelayout_null_water"),
        (0, 4, "spritelayout_null_water"),
        (0, 5, "spritelayout_null_water"),
        (0, 6, "spritelayout_null_water"),
        (1, 0, "spritelayout_null_water"),
        (1, 1, "spritelayout_null_water"),
        (1, 2, "spritelayout_null_water"),
        (1, 3, "spritelayout_null_water"),
        (1, 4, "spritelayout_null_water"),
        (1, 5, "spritelayout_null_water"),
        (1, 6, "spritelayout_null_water"),
        (2, 0, "spritelayout_null_water"),
        (2, 1, "spritelayout_null_water"),
        (2, 2, "spritelayout_null_water"),
        (2, 3, "fishing_grounds_spritelayout_3"),
        (2, 4, "spritelayout_null_water"),
        (2, 5, "spritelayout_null_water"),
        (2, 6, "spritelayout_null_water"),
        (3, 0, "spritelayout_null_water"),
        (3, 1, "spritelayout_null_water"),
        (3, 2, "spritelayout_null_water"),
        (3, 3, "spritelayout_null_water"),
        (3, 4, "spritelayout_null_water"),
        (3, 5, "spritelayout_null_water"),
        (3, 6, "spritelayout_null_water"),
        (4, 0, "spritelayout_null_water"),
        (4, 1, "spritelayout_null_water"),
        (4, 2, "spritelayout_null_station"),
        (4, 3, "spritelayout_null_station"),
        (4, 4, "spritelayout_null_water"),
        (4, 5, "spritelayout_null_water"),
        (4, 6, "spritelayout_null_water"),
        (5, 0, "spritelayout_null_water"),
        (5, 1, "spritelayout_null_water"),
        (5, 2, "fishing_grounds_spritelayout_2"),
        (5, 3, "fishing_grounds_spritelayout_4"),
        (5, 4, "fishing_grounds_spritelayout_2"),
        (5, 5, "spritelayout_null_water"),
        (5, 6, "spritelayout_null_water"),
        (6, 0, "spritelayout_null_water"),
        (6, 1, "spritelayout_null_water"),
        (6, 2, "spritelayout_null_water"),
        (6, 3, "spritelayout_null_water"),
        (6, 4, "spritelayout_null_water"),
        (6, 5, "spritelayout_null_water"),
        (6, 6, "spritelayout_null_water"),
        (7, 0, "spritelayout_null_water"),
        (7, 1, "spritelayout_null_water"),
        (7, 2, "spritelayout_null_water"),
        (7, 3, "spritelayout_null_water"),
        (7, 4, "spritelayout_null_water"),
        (7, 5, "spritelayout_null_water"),
        (7, 6, "spritelayout_null_water"),
    ],
)
industry.add_industry_layout(
    id="fishing_grounds_industry_layout_4",
    layout=[
        (0, 0, "spritelayout_null_water"),
        (0, 1, "spritelayout_null_water"),
        (0, 2, "spritelayout_null_water"),
        (0, 3, "spritelayout_null_water"),
        (0, 4, "spritelayout_null_water"),
        (0, 5, "spritelayout_null_water"),
        (0, 6, "spritelayout_null_water"),
        (1, 0, "spritelayout_null_water"),
        (1, 1, "spritelayout_null_water"),
        (1, 2, "spritelayout_null_water"),
        (1, 3, "spritelayout_null_water"),
        (1, 4, "spritelayout_null_water"),
        (1, 5, "spritelayout_null_water"),
        (1, 6, "spritelayout_null_water"),
        (2, 0, "spritelayout_null_water"),
        (2, 1, "spritelayout_null_water"),
        (2, 2, "spritelayout_null_station"),
        (2, 3, "spritelayout_null_station"),
        (2, 4, "spritelayout_null_water"),
        (2, 5, "fishing_grounds_spritelayout_3"),
        (2, 6, "spritelayout_null_water"),
        (3, 0, "spritelayout_null_water"),
        (3, 1, "spritelayout_null_water"),
        (3, 2, "fishing_grounds_spritelayout_2"),
        (3, 3, "fishing_grounds_spritelayout_4"),
        (3, 4, "fishing_grounds_spritelayout_3"),
        (3, 5, "fishing_grounds_spritelayout_1"),
        (3, 6, "spritelayout_null_water"),
        (4, 0, "spritelayout_null_water"),
        (4, 1, "spritelayout_null_water"),
        (4, 2, "spritelayout_null_water"),
        (4, 3, "spritelayout_null_water"),
        (4, 4, "spritelayout_null_water"),
        (4, 5, "spritelayout_null_water"),
        (4, 6, "spritelayout_null_water"),
        (5, 0, "spritelayout_null_water"),
        (5, 1, "spritelayout_null_water"),
        (5, 2, "spritelayout_null_water"),
        (5, 3, "spritelayout_null_water"),
        (5, 4, "spritelayout_null_water"),
        (5, 5, "spritelayout_null_water"),
        (5, 6, "spritelayout_null_water"),
    ],
)
