import importlib

registered_cargos = []

# keep these alphabetised for ease of maintaining
cargo_module_names = [
    "acid",
    "aggregates",
    "alcohol",
    "aluminium",
    "ammonia",
    "beans",
    "building_materials",
    "carbon_black",
    "cassava",
    "cast_iron",
    "cement",
    "chemicals",
    "chlorine",
    "clay",
    "cleaning_agents",
    "coal",
    "coal_tar",
    "coffee",
    "coke",
    "copper",
    "copper_ore",
    "diamonds",
    "edible_oil",
    "electrical_parts",
    "engineering_supplies",
    "explosives",
    "farm_supplies",
    "ferroalloys",
    "fertiliser",
    "fish",
    "food",
    "forgings_and_castings",
    "fruits",
    "glass",
    "goods",
    "grain",
    "hardware",
    "iron_ore",
    "kaolin",
    "livestock",
    "limestone",
    "logs",
    "lye",
    "mail",
    "maize",
    "manganese",
    "milk",
    "nitrates",
    "nitrogen",
    "nuts",
    "oil",
    "oxygen",
    "paints_and_coatings",
    "paper",
    "passengers",
    "peat",
    "petrol",
    "phosphate",
    "pig_iron",
    "pipework",
    "potash",
    "concrete_products",
    "pumps_and_valves",
    "pyrite_ore",
    "quicklime",
    "rebar",
    "rubber",
    "sand",
    "salt",
    "scrap_metal",
    "seals_belts_and_hoses",
    "slag",
    "soda_ash",
    "steel",
    "steel_billets_and_blooms",
    "steel_ingots",
    "steel_merchant_bar",
    "steel_pipe",
    "steel_sections",
    "steel_sheet",
    "steel_slab",
    "steel_tube",
    "steel_wire_rod",
    "sulphur",
    "timber",
    "tyre_cord",
    "tyres",
    "vehicle_bodies",
    "vehicle_engines",
    "vehicle_parts",
    "vehicles",
    "welding_consumables",
    "wool",
    "zinc",
]

package_name = "cargos"
for cargo_module_name in cargo_module_names:
    cargo_module = importlib.import_module(
        "." + cargo_module_name, package_name
    )
    cargo_module.cargo.register()
