from cargo import Cargo

cargo = Cargo(id='coal_tar',
              type_name='string(STR_CARGO_NAME_COAL_TAR)',
              unit_name='string(STR_CARGO_NAME_COAL_TAR)',
              type_abbreviation='string(STR_CID_COAL_TAR)',
              sprite='NEW_CARGO_SPRITE',
              weight='1.0',
              cargo_payment_list_colour='2',
              is_freight='1',
              cargo_classes='bitmask(CC_BULK, CC_COVERED)',
              cargo_label='CTAR',
              town_growth_effect='TOWNGROWTH_NONE',
              town_growth_multiplier='1.0',
              units_of_cargo='TTD_STR_TONS',
              items_of_cargo='string(STR_CARGO_UNIT_COAL_TAR)',
              penalty_lowerbound='30',
              single_penalty_length='255',
              price_factor='53',
              capacity_multiplier='1',
              icon_indices=(1, 3))
