from cargo import Cargo

cargo = Cargo(id='glass',
              type_name='string(STR_CARGO_NAME_GLASS)',
              unit_name='string(STR_CARGO_NAME_GLASS)',
              type_abbreviation='string(STR_CID_GLASS)',
              sprite='NEW_CARGO_SPRITE',
              weight='0.65',
              is_freight='1',
              cargo_classes='bitmask(CC_PIECE_GOODS)',
              cargo_label='GLAS',
              town_growth_effect='TOWNGROWTH_NONE',
              town_growth_multiplier='1.0',
              units_of_cargo='TTD_STR_TONS',
              items_of_cargo='string(STR_CARGO_UNIT_GLASS)',
              penalty_lowerbound='12',
              single_penalty_length='180',
              price_factor=147,
              capacity_multiplier='1',
              icon_indices=(7, 1))
