from firs import Cargo

cargo = Cargo(id = 'goods',
              number = '5',
              type_name = '20',
              unit_name = '52',
              type_abbreviation = '148',
              sprite = 'NEW_CARGO_SPRITE',
              weight = '0.5',
              station_list_colour = '194',
              cargo_payment_list_colour = '194',
              is_freight = '1',
              cargo_classes = 'bitmask(CC_EXPRESS)',
              cargo_label = '"GOOD"',
              town_growth_effect = 'TOWNGROWTH_WATER',
              town_growth_multiplier = '1.0',
              units_of_cargo = '84',
              items_of_cargo = '116',
              penalty_lowerbound = '5',
              single_penalty_length = '24',
              price_factor = '149.4140625',
              capacity_multiplier = '2')
