from cargo import Cargo

cargo = Cargo(id='kaolin',
              type_name='string(STR_CARGO_NAME_KAOLIN)',
              unit_name='string(STR_CARGO_NAME_KAOLIN)',
              type_abbreviation='string(STR_CID_KAOLIN)',
              sprite='NEW_CARGO_SPRITE',
              weight='1.0',
              cargo_payment_list_colour='14',
              is_freight='1',
              cargo_classes='bitmask(CC_BULK, CC_LIQUID, CC_COVERED)',
              cargo_label='KAOL',
              town_growth_effect='TOWNGROWTH_NONE',
              town_growth_multiplier='1.0',
              units_of_cargo='80',
              items_of_cargo='string(STR_CARGO_UNIT_KAOLIN)',
              penalty_lowerbound='30',
              single_penalty_length='255',
              price_factor='74',
              capacity_multiplier='1',
              icon_indices=(5, 3))
