from cargo import Cargo

cargo = Cargo(id='lumber',
              type_name='string(STR_CARGO_NAME_LUMBER)',
              unit_name='string(STR_CARGO_NAME_LUMBER)',
              type_abbreviation='string(STR_CID_LUMBER)',
              sprite='NEW_CARGO_SPRITE',
              weight='1.0',
              cargo_payment_list_colour='58',
              is_freight='1',
              cargo_classes='bitmask(CC_BULK, CC_PIECE_GOODS)',
              cargo_label='WDPR',
              town_growth_effect='TOWNGROWTH_NONE',
              town_growth_multiplier='1.0',
              units_of_cargo='80',
              items_of_cargo='string(STR_CARGO_UNIT_LUMBER)',
              penalty_lowerbound='18',
              single_penalty_length='255',
              price_factor='124',
              capacity_multiplier='1',
              icon_indices=(6, 1))
