from cargo import Cargo

cargo = Cargo(id='manganese',
              type_name='string(STR_CARGO_NAME_MANGANESE)',
              unit_name='string(STR_CARGO_NAME_MANGANESE)',
              type_abbreviation='string(STR_CID_MANGANESE)',
              sprite='NEW_CARGO_SPRITE',
              weight='1.0',
              cargo_payment_list_colour='16',
              is_freight='1',
              cargo_classes='bitmask(CC_BULK)',
              cargo_label='MNO2',
              town_growth_effect='TOWNGROWTH_NONE',
              town_growth_multiplier='1.0',
              units_of_cargo='80',
              items_of_cargo='string(STR_CARGO_UNIT_MANGANESE)',
              penalty_lowerbound='30',
              single_penalty_length='255',
              price_factor='75',
              capacity_multiplier='1',
              icon_indices=(9, 2))
