from cargo import Cargo

cargo = Cargo(id='phosphate',
              type_name='string(STR_CARGO_NAME_PHOSPHATE)',
              unit_name='string(STR_CARGO_NAME_PHOSPHATE)',
              type_abbreviation='string(STR_CID_PHOSPHATE)',
              sprite='NEW_CARGO_SPRITE',
              weight='1.0',
              cargo_payment_list_colour='64',
              is_freight='1',
              cargo_classes='bitmask(CC_BULK)',
              cargo_label='PHOS',
              town_growth_effect='TOWNGROWTH_NONE',
              town_growth_multiplier='1.0',
              units_of_cargo='80',
              items_of_cargo='string(STR_CARGO_UNIT_PHOSPHATE)',
              penalty_lowerbound='30',
              single_penalty_length='255',
              price_factor='95',
              capacity_multiplier='1',
              icon_indices=(10, 2))
