from cargo import Cargo

cargo = Cargo(id='plastics',
              type_name='string(STR_CARGO_NAME_PLASTICS)',
              unit_name='string(STR_CARGO_NAME_PLASTICS)',
              type_abbreviation='string(STR_CID_PLASTICS)',
              sprite='NEW_CARGO_SPRITE',
              weight='1.0',
              is_freight='1',
              cargo_classes='bitmask(CC_PIECE_GOODS, CC_BULK, CC_COVERED)',
              cargo_label='PLAS',
              town_growth_effect='TOWNGROWTH_NONE',
              town_growth_multiplier='1.0',
              units_of_cargo='TTD_STR_LITERS',
              items_of_cargo='string(STR_CARGO_UNIT_PLASTICS)',
              penalty_lowerbound='12',
              single_penalty_length='36',
              capacity_multiplier='1',
              price_factor=167,
              icon_indices=(6, 4))
