from cargo import Cargo

cargo = Cargo(id='raw_latex',
              type_name='string(STR_CARGO_NAME_RAW_LATEX)',
              unit_name='string(STR_CARGO_NAME_RAW_LATEX)',
              type_abbreviation='string(STR_CID_RAW_LATEX)',
              sprite='NEW_CARGO_SPRITE',
              weight='1.0',
              cargo_payment_list_colour='6',
              is_freight='1',
              cargo_classes='bitmask(CC_LIQUID)',
              cargo_label='LATX',
              town_growth_effect='TOWNGROWTH_NONE',
              town_growth_multiplier='1.0',
              units_of_cargo='TTD_STR_LITERS',
              items_of_cargo='string(STR_CARGO_UNIT_RAW_LATEX)',
              penalty_lowerbound='10',
              single_penalty_length='36',
              capacity_multiplier='1',
              price_factor='110',
              icon_indices=(2, 2))
