from cargo import Cargo

cargo = Cargo(id='salt',
              type_name='string(STR_CARGO_NAME_SALT)',
              unit_name='string(STR_CARGO_NAME_SALT)',
              type_abbreviation='string(STR_CID_SALT)',
              sprite='NEW_CARGO_SPRITE',
              weight='1.0',
              cargo_payment_list_colour='121',
              is_freight='1',
              cargo_classes='bitmask(CC_BULK)',
              cargo_label='SALT',
              town_growth_effect='TOWNGROWTH_NONE',
              town_growth_multiplier='1.0',
              units_of_cargo='80',
              items_of_cargo='string(STR_CARGO_UNIT_SALT)',
              penalty_lowerbound='30',
              single_penalty_length='255',
              capacity_multiplier='1',
              price_factor='108',
              icon_indices=(3, 4))
