from cargo import Cargo

cargo = Cargo(id='sand',
              type_name='string(STR_CARGO_NAME_SAND)',
              unit_name='string(STR_CARGO_NAME_SAND)',
              type_abbreviation='string(STR_CID_SAND)',
              sprite='NEW_CARGO_SPRITE',
              weight='1.0',
              is_freight='1',
              cargo_classes='bitmask(CC_BULK)',
              cargo_label='SAND',
              town_growth_effect='TOWNGROWTH_NONE',
              town_growth_multiplier='1.0',
              units_of_cargo='TTD_STR_TONS',
              items_of_cargo='string(STR_CARGO_UNIT_SAND)',
              penalty_lowerbound='64',
              single_penalty_length='255',
              capacity_multiplier='1',
              price_factor=59,
              icon_indices=(0, 1))
