from cargo import Cargo

cargo = Cargo(id='sulphuric_acid',
              type_name='string(STR_CARGO_NAME_SULPHURIC_ACID)',
              unit_name='string(STR_CARGO_NAME_SULPHURIC_ACID)',
              type_abbreviation='string(STR_CID_SULPHURIC_ACID)',
              sprite='NEW_CARGO_SPRITE',
              weight='1.5',
              cargo_payment_list_colour='184',
              is_freight='1',
              cargo_classes='bitmask(CC_LIQUID, CC_HAZARDOUS)',
              cargo_label='SUAC',
              town_growth_effect='TOWNGROWTH_NONE',
              town_growth_multiplier='1.0',
              units_of_cargo='TTD_STR_LITERS',
              items_of_cargo='string(STR_CARGO_UNIT_SULPHURIC_ACID)',
              penalty_lowerbound='24',
              single_penalty_length='48',
              price_factor=109,
              capacity_multiplier='1',
              icon_indices=(4, 4))
