from cargo import Cargo

cargo = Cargo(id='tin_mill_black_plate',
              type_name='string(STR_CARGO_NAME_TIN_MILL_BLACK_PLATE)',
              unit_name='string(STR_CARGO_NAME_TIN_MILL_BLACK_PLATE)',
              type_abbreviation='string(STR_CID_TIN_MILL_BLACK_PLATE)',
              sprite='NEW_CARGO_SPRITE',
              weight='1.0',
              cargo_payment_list_colour='9',
              is_freight='1',
              cargo_classes='bitmask(CC_PIECE_GOODS)',
              cargo_label='TMBP',
              town_growth_effect='TOWNGROWTH_NONE',
              town_growth_multiplier='1.0',
              units_of_cargo='TTD_STR_TONS',
              items_of_cargo='string(STR_CARGO_UNIT_TIN_MILL_BLACK_PLATE)',
              penalty_lowerbound='14',
              single_penalty_length='255',
              capacity_multiplier='1',
              price_factor=130,
              icon_indices=(12, 4))
