from cargo import Cargo

cargo = Cargo(id='water',
              type_name='TTD_STR_CARGO_PLURAL_WATER',
              unit_name='TTD_STR_CARGO_SINGULAR_WATER',
              type_abbreviation='TTD_STR_ABBREV_WATER',
              sprite='NEW_CARGO_SPRITE',
              weight='1',
              is_freight='1',
              cargo_classes='bitmask(CC_EXPRESS, CC_LIQUID, CC_REFRIGERATED)',
              cargo_label='WATR',
              town_growth_effect='TOWNGROWTH_WATER',
              town_growth_multiplier='1.0',
              units_of_cargo='TTD_STR_QUANTITY_WATER',
              items_of_cargo='TTD_STR_QUANTITY_WATER',
              penalty_lowerbound='22',
              single_penalty_length='44',
              price_factor=152,
              capacity_multiplier='1',
              icon_indices=(1, 5))
