dicts = []

aluminium_plant = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_aluminium_plant_1, tilelayout_aluminium_plant_2, tilelayout_aluminium_plant_3]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_ALUMINIUM_PLANT)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_ALUMINIUM_PLANT)',
    'prod_cargo_types': '[STEL]',
    'accept_cargo_types': '[AORE, RFPR, SCMT]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '200',
    'map_colour': '175',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
arable_farm = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_arable_farm_1, tilelayout_arable_farm_2, tilelayout_arable_farm_3]',
    'life_type': 'IND_LIFE_TYPE_ORGANIC',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_FARM',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_FARM',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_ARABLE_FARM)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_ARABLE_FARM)',
    'prod_cargo_types': '[GRAI, SGBT]',
    'accept_cargo_types': '[FMSP]',
    'prod_multiplier': '[7, 7]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '1',
    'conflicting_ind_types': '[]',
    'prob_random': '24',
    'prob_in_game': '4',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '55',
    'map_colour': '208',
    'remove_cost_multiplier': '0',
    'spec_flags': 'bitmask(IND_FLAG_PLANT_FIELDS_PERIODICALLY, IND_FLAG_PLANT_FIELDS_WHEN_BUILT)',
},
)
bauxite_mine = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[bauxite_mine_industry_layout_1_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_EXTRACTIVE',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_BAUXITE_MINE)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_BAUXITE_MINE)',
    'prod_cargo_types': '[AORE]',
    'accept_cargo_types': '[ENSP]',
    'prod_multiplier': '[19, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '6',
    'prob_in_game': '10',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '238',
    'map_colour': '71',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
biorefinery = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[biorefinery_industry_layout_1_tilelayout, biorefinery_industry_layout_2_tilelayout, biorefinery_industry_layout_3_tilelayout, biorefinery_industry_layout_4_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_BIOREFINERY)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_BIOREFINERY)',
    'prod_cargo_types': '[RFPR, PETR]',
    'accept_cargo_types': '[GRAI, SGBT]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '170',
    'map_colour': '186',
    'remove_cost_multiplier': '0',
    'spec_flags': 'bitmask(IND_FLAG_MILITARY_AIRPLANE_CAN_EXPLODE)',
},
)
brewery = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[brewery_industry_layout_1_tilelayout, brewery_industry_layout_2_tilelayout, brewery_industry_layout_3_tilelayout, brewery_industry_layout_4_tilelayout, brewery_industry_layout_5_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_BREWERY)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_BREWERY)',
    'prod_cargo_types': '[BEER]',
    'accept_cargo_types': '[MNSP, FRVG, GRAI]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '50',
    'map_colour': '191',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
brick_works = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_brick_works_1, tilelayout_brick_works_2, tilelayout_brick_works_3]',
    'life_type': '4',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_BRICK_WORKS)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_BRICK_WORKS)',
    'prod_cargo_types': '[BDMT]',
    'accept_cargo_types': '[COAL, SAND, CLAY]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '120',
    'map_colour': '184',
    'remove_cost_multiplier': '0',
    'spec_flags': 'bitmask(IND_FLAG_MILITARY_HELICOPTER_CAN_EXPLODE)',
},
)
builders_yard = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_builders_yard_1, tilelayout_builders_yard_2]',
    'life_type': 'IND_LIFE_TYPE_BLACK_HOLE',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_BUILDERS_YARD)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_BUILDERS_YARD)',
    'prod_cargo_types': '[]',
    'accept_cargo_types': '[BDMT]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '0',
    'conflicting_ind_types': '[builders_yard]',
    'prob_random': '18',
    'prob_in_game': '12',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '8',
    'map_colour': '15',
    'remove_cost_multiplier': '0',
},
)
cement_plant = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_cement_plant_1, tilelayout_cement_plant_2, tilelayout_cement_plant_3, tilelayout_cement_plant_4, tilelayout_cement_plant_5]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_CEMENT_PLANT)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_CEMENT_PLANT)',
    'prod_cargo_types': '[BDMT]',
    'accept_cargo_types': '[COAL, CLAY, GRVL]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '203',
    'map_colour': '19',
    'remove_cost_multiplier': '0',
    'spec_flags': 'bitmask(IND_FLAG_MILITARY_HELICOPTER_CAN_EXPLODE)',
},
)
clay_pit = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_clay_pit_1, tilelayout_clay_pit_2]',
    'life_type': 'IND_LIFE_TYPE_EXTRACTIVE',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_CLAY_PIT)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_CLAY_PIT)',
    'prod_cargo_types': '[CLAY]',
    'accept_cargo_types': '[ENSP]',
    'prod_multiplier': '[16, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '200',
    'map_colour': '46',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
coal_mine = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'override': '0',
    'accept_cargo_types': '[ENSP]',
    'prod_multiplier': '[20, 0]',
    'input_multiplier_1': '[0, 0]',
    'conflicting_ind_types': '[]',
    'prob_random': '8',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '252',
    'map_colour': '1',
},
)
dairy = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_dairy_1, tilelayout_dairy_2, tilelayout_dairy_3, tilelayout_dairy_4, tilelayout_dairy_5, tilelayout_dairy_6, tilelayout_dairy_7]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_DAIRY)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_DAIRY)',
    'prod_cargo_types': '[FOOD]',
    'accept_cargo_types': '[MNSP, MILK]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '45',
    'map_colour': '15',
    'remove_cost_multiplier': '0',
    'spec_flags': 'bitmask(IND_FLAG_MILITARY_HELICOPTER_CAN_EXPLODE)',
},
)
dairy_farm = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_dairy_farm_1, tilelayout_dairy_farm_2, tilelayout_dairy_farm_3]',
    'life_type': 'IND_LIFE_TYPE_ORGANIC',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_FARM',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_DAIRYFARM)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_DAIRYFARM)',
    'prod_cargo_types': '[LVST, MILK]',
    'accept_cargo_types': '[FMSP]',
    'prod_multiplier': '[4, 4]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '1',
    'conflicting_ind_types': '[]',
    'prob_random': '24',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '60',
    'map_colour': '164',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
dredging_site = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_dredging_site_1]',
    'life_type': 'IND_LIFE_TYPE_EXTRACTIVE',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_DREDGING_SITE)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_DREDGING_SITE)',
    'prod_cargo_types': '[SAND, GRVL]',
    'accept_cargo_types': '[ENSP]',
    'prod_multiplier': '[13, 13]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '180',
    'map_colour': '195',
    'remove_cost_multiplier': '0',
    'spec_flags': 'bitmask(IND_FLAG_BUILT_ON_WATER, IND_FLAG_AI_CREATES_AIR_AND_SHIP_ROUTES)',
},
)
fertiliser_plant = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_fertiliser_plant_1, tilelayout_fertiliser_plant_2, tilelayout_fertiliser_plant_3, tilelayout_fertiliser_plant_4, tilelayout_fertiliser_plant_5, tilelayout_fertiliser_plant_6, tilelayout_fertiliser_plant_7]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_FERTILISER_PLANT)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_FERTILISER_PLANT)',
    'prod_cargo_types': '[FMSP]',
    'accept_cargo_types': '[RFPR]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '170',
    'map_colour': '174',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
fishing_grounds = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '5',
    'layouts': '[tilelayout_fishing_grounds_1, tilelayout_fishing_grounds_2, tilelayout_fishing_grounds_3, tilelayout_fishing_grounds_4]',
    'life_type': 'IND_LIFE_TYPE_EXTRACTIVE',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_FISHING_GROUND)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_FISHING_GROUND)',
    'prod_cargo_types': '[FISH]',
    'accept_cargo_types': '[]',
    'prod_multiplier': '[5, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '2',
    'conflicting_ind_types': '[]',
    'prob_random': '20',
    'prob_in_game': '20',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '88',
    'map_colour': '158',
    'remove_cost_multiplier': '0',
    'spec_flags': 'bitmask(IND_FLAG_BUILT_ON_WATER, IND_FLAG_NO_PRODUCTION_INCREASE, IND_FLAG_AI_CREATES_AIR_AND_SHIP_ROUTES)',
},
)
fishing_harbour = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_fishing_harbour_1, tilelayout_fishing_harbour_2, tilelayout_fishing_harbour_3, tilelayout_fishing_harbour_4, tilelayout_fishing_harbour_5]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_FISHING_HARBOUR)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_FISHING_HARBOUR)',
    'prod_cargo_types': '[FOOD]',
    'accept_cargo_types': '[MNSP, FISH]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '14',
    'prob_in_game': '8',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '150',
    'map_colour': '15',
    'remove_cost_multiplier': '0',
    'spec_flags': 'bitmask(IND_FLAG_BUILT_ON_WATER)',
},
)
food_market = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[food_market_industry_layout_tilelayout]',
    'name': 'string(STR_IND_FOOD_MARKET)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_FOOD_MARKET)',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'prod_cargo_types': '[]',
    'accept_cargo_types': '[FOOD, FRVG, BEER]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '2',
    'life_type': 'IND_LIFE_TYPE_BLACK_HOLE',
    'conflicting_ind_types': '[food_market]',
    'spec_flags': 'bitmask(IND_FLAG_ONLY_IN_TOWNS)',
    'prob_random': '24',
    'prob_in_game': '12',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '6',
    'remove_cost_multiplier': '0',
    'map_colour': '191',
},
)
forest = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': 'INDUSTRYTYPE_FOREST',
    'layouts': '[tilelayout_forest_1, tilelayout_forest_2, tilelayout_forest_3]',
    'life_type': 'IND_LIFE_TYPE_ORGANIC',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': '18437',
    'prod_cargo_types': '[WOOD]',
    'accept_cargo_types': '[FMSP]',
    'prod_multiplier': '[19]',
    'conflicting_ind_types': '[]',
    'prob_random': '8',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '95',
    'map_colour': '81',
},
)
fruit_plantation = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_5807_1, tilelayout_5807_2, tilelayout_5807_3, tilelayout_5807_4]',
    'life_type': 'IND_LIFE_TYPE_ORGANIC',
    'name': 'TTD_STR_INDUSTRY_NAME_FRUIT_PLANTATION',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'prod_cargo_types': '[FRVG]',
    'accept_cargo_types': '[FMSP]',
    'prod_multiplier': '[6]',
    'conflicting_ind_types': '[]',
    'prob_random': '18',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '54',
    'map_colour': '86',
    'spec_flags': '0',
},
)
furniture_factory = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_furniture_factory_1, tilelayout_furniture_factory_2, tilelayout_furniture_factory_3, tilelayout_furniture_factory_4, tilelayout_furniture_factory_5]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_FURNITURE_FACTORY)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_FURNITURE_FACTORY)',
    'prod_cargo_types': '[GOOD]',
    'accept_cargo_types': '[MNSP, WDPR]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '8',
    'prob_in_game': '7',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '95',
    'map_colour': '186',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
glass_works = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[glass_works_industry_layout_1_tilelayout, glass_works_industry_layout_2_tilelayout, glass_works_industry_layout_3_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_GLASS_WORKS)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_GLASS_WORKS)',
    'prod_cargo_types': '[BDMT, MNSP]',
    'accept_cargo_types': '[SAND, RFPR]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '95',
    'map_colour': '146',
    'remove_cost_multiplier': '0',
    'spec_flags': 'bitmask(IND_FLAG_MILITARY_HELICOPTER_CAN_EXPLODE)',
},
)
grain_mill = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[grain_mill_industry_layout_1_tilelayout, grain_mill_industry_layout_2_tilelayout, grain_mill_industry_layout_3_tilelayout, grain_mill_industry_layout_4_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_GRAIN_MILL)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_GRAIN_MILL)',
    'prod_cargo_types': '[FOOD]',
    'accept_cargo_types': '[MNSP, GRAI]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '10',
    'prob_in_game': '10',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '44',
    'map_colour': '48',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
hardware_store = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[hardware_store_industry_layout_tilelayout]',
    'name': 'string(STR_IND_HARDWARE_STORE)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_HARDWARE_STORE)',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'prod_cargo_types': '[]',
    'accept_cargo_types': '[GOOD, BDMT]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '2',
    'life_type': 'IND_LIFE_TYPE_BLACK_HOLE',
    'conflicting_ind_types': '[hardware_store]',
    'spec_flags': 'bitmask(IND_FLAG_ONLY_IN_TOWNS)',
    'prob_random': '24',
    'prob_in_game': '12',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '6',
    'map_colour': '15',
    'remove_cost_multiplier': '0',
},
)
hotel = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[hotel_industry_layout_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_BLACK_HOLE',
    'name': 'string(STR_IND_HOTEL)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_HOTEL)',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'prod_cargo_types': '[PASS]',
    'accept_cargo_types': '[FOOD, BEER, PASS]',
    'prod_multiplier': '[20, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '2',
    'conflicting_ind_types': '[hotel]',
    'prob_random': '10',
    'prob_in_game': '20',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '15',
    'map_colour': '190',
    'remove_cost_multiplier': '0',
    'spec_flags': 'bitmask(IND_FLAG_BUILT_NEAR_TOWN)',
},
)
iron_works = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_iron_works_1]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_IRON_WORKS)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_IRON_WORKS)',
    'prod_cargo_types': '[STEL]',
    'accept_cargo_types': '[IORE, WOOD]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '69',
    'map_colour': '194',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
iron_ore_mine = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '18',
    'override': '18',
    'accept_cargo_types': '[ENSP]',
    'prod_multiplier': '[19]',
    'conflicting_ind_types': '[]',
    'prob_random': '7',
    'prob_in_game': '4',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '232',
    'map_colour': '55',
},
)
junk_yard = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_junkyard_1, tilelayout_junkyard_2, tilelayout_junkyard_3]',
    'life_type': 'IND_LIFE_TYPE_EXTRACTIVE',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_JUNKYARD)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_JUNKYARD)',
    'prod_cargo_types': '[SCMT]',
    'accept_cargo_types': '[ENSP]',
    'prod_multiplier': '[12, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '7',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '101',
    'map_colour': '36',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
lime_kiln = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_lime_kiln_1, tilelayout_lime_kiln_2, tilelayout_lime_kiln_3]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_LIME_KILN)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_LIME_KILN)',
    'prod_cargo_types': '[RFPR, FMSP]',
    'accept_cargo_types': '[GRVL, COAL]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '7',
    'prob_in_game': '6',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '45',
    'map_colour': '209',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
lumber_yard = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[lumber_yard_industry_layout_1_tilelayout, lumber_yard_industry_layout_2_tilelayout, lumber_yard_industry_layout_3_tilelayout, lumber_yard_industry_layout_4_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_LUMBER_YARD)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_LUMBER_YARD)',
    'prod_cargo_types': '[ENSP, BDMT]',
    'accept_cargo_types': '[WDPR, RFPR]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '35',
    'map_colour': '42',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
machine_shop = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_machine_shop_1, tilelayout_machine_shop_2, tilelayout_machine_shop_3, tilelayout_machine_shop_4, tilelayout_machine_shop_5]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_MACHINE_SHOP)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_MACHINE_SHOP)',
    'prod_cargo_types': '[FMSP, ENSP]',
    'accept_cargo_types': '[STEL, PETR]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '145',
    'map_colour': '48',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
metal_fabrication_plant = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_metal_fabrication_plant_1, tilelayout_metal_fabrication_plant_2, tilelayout_metal_fabrication_plant_3]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_METAL_FABRICATION_PLANT)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_METAL_FABRICATION_PLANT)',
    'prod_cargo_types': '[BDMT]',
    'accept_cargo_types': '[STEL, RFPR]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '120',
    'map_colour': '191',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
metal_foundry = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_metal_foundry_1, tilelayout_metal_foundry_2]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_METAL_FOUNDRY)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_METAL_FOUNDRY)',
    'prod_cargo_types': '[GOOD, MNSP]',
    'accept_cargo_types': '[STEL, RFPR]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '120',
    'map_colour': '123',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
mixed_farm = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_mixed_farm_1, tilelayout_mixed_farm_2, tilelayout_mixed_farm_3]',
    'life_type': 'IND_LIFE_TYPE_ORGANIC',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_FARM',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_MIXEDFARM)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_MIXEDFARM)',
    'prod_cargo_types': '[LVST, FICR]',
    'accept_cargo_types': '[FMSP]',
    'prod_multiplier': '[7, 7]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '1',
    'conflicting_ind_types': '[]',
    'prob_random': '24',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '49',
    'map_colour': '7',
    'remove_cost_multiplier': '0',
    'spec_flags': 'bitmask(IND_FLAG_PLANT_FIELDS_PERIODICALLY, IND_FLAG_PLANT_FIELDS_WHEN_BUILT)',
},
)
oil_rig = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '5',
    'override': '5',
    'name': '18439',
    'prod_cargo_types': '[OIL_, PASS]',
    'accept_cargo_types': '[ENSP]',
    'prod_multiplier': '[29, 4]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'conflicting_ind_types': '[]',
    'prob_random': '6',
    'prob_in_game': '6',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '255',
    'map_colour': '152',
},
)
oil_wells = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[oil_wells_industry_layout_1_tilelayout, oil_wells_industry_layout_2_tilelayout, oil_wells_industry_layout_3_tilelayout, oil_wells_industry_layout_4_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_ORGANIC',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': '18445',
    'prod_cargo_types': '[OIL_]',
    'accept_cargo_types': '[ENSP]',
    'prod_multiplier': '[28]',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '230',
    'map_colour': '152',
    'spec_flags': '0',
},
)
oil_refinery = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '4',
    'override': '4',
    'prod_cargo_types': '[RFPR, PETR]',
    'accept_cargo_types': '[OIL_]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'conflicting_ind_types': '[]',
    'prob_random': '4',
    'prob_in_game': '2',
    'fund_cost_multiplier': '200',
    'map_colour': '191',
    'spec_flags': '0',
},
)
paper_mill = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '14',
    'override': '14',
    'prod_cargo_types': '[GOOD, MNSP]',
    'accept_cargo_types': '[CLAY, WOOD, RFPR]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '2',
    'fund_cost_multiplier': '120',
    'map_colour': '184',
},
)
petrol_pump = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[petrol_pump_industry_layout_1_tilelayout, petrol_pump_industry_layout_2_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_BLACK_HOLE',
    'name': 'string(STR_IND_PETROLPUMP)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_PETROLPUMP)',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'prod_cargo_types': '[]',
    'accept_cargo_types': '[FOOD, GOOD, PETR]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '2',
    'conflicting_ind_types': '[]',
    'spec_flags': '0',
    'prob_random': '14',
    'prob_in_game': '14',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '8',
    'remove_cost_multiplier': '0',
    'map_colour': '15',
},
)
plastics_plant = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[plastics_plant_industry_layout_1_tilelayout, plastics_plant_industry_layout_2_tilelayout, plastics_plant_industry_layout_3_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_PLASTICS_PLANT)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_PLASTICS_PLANT)',
    'prod_cargo_types': '[GOOD, MNSP]',
    'accept_cargo_types': '[RFPR, FICR]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '125',
    'map_colour': '208',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
quarry = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[tilelayout_quarry_1, tilelayout_quarry_2]',
    'life_type': 'IND_LIFE_TYPE_EXTRACTIVE',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_QUARRY)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_QUARRY)',
    'prod_cargo_types': '[SAND, GRVL]',
    'accept_cargo_types': '[ENSP]',
    'prod_multiplier': '[14, 14]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '210',
    'map_colour': '195',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
recycling_plant = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[recycling_plant_industry_layout_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_FARM',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_RECYCLING_PLANT)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_RECYCLING_PLANT)',
    'prod_cargo_types': '[SCMT, MNSP]',
    'accept_cargo_types': '[RCYC]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '7',
    'prob_in_game': '7',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '118',
    'map_colour': '164',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
recycling_depot = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[recycling_depot_industry_layout_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_EXTRACTIVE',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_RECYCLING_DEPOT)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_RECYCLING_DEPOT)',
    'prod_cargo_types': '[RCYC]',
    'accept_cargo_types': '[]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '2',
    'conflicting_ind_types': '[]',
    'prob_random': '20',
    'prob_in_game': '20',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '118',
    'map_colour': '191',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
sheep_farm = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[sheep_farm_industry_layout_1_tilelayout, sheep_farm_industry_layout_2_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_ORGANIC',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_FARM',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_SHEEPFARM)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_SHEEPFARM)',
    'prod_cargo_types': '[LVST, WOOL]',
    'accept_cargo_types': '[FMSP]',
    'prod_multiplier': '[4, 4]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '1',
    'conflicting_ind_types': '[]',
    'prob_random': '21',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '45',
    'map_colour': '14',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)
smithy_forge = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[smithy_forge_industry_layout_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_SMITHY_FORGE)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_SMITHY_FORGE)',
    'prod_cargo_types': '[ENSP, FMSP]',
    'accept_cargo_types': '[STEL]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '2',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '63',
    'map_colour': '133',
    'remove_cost_multiplier': '0',
    'spec_flags': 'bitmask(IND_FLAG_ONLY_IN_TOWNS)',
},
)
steel_mill = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '8',
    'override': '8',
    'accept_cargo_types': '[IORE, COAL, SCMT]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '2',
    'fund_cost_multiplier': '200',
    'map_colour': '9',
},
)
stockyard = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[stockyard_industry_layout_1_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_STOCKYARD)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_STOCKYARD)',
    'prod_cargo_types': '[FOOD]',
    'accept_cargo_types': '[MNSP, LVST]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '145',
    'map_colour': '176',
    'remove_cost_multiplier': '0',
    'spec_flags': 'bitmask(IND_FLAG_MILITARY_HELICOPTER_CAN_EXPLODE)',
},
)
sugar_refinery = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '0',
    'layouts': '[sugar_refinery_industry_layout_1_tilelayout]',
    'life_type': '4',
    'name': 'string(STR_IND_SUGAR_REFINERY)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_SUGAR_REFINERY)',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'prod_cargo_types': '[FOOD]',
    'accept_cargo_types': '[MNSP, SGBT]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '3',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '140',
    'map_colour': '83',
    'remove_cost_multiplier': '0',
    'spec_flags': 'bitmask(IND_FLAG_MILITARY_AIRPLANE_CAN_EXPLODE)',
},
)
sawmill = dict(type =  'FEAT_INDUSTRYTILES' ,
properties = {
    'substitute': '2',
    'override': '2',
    'prod_cargo_types': '[WDPR]',
    'accept_cargo_types': '[WOOD]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'conflicting_ind_types': '[]',
    'prob_random': '5',
    'prob_in_game': '2',
    'fund_cost_multiplier': '97',
    'map_colour': '194',
},
)
textile_mill = dict(type =  'FEAT_INDUSTRIES' ,
properties = {
    'substitute': '0',
    'layouts': '[textile_mill_industry_layout_1_tilelayout, textile_mill_industry_layout_2_tilelayout, textile_mill_industry_layout_3_tilelayout, textile_mill_industry_layout_4_tilelayout, textile_mill_industry_layout_5_tilelayout, textile_mill_industry_layout_6_tilelayout]',
    'life_type': 'IND_LIFE_TYPE_PROCESSING',
    'closure_msg': 'TTD_STR_NEWS_INDUSTRY_CLOSURE_SUPPLY_PROBLEMS',
    'prod_increase_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_INCREASE_GENERAL',
    'prod_decrease_msg': 'TTD_STR_NEWS_INDUSTRY_PRODUCTION_DECREASE_GENERAL',
    'new_ind_msg': 'TTD_STR_NEWS_INDUSTRY_CONSTRUCTION',
    'name': 'string(STR_IND_TEXTILE_MILL)',
    'nearby_station_name': 'string(STR_STATION, string(STR_TOWN), string(STR_IND_TEXTILE_MILL)',
    'prod_cargo_types': '[GOOD]',
    'accept_cargo_types': '[MNSP, WOOL, FICR]',
    'prod_multiplier': '[0, 0]',
    'input_multiplier_1': '[0, 0]',
    'input_multiplier_2': '[0, 0]',
    'input_multiplier_3': '[0, 0]',
    'min_cargo_distr': '5',
    'conflicting_ind_types': '[]',
    'prob_random': '8',
    'prob_in_game': '7',
    'prospect_chance': '0.75',
    'fund_cost_multiplier': '120',
    'map_colour': '37',
    'remove_cost_multiplier': '0',
    'spec_flags': '0',
},
)

print 'industries = dict('
print 'aluminium_plant=', aluminium_plant,','
print 'arable_farm=', arable_farm,','
print 'bauxite_mine=', bauxite_mine,','
print 'biorefinery=', biorefinery,','
print 'brewery=', brewery,','
print 'brick_works=', brick_works,','
print 'builders_yard=', builders_yard,','
print 'cement_plant=', cement_plant,','
print 'clay_pit=', clay_pit,','
print 'coal_mine=', coal_mine,','
print 'dairy=', dairy,','
print 'dairy_farm=', dairy_farm,','
print 'dredging_site=', dredging_site,','
print 'fertiliser_plant=', fertiliser_plant,','
print 'fishing_grounds=', fishing_grounds,','
print 'fishing_harbour=', fishing_harbour,','
print 'food_market=', food_market,','
print 'forest=', forest,','
print 'fruit_plantation=', fruit_plantation,','
print 'furniture_factory=', furniture_factory,','
print 'glass_works=', glass_works,','
print 'grain_mill=', grain_mill,','
print 'hardware_store=', hardware_store,','
print 'hotel=', hotel,','
print 'iron_works=', iron_works,','
print 'iron_ore_mine=', iron_ore_mine,','
print 'junk_yard=', junk_yard,','
print 'lime_kiln=', lime_kiln,','
print 'lumber_yard=', lumber_yard,','
print 'machine_shop=', machine_shop,','
print 'metal_fabrication_plant=', metal_fabrication_plant,','
print 'metal_foundry=', metal_foundry,','
print 'mixed_farm=', mixed_farm,','
print 'oil_rig=', oil_rig,','
print 'oil_wells=', oil_wells,','
print 'oil_refinery=', oil_refinery,','
print 'paper_mill=', paper_mill,','
print 'petrol_pump=', petrol_pump,','
print 'plastics_plant=', plastics_plant,','
print 'quarry=', quarry,','
print 'recycling_plant=', recycling_plant,','
print 'recycling_depot=', recycling_depot,','
print 'sheep_farm=', sheep_farm,','
print 'smithy_forge=', smithy_forge,','
print 'steel_mill=', steel_mill,','
print 'stockyard=', stockyard,','
print 'sugar_refinery=', sugar_refinery,','
print 'sawmill=', sawmill,','
print 'textile_mill=', textile_mill
print ')'
