[GLOBAL_PRAGMA]
grflangid = "0x38"
plural = "6"
gender = "middle male female"
case = "nom lok aku vok dat ins gen"

[STR_GRF_DESC]
base = "{ORANGE}FIRS Zamjenski Industrijski Set{}{BLACK}Od {SILVER}andythenorth{BLACK} i {SILVER}FooBar{BLACK}.{}{BLACK}'1,000 obaveza i dalje...'{BLACK}{}{}Website: {SILVER}www.tt-foundry.com/sets/FIRS{BLACK}.Licenca: {SILVER}GPL v2{BLACK}.Posebne zahvale {SILVER}Ammler{BLACK}, {SILVER}Core Xii{BLACK}, {SILVER}Irwe{BLACK}, {SILVER}planetmaker{BLACK} i {SILVER}Zephyris{BLACK}.Koristi dijelove od {SILVER}eGRVTS{BLACK}, {SILVER}ISR{BLACK} i {SILVER}OpenGFX{BLACK}."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Najveća udaljenost ribarskih polja, naftnih platformi i jaružališta od obale u poljima."

[STR_PARAM_DESC_ECONOMIES]
base = "Svaka ekonomija daje različite kombinacije tereta i industrija.{}{}Za igrače koji žele jednostavnost igre, {SILVER}Osnovne {BLACK} ekonomije imaju manje industrija i tereta nego druge FIRS ekonomije.{}{}Na FIRS web stranici se nalaze detaljne informacije o svakoj vrsti ekonomije."

[STR_PARAM_DESC_NO_OPENINGS]
base = "Po osnovnoj postavci, tijekom igre neće se otvarati nove industrije.{}{}Ako je {SILVER}\"spriječi otvaranje\" {BLACK} uključeno, industrije se neće otvarati tijekom igre, a igrači neće moći financirati ili istraživati nove industrije."

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Najveća udaljenost od obale za pomorske industrije u poljima"

[STR_PARAM_NAME_ECONOMIES]
base = "Ekonomija"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Zabrani otvaranje novih industrija tijekom igre"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Bez limita"

[STR_PARAM_NAME_PRIMARY_LEVEL1_REQUIREMENT]
base = "Kutije potrepština potrebne za Unaprijeđenu primarnu proizvodnju (osnovna postavka 16)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_REQUIREMENT]
base = "Kutije potrepština potrebne za Masovnu primarnu proizvodnju (osnovna postavka 80)"

[STR_PARAM_DESC_PRIMARY_LEVEL_REQUIREMENT]
base = "Farme, rudnici i slične industrije će povećati proizvodnju kada su kutije potrepština dostavljene, prvo na {SILVER}Unaprijeđenu{BLACK}, a onda na {SILVER}Masovnu{BLACK} proizvodnju, ako je dostavljeno dovoljno kutija.{}{}Osnovne postavke su dovoljno dobre ali ako trebate, možete ih promijeniti ovdje.{}{}Potrebe dostave tereta za industrije u lukama će biti 8x veće od vrijednosti postavljenih ovdje."

[STR_PARAM_NAME_PRIMARY_LEVEL1_BONUS]
base = "Nivo Unaprijeđene primarne proizvodnje (%)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_BONUS]
base = "Nivo Masovne primarne proizvodnje (%)"

[STR_PARAM_DESC_PRIMARY_LEVEL_BONUS]
base = "Proizvodnja na farmama, u rudnicima i sličnim industrijama kada su potrebe dostave zadovoljene (kao postotak {SILVER}Normalnog {BLACK} nivoa proizvodnje)."

[STR_PARAM_VALUE_ECONOMIES_BASIC_TEMPERATE]
base = "Osnovna - umjerena klima"

[STR_PARAM_VALUE_ECONOMIES_BASIC_ARCTIC]
base = "Osnovna - arktička klima"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TROPIC]
base = "Osnovna - tropska klima"

[STR_PARAM_VALUE_ECONOMIES_IN_A_HOT_COUNTRY]
base = "U vrućoj zemlji"

[STR_PARAM_VALUE_ECONOMIES_STEELTOWN]
base = "Grad od Čelika"

[STR_CARGO_NAME_ACID]
base = "Kiselina"

[STR_CARGO_NAME_ALCOHOL]
base = "Alkohol"

[STR_CARGO_NAME_BEANS]
base = "Grah"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "Građevni materijal"

[STR_CARGO_NAME_CASSAVA]
base = "Manioka"

[STR_CARGO_NAME_CEMENT]
base = "Cement"

[STR_CARGO_NAME_CHEMICALS]
base = "Kemikalije"

[STR_CARGO_NAME_CHLORINE]
base = "Klor"

[STR_CARGO_NAME_CLAY]
base = "Glina"

[STR_CARGO_NAME_COFFEE]
base = "Kava"

[STR_CARGO_NAME_COKE]
base = "Koks"

[STR_CARGO_NAME_COPPER]
base = "Bakar"

[STR_CARGO_NAME_EDIBLE_OIL]
base = "Jestivo ulje"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "Inžinjerske potrepštine"

[STR_CARGO_NAME_EXPLOSIVES]
base = "Eksplozivi"

[STR_CARGO_NAME_FISH]
base = "Riba"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "Poljoprivredne potrepštine"

[STR_CARGO_NAME_FERTILISER]
base = "Gnojivo"

[STR_CARGO_NAME_FRUITS]
base = "Voće"

[STR_CARGO_NAME_KAOLIN]
base = "Kaolinit"

[STR_CARGO_NAME_LIMESTONE]
base = "Vapnenac"

[STR_CARGO_NAME_TIMBER]
base = "Drvo"

[STR_CARGO_NAME_MILK]
base = "Mlijeko"

[STR_CARGO_NAME_MANGANESE]
base = "Mangan"

[STR_CARGO_NAME_NITRATES]
base = "Nitrati"

[STR_CARGO_NAME_NUTS]
base = "Orasi"

[STR_CARGO_NAME_PEAT]
base = "Treset"

[STR_CARGO_NAME_PETROL]
base = "Benzin"

[STR_CARGO_NAME_PHOSPHATE]
base = "Fosfati"

[STR_CARGO_NAME_PIG_IRON]
base = "Sirovo željezo"

[STR_CARGO_NAME_POTASH]
base = "Potaša"

[STR_CARGO_NAME_PYRITE_ORE]
base = "Pirit"

[STR_CARGO_NAME_QUICKLIME]
base = "Živo vapno"

[STR_CARGO_NAME_SALT]
base = "Sol"

[STR_CARGO_NAME_SAND]
base = "Pijesak"

[STR_CARGO_NAME_SCRAP_METAL]
base = "Otpadni metal"

[STR_CARGO_NAME_SLAG]
base = "Šljaka"

[STR_CARGO_NAME_SODA_ASH]
base = "Soda"

[STR_CARGO_NAME_STEEL]
base = "Čelik"

[STR_CARGO_NAME_AGGREGATES]
base = "Kamen"

[STR_CARGO_NAME_SULPHUR]
base = "Sumpor"

[STR_CARGO_NAME_VEHICLE_BODIES]
base = "Karoserije vozila"

[STR_CARGO_NAME_VEHICLE_PARTS]
base = "Dijelovi za vozila"

[STR_CARGO_NAME_VEHICLES]
base = "Vozila"

[STR_CARGO_NAME_WOOL]
base = "Vuna"

[STR_CARGO_NAME_ZINC]
base = "Cink"

[STR_CARGO_UNIT_ACID]
base = "{VOLUME} kiseline"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} alkohola"

[STR_CARGO_UNIT_BEANS]
base = "{WEIGHT} graha"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} građevnog materijala"

[STR_CARGO_UNIT_CASSAVA]
base = "{WEIGHT} manioke"

[STR_CARGO_UNIT_CEMENT]
base = "{WEIGHT} cementa"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} kemikalija"

[STR_CARGO_UNIT_CHLORINE]
base = "{VOLUME} klora"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} gline"

[STR_CARGO_UNIT_COFFEE]
base = "{SIGNED_WORD} vreć{P a e e} kave"

[STR_CARGO_UNIT_COKE]
base = "{WEIGHT} koksa"

[STR_CARGO_UNIT_COPPER]
base = "{WEIGHT} bakra"

[STR_CARGO_UNIT_EDIBLE_OIL]
base = "{VOLUME} jestivog ulja"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} kutij{P 0 a e e} inžinjerskih potrepština"

[STR_CARGO_UNIT_EXPLOSIVES]
base = "{SIGNED_WORD} kutij{P 0 a e e} eksploziva"

[STR_CARGO_UNIT_FERTILISER]
base = "{WEIGHT} gnojiva"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} ribe"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} kutij{P 0 a e e} poljoprivrednih potrepština"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} voća"

[STR_CARGO_UNIT_KAOLIN]
base = "{WEIGHT} kaolinita"

[STR_CARGO_UNIT_LIMESTONE]
base = "{WEIGHT} vapnenca"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} drva"

[STR_CARGO_UNIT_LYE]
base = "{VOLUME} lužine"

[STR_CARGO_UNIT_MANGANESE]
base = "{WEIGHT} mangana"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} mlijeka"

[STR_CARGO_UNIT_NICKEL]
base = "{WEIGHT} nikla"

[STR_CARGO_UNIT_NITRATES]
base = "{WEIGHT} nitrata"

[STR_CARGO_UNIT_NUTS]
base = "{SIGNED_WORD} vreć{P a e e} oraha"

[STR_CARGO_UNIT_PEAT]
base = "{WEIGHT} treseta"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} benzina"

[STR_CARGO_UNIT_PHOSPHATE]
base = "{WEIGHT} fosfata"

[STR_CARGO_UNIT_PIG_IRON]
base = "{WEIGHT} sirovog željeza"

[STR_CARGO_UNIT_POTASH]
base = "{WEIGHT} potaša"

[STR_CARGO_UNIT_PYRITE_ORE]
base = "{WEIGHT} pirita"

[STR_CARGO_UNIT_QUICKLIME]
base = "{WEIGHT} živog vapna"

[STR_CARGO_UNIT_SALT]
base = "{WEIGHT} soli"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} pijeska"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} otpadnog metala"

[STR_CARGO_UNIT_SLAG]
base = "{WEIGHT} šljake"

[STR_CARGO_UNIT_SODA_ASH]
base = "{WEIGHT} sode"

[STR_CARGO_UNIT_STEEL]
base = "{WEIGHT} čelika"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} kamena"

[STR_CARGO_UNIT_SULPHUR]
base = "{WEIGHT} sumpora"

[STR_CARGO_UNIT_VEHICLE_BODIES]
base = "{WEIGHT} karoserija"

[STR_CARGO_UNIT_VEHICLE_PARTS]
base = "{WEIGHT} dijelova za vozila"

[STR_CARGO_UNIT_VEHICLES]
base = "{WEIGHT} vozila"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} bal{P 0 a e e} vune"

[STR_CARGO_UNIT_ZINC]
base = "{WEIGHT} cinka"

[STR_CID_ACID]
base = "{TINYFONT}KI"

[STR_CID_ALCOHOL]
base = "{TINYFONT}AL"

[STR_CID_BEANS]
base = "{TINYFONT}GH"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}GM"

[STR_CID_CASSAVA]
base = "{TINYFONT}MA"

[STR_CID_CEMENT]
base = "{TINYFONT}CE"

[STR_CID_CHEMICALS]
base = "{TINYFONT}KM"

[STR_CID_CHLORINE]
base = "{TINYFONT}KL"

[STR_CID_CLAY]
base = "{TINYFONT}GL"

[STR_CID_COFFEE]
base = "{TINYFONT}KV"

[STR_CID_COKE]
base = "{TINYFONT}KK"

[STR_CID_COPPER]
base = "{TINYFONT}BA"

[STR_CID_EDIBLE_OIL]
base = "{TINYFONT}JU"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}IP"

[STR_CID_EXPLOSIVES]
base = "{TINYFONT}EX"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}AP"

[STR_CID_FERTILISER]
base = "{TINYFONT}GN"

[STR_CID_FISH]
base = "{TINYFONT}RI"

[STR_CID_KAOLIN]
base = "{TINYFONT}KN"

[STR_CID_LIMESTONE]
base = "{TINYFONT}VA"

[STR_CID_TIMBER]
base = "{TINYFONT}DR"

[STR_CID_LYE]
base = "{TINYFONT}LU"

[STR_CID_MANGANESE]
base = "{TINYFONT}MN"

[STR_CID_MILK]
base = "{TINYFONT}MK"

[STR_CID_NICKEL]
base = "{TINYFONT}NK"

[STR_CID_NITRATES]
base = "{TINYFONT}NI"

[STR_CID_NUTS]
base = "{TINYFONT}OR"

[STR_CID_PEAT]
base = "{TINYFONT}TR"

[STR_CID_PETROL]
base = "{TINYFONT}BE"

[STR_CID_PIG_IRON]
base = "{TINYFONT}SŽ"

[STR_CID_PHOSPHATE]
base = "{TINYFONT}FO"

[STR_CID_POTASH]
base = "{TINYFONT}PA"

[STR_CID_PYRITE_ORE]
base = "{TINYFONT}PR"

[STR_CID_QUICKLIME]
base = "{TINYFONT}ŽV"

[STR_CID_SALT]
base = "{TINYFONT}SO"

[STR_CID_SAND]
base = "{TINYFONT}PI"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}OM"

[STR_CID_SLAG]
base = "{TINYFONT}ŠLJ"

[STR_CID_SODA_ASH]
base = "{TINYFONT}SD"

[STR_CID_STEEL]
base = "{TINYFONT}ČE"

[STR_CID_AGGREGATES]
base = "{TINYFONT}KA"

[STR_CID_SULPHUR]
base = "{TINYFONT}SU"

[STR_CID_VEHICLE_BODIES]
base = "{TINYFONT}KR"

[STR_CID_VEHICLE_PARTS]
base = "{TINYFONT}DV"

[STR_CID_VEHICLES]
base = "{TINYFONT}VO"

[STR_CID_WOOL]
base = "{TINYFONT}VU"

[STR_CID_ZINC]
base = "{TINYFONT}CN"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}FIRS nije predviđen za korištenje u Zemlji igračaka"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "mora biti smješteno ispod linije snijega."

[STR_ERR_LOCATION_NOT_BELOW_SNOWLINE]
base = "mora biti smješteno iznad linije snijega."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "mora biti smješteno na kopnu."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "ne smije biti smješteno u pustinji."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "ne može biti smješteno na nagibima."

[STR_ERR_LOCATION_LIMIT_1_PER_TOWN]
base = "dozvoljena je samo jedna industrija ovog tipa po gradu."

[STR_IND_ALUMINIUM_PLANT]
base = "Ljevaonica aluminija"

[STR_IND_AMMONIA_PLANT]
base = "Tvornica amonijaka"

[STR_IND_ARABLE_FARM]
base = "Poljoprivredna farma"

[STR_IND_ASSEMBLY_PLANT]
base = "Tvornica vozila"

[STR_IND_BASIC_OXYGEN_FURNACE]
base = "Oksidacijska peć"

[STR_IND_BIOREFINERY]
base = "Biorafinerija"

[STR_IND_BLAST_FURNACE]
base = "Visoka peć"

[STR_IND_BREWERY]
base = "Pivovara"

[STR_IND_CIDER_MILL]
base = "Mlin za jabukovaču"

[STR_IND_BRICK_WORKS]
base = "Ciglana"

[STR_IND_BUILDERS_YARD]
base = "Građevinsko dvorište"

[STR_IND_BULK_TERMINAL]
base = "Terminal za rasuti teret"

[STR_IND_CEMENT_PLANT]
base = "Cementara"

[STR_IND_CHEMICAL_PLANT]
base = "Kemijsko postrojenje"

[STR_IND_CLAY_PIT]
base = "Kop gline"

[STR_IND_COFFEE_ESTATE]
base = "Plantaža kave"

[STR_IND_COKE_OVEN]
base = "Koksna peć"

[STR_IND_COPPER_SMELTER]
base = "Rafinerija bakra"

[STR_IND_DAIRY]
base = "Mljekara"

[STR_IND_DAIRY_FARM]
base = "Mliječna farma"

[STR_IND_DREDGING_SITE]
base = "Jaružalište"

[STR_IND_ELECTRIC_ARC_FURNACE]
base = "Elektrolučna peć"

[STR_IND_FISHING_GROUND]
base = "Ribarsko polje"

[STR_IND_FISHING_HARBOUR]
base = "Ribarska luka"

[STR_IND_FISHING_VILLAGE]
base = "Ribarsko naselje"

[STR_IND_FLOUR_MILL]
base = "Mlin za brašno"

[STR_IND_FOOD_MARKET]
base = "Prehrambena tržnica"

[STR_IND_FOOD_PROCESSOR]
base = "Tvornica za preradu hrane"

[STR_IND_FURNITURE_FACTORY]
base = "Tvornica namještaja"

[STR_IND_GENERAL_STORE]
base = "Trgovina općom robom"

[STR_IND_GLASS_WORKS]
base = "Staklarna"

[STR_IND_HARDWARE_STORE]
base = "Trgovina opremom"

[STR_IND_HOTEL]
base = "Hotel"

[STR_IND_HERDING_COOP]
base = "Lovački kamp"

[STR_IND_SCRAP_YARD]
base = "Odlagalište otpada"

[STR_IND_LIME_KILN]
base = "Vapnara"

[STR_IND_LIMESTONE_MINE]
base = "Rudnik vapnenca"

[STR_IND_LIQUIDS_TERMINAL]
base = "Terminal za tekuće terete"

[STR_IND_TIMBER_YARD]
base = "Pilana"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "Trgovina strojevima"

[STR_IND_MANGANESE_MINE]
base = "Rudnik mangana"

[STR_IND_MIXEDFARM]
base = "Miješana farma"

[STR_IND_NITRATE_MINE]
base = "Rudnik nitrata"

[STR_IND_ORCHARD_PIGGERY]
base = "Voćnjak i svinjac"

[STR_IND_PEATLANDS]
base = "Tresetišta"

[STR_IND_PETROLPUMP]
base = "Benzinska pumpa"

[STR_IND_PHOSPHATE_MINE]
base = "Rudnik fosfata"

[STR_IND_PLASTICS_PLANT]
base = "Tvornica plastike"

[STR_IND_PORT]
base = "Luka"

[STR_IND_POTASH_MINE]
base = "Rudnik potaše"

[STR_IND_PYRITE_MINE]
base = "Rudnik pirita"

[STR_IND_PYRITE_SMELTER]
base = "Talionica pirita"

[STR_IND_POWER_PLANT]
base = "Elektrana"

[STR_IND_QUARRY]
base = "Kamenolom"

[STR_IND_RANCH]
base = "Ranč"

[STR_IND_SHEEPFARM]
base = "Ovčja farma"

[STR_IND_SLAG_GRINDING_PLANT]
base = "Postrojenje za mljevenje šljake"

[STR_IND_SMITHY_FORGE]
base = "Kovačnica"

[STR_IND_SODA_ASH_MINE]
base = "Rudnik sode"

[STR_IND_STOCKYARD]
base = "Stočno dvorište"

[STR_IND_SUGAR_REFINERY]
base = "Šećerana"

[STR_IND_SUPPLY_YARD]
base = "Dostavno skladište"

[STR_IND_TEXTILE_MILL]
base = "Tvornica tekstila"

[STR_IND_TRADING_POST]
base = "Trgovačka kuća"

[STR_IND_TYRE_PLANT]
base = "Tvornica guma"

[STR_IND_VINEYARD]
base = "Vinograd"

[STR_IND_WHARF]
base = "Pristanište"

[STR_CARGO_SUBTYPE_DISPLAY_CARGO_SUPPLIED_FLAG]
base = "{BLACK}(dostavljeno)"

[STR_EXTRA_TEXT_SECONDARY_NON_COMBINATORY]
base = "{BLACK}Proizvodi na najvećem nivou ako se dostavi {WHITE}bilo koji {BLACK}potrebni teret."

[STR_PRIMARY_PRODUCTION_1X]
base = "{BLACK}Trenutna proizvodnja: {YELLOW}Normalna{}{}{BLACK}Za povećavanje proizvodnje na {WHITE}Unaprijeđenu{BLACK} dostavite {SIGNED_WORD} kutija potrepština unutar tri mjeseca{}Za povećavanje proizvodnje na {WHITE}Masovnu{BLACK} dostavite {SIGNED_WORD} kutija."

[STR_PRIMARY_PRODUCTION_2X]
base = "{BLACK}Trenutna proizvodnja: {YELLOW}Unaprijeđena{}{}{BLACK}Za zadržavanje ovog nivoa, dostavite {SIGNED_WORD} kutija potrepština unutar tri mjeseca{}Za povećavanje proizvodnje na {WHITE}Masovnu{BLACK} dostavite {SIGNED_WORD} kutija."

[STR_PRIMARY_PRODUCTION_4X]
base = "{BLACK}Trenutna proizvodnja: {YELLOW}Masovna{}{}{BLACK}Za zadržavanje ovog nivoa, dostavite {SKIP}{SIGNED_WORD} kutija potrepština unutar tri mjeseca."

[STR_PORT_PRODUCTION_1X]
base = "{BLACK}Trenutna proizvodnja: {YELLOW}Normalna{}{}{BLACK}Za {WHITE}Unaprijeđenu{BLACK}proizvodnju dostavite {SIGNED_WORD} jedinica tereta unutar tri mjeseca.{}Za {WHITE}Masovnu {BLACK}proizvodnju dostavite {SIGNED_WORD} jedinica tereta."

[STR_PORT_PRODUCTION_2X]
base = "{BLACK}Trenutna proizvodnja: {YELLOW}Unaprijeđena{}{}{BLACK}Za zadržavanje ovog nivoa, dostavite {SIGNED_WORD} jedinica tereta unutar tri mjeseca{}Za povećavanje proizvodnje na {WHITE}Masovnu{BLACK} dostavite {SIGNED_WORD} jedinica tereta."

[STR_PORT_PRODUCTION_4X]
base = "{BLACK}Trenutna proizvodnja: {YELLOW}Masovna{}{}{BLACK}Za zadržavanje ovog nivoa, dostavite {SKIP}{SIGNED_WORD} jedinica tereta unutar tri mjeseca."

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Lokacija: {YELLOW}Ne može se financirati na snijegu ili u pustinji ili na padinama."

[STR_FUND_COFFEE_ESTATE]
base = "{}{BLACK}Lokacija: {YELLOW}Ne može biti financirano na snijegu ili u pustinjama."

[STR_FUND_DAIRY_FARM]
base = "{}{BLACK}Lokacija: {YELLOW}Ne može biti financirano na snijegu ili u pustinjama."

[STR_FUND_FOREST]
base = "{}{BLACK}Lokacija: {YELLOW}Ne može se financirati u pustinji."

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Lokacija: {YELLOW}Ne može se financirati na snijegu."

[STR_FUND_HERDING_COOP]
base = "{}{BLACK}Lokacija: {YELLOW}Mora se financirati na snijegu."

[STR_FUND_ORCHARD_PIGGERY]
base = "{}{BLACK}Lokacija: {YELLOW}Ne može biti financirano na snijegu ili u pustinjama."

[STR_FUND_RUBBER_PLANTATION]
base = "{}{BLACK}Lokacija: {YELLOW}Ne može biti financirano na snijegu ili u pustinjama."

[STR_FUND_VINEYARD]
base = "{}{BLACK}Lokacija: {YELLOW}Ne može biti financirano na snijegu ili u pustinjama."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}Dostupno od: {YELLOW}{COMMA}"

[STR_FUND_AVAILABLE_UNTIL]
base = "{}{BLACK}Nije dostupno nakon: {YELLOW}{COMMA}"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING} {STRING}"

[STR_STATION_ANIMALS]
base = "Tržnica konja"

[STR_STATION_AUTOMOTIVE]
base = "Automobilska"

[STR_STATION_BAR_GRILL_AND_ROOMS]
base = "Bar, roštilj i sobe"

[STR_STATION_BARNS]
base = "Štale"

[STR_STATION_BARREL_AND_KEG]
base = "Bačva i krigla"

[STR_STATION_BASE]
base = "Baza"

[STR_STATION_BONEYARD]
base = "Groblje"

[STR_STATION_BANK_TOP]
base = "Nasip"

[STR_STATION_COLLIERY]
base = "Ugljenokop"

[STR_STATION_COPPER_LODE]
base = "Bakrena žila"

[STR_STATION_CREOSOTING]
base = "Asfaltiranje"

[STR_STATION_DAIRY_LANE]
base = "Mljekarska ulica"

[STR_STATION_ESTATE]
base = "Imanje"

[STR_STATION_FARM_1]
base = "Imanje"

[STR_STATION_FARM_2]
base = "Livade"

[STR_STATION_FARM_3]
base = "Ranč"

[STR_STATION_FISHMARKET]
base = "Tržnica ribe"

[STR_STATION_FOOD_CORPORATION]
base = "Prehrambeni koncern"

[STR_STATION_FOREST]
base = "Čistina za ukrcaj trupaca"

[STR_STATION_FURNACE]
base = "Peć"

[STR_STATION_HEAVY_INDUSTRY_2]
base = "Radionica"

[STR_STATION_HERDING_COOP]
base = "Lovačka kuća"

[STR_STATION_INDUSTRY_ESTATE_1]
base = "Industrijski park"

[STR_STATION_INDUSTRY_HARBOUR_1]
base = "Industrijska luka"

[STR_STATION_INDUSTRY_HARBOUR_2]
base = "Obalna luka"

[STR_STATION_INDUSTRY_HARBOUR_3]
base = "Privezište"

[STR_STATION_IRONSTONE]
base = "Željezna rudača"

[STR_STATION_KILNS]
base = "Peći za sušenje"

[STR_STATION_KIMBERLITE_DEPOSITS]
base = "Naslage kimberlita"

[STR_STATION_LIMESTONE_MINES]
base = "Rudnici vapnenca"

[STR_STATION_MANGANESE_MINES]
base = "Rudnici mangana"

[STR_STATION_MILL]
base = "Mlin"

[STR_STATION_MOULDINGS]
base = "Modeliranje"

[STR_STATION_OIL_RIG]
base = "Polje"

[STR_STATION_ORCHARDS]
base = "Voćnjaci"

[STR_STATION_PIT]
base = "Rupa"

[STR_STATION_PLANTATION]
base = "Plantaža"

[STR_STATION_POWERHUNGRY]
base = "Elektrana"

[STR_STATION_PUMPS]
base = "Pumpe"

[STR_STATION_PYRITES]
base = "Naslage pirita"

[STR_STATION_REFINERY]
base = "Rafinerija"

[STR_STATION_RUBBER_COMPANY]
base = "Tvornica gume"

[STR_STATION_SALTPETER_WORKS]
base = "Prerada salitre"

[STR_STATION_SHARP_STREET]
base = "Oštra ulica"

[STR_STATION_SHEEP_FOLD]
base = "Tor za ovce"

[STR_STATION_SHOALS]
base = "Plićaci"

[STR_STATION_SILO]
base = "Silos"

[STR_STATION_SMELTER]
base = "Talionica"

[STR_STATION_SUGAR_COMPANY]
base = "Šećerana"

[STR_STATION_TANK_FARM]
base = "Skladište tekućih tereta"

[STR_STATION_TAPPERS_SHED]
base = "Zvučna kutija"

[STR_STATION_TOWN_1]
base = "Stara vijećnica"

[STR_STATION_TOWN_3]
base = "Dućani"

[STR_STATION_TRONA_BEDS]
base = "Naslage natrona"

[STR_STATION_WATER]
base = "Sprud"

[STR_STATION_WELLS]
base = "Izvori"

[STR_STATION_WINERY]
base = "Vinski podrum"
