[GLOBAL_PRAGMA]
grflangid = "0x15"
plural = "10"
gender = "fp map f mnp m n np"
case = "acc nom loc big voc ins dat small gen"

[STR_GRF_DESC]
base = "{ORANGE}FIRS Industry Replacement Set{}{BLACK}By {SILVER}andythenorth{BLACK} and {SILVER}FooBar{BLACK}.{}{BLACK}'1,000 commits and counting...'{BLACK}{}{}Website: {SILVER}www.tt-foundry.com/sets/FIRS{BLACK}.License: {SILVER}GPL v2{BLACK}.Special thanks to {SILVER}Ammler{BLACK}, {SILVER}Core Xii{BLACK}, {SILVER}Irwe{BLACK}, {SILVER}planetmaker{BLACK} and {SILVER}Zephyris{BLACK}.Uses parts of {SILVER}eGRVTS{BLACK}, {SILVER}ISR{BLACK} and {SILVER}OpenGFX{BLACK}."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maximální vzdálenost loviště ryb a těžby podvodních sedimentů od pobřeží."

[STR_PARAM_DESC_ECONOMIES]
base = "Každá ekonomika poskytuje různou kombinaci nákladů a průmyslu.{}{} {SILVER}Základní {BLACK}ekonomiky obsahují méně průmyslu a nákladů než ostatní FIRS ekonomiky a jsou tedy vhodné i pro začínající hráče.{}{}Detailní informace ke každé ekonomice jsou k dispozici na stránkách FIRSu."

[STR_PARAM_DESC_NO_OPENINGS]
base = "Ve výchozím nastavení je během hry stavěn nový průmysl.{}{}Pokud je aktivní nastavení {SILVER}zakázat stavbu{BLACK}, nový průmysl nebude během hry stavěn a hráči není umožněno stavět či financovat nový průmysl."

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maximální vzdálenost vodního průmyslu"

[STR_PARAM_NAME_ECONOMIES]
base = "Ekonomika"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Zabránit stavbě průmyslu během hry."

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Bez limitu"

[STR_PARAM_NAME_PRIMARY_LEVEL1_REQUIREMENT]
base = "Krabic zásob potřebných pro Zvýšenou primární produkci (výchozí 16)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_REQUIREMENT]
base = "Krabic zásob potřebných pro Gung-ho primární produkci (výchozí 80)"

[STR_PARAM_DESC_PRIMARY_LEVEL_REQUIREMENT]
base = "Produkce farem, dolů a podobného průmyslu se zvýší v případě dodání krabic se zásobami. Nejprve na {SILVER}Zvýšenou{BLACK}, a poté na {SILVER}Gung-ho{BLACK}, produkci, pokud je doručen dostatek zásob.{}{}Výchozí nastavení jsou dobrá, ale v případě potřeby je zde možné tyto hodnoty změnit.{}{}Požadavky na náklad jsou u přístavních typů průmyslu jsou znásobeny 8x."

[STR_PARAM_NAME_PRIMARY_LEVEL1_BONUS]
base = "Vylepšená základní úroveň produkce (%)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_BONUS]
base = "Gung-ho primární úroveň produkce (%)"

[STR_PARAM_DESC_PRIMARY_LEVEL_BONUS]
base = "Produkce farem, dolů a podobného průmyslu v případě dodání požadovaného množství zásob (procento {SILVER}Normální {BLACK}úrovně produkce)."

[STR_PARAM_VALUE_ECONOMIES_BASIC_TEMPERATE]
base = "Základní mírná"

[STR_PARAM_VALUE_ECONOMIES_BASIC_ARCTIC]
base = "Základní arktická"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TROPIC]
base = "Základní tropická"

[STR_PARAM_VALUE_ECONOMIES_IN_A_HOT_COUNTRY]
base = "V subtropech"

[STR_PARAM_VALUE_ECONOMIES_STEELTOWN]
base = "Ocelové město"

[STR_CARGO_NAME_ACID]
base = "Kyselina"

[STR_CARGO_NAME_ALCOHOL]
base = "Alkohol"

[STR_CARGO_NAME_BAUXITE]
base = "Bauxit"

[STR_CARGO_NAME_BEANS]
base = "Fazole"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "Stavební materiály"

[STR_CARGO_NAME_CASSAVA]
base = "Maniok"

[STR_CARGO_NAME_CEMENT]
base = "Cement"

[STR_CARGO_NAME_CHEMICALS]
base = "Chemikálie"

[STR_CARGO_NAME_CHLORINE]
base = "Chlór"

[STR_CARGO_NAME_CLAY]
base = "Jíl"

[STR_CARGO_NAME_COFFEE]
base = "Káva"

[STR_CARGO_NAME_COKE]
base = "Koks"

[STR_CARGO_NAME_COPPER]
base = "Měď"

[STR_CARGO_NAME_EDIBLE_OIL]
base = "Potravinářský olej"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "Strojírenské potřeby"

[STR_CARGO_NAME_EXPLOSIVES]
base = "Výbušniny"

[STR_CARGO_NAME_FIBRES]
base = "Rostlinná vlákna"

[STR_CARGO_NAME_FISH]
base = "Ryby"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "Zemědělské potřeby"

[STR_CARGO_NAME_FERTILISER]
base = "Hnojivo"

[STR_CARGO_NAME_FRUITS]
base = "Ovoce a Zelenina"

[STR_CARGO_NAME_KAOLIN]
base = "Kaolin"

[STR_CARGO_NAME_LIMESTONE]
base = "Vápenec"

[STR_CARGO_NAME_TIMBER]
base = "Řezivo"

[STR_CARGO_NAME_MILK]
base = "Mléko"

[STR_CARGO_NAME_MANGANESE]
base = "Mangan"

[STR_CARGO_NAME_NITRATES]
base = "Ledek"

[STR_CARGO_NAME_NUTS]
base = "Ořechy"

[STR_CARGO_NAME_PEAT]
base = "Rašelina"

[STR_CARGO_NAME_PETROL]
base = "Paliva"

[STR_CARGO_NAME_PHOSPHATE]
base = "Fosfát"

[STR_CARGO_NAME_PIG_IRON]
base = "Surové železo"

[STR_CARGO_NAME_POTASH]
base = "Potaš"

[STR_CARGO_NAME_PYRITE_ORE]
base = "Pyrit"

[STR_CARGO_NAME_QUICKLIME]
base = "Nehašené vápno"

[STR_CARGO_NAME_RECYCLABLES]
base = "Recyklovatelné materiály"

[STR_CARGO_NAME_SALT]
base = "Sůl"

[STR_CARGO_NAME_SAND]
base = "Písek"

[STR_CARGO_NAME_SCRAP_METAL]
base = "Kovový šrot"

[STR_CARGO_NAME_SLAG]
base = "Struska"

[STR_CARGO_NAME_SODA_ASH]
base = "Soda"

[STR_CARGO_NAME_STEEL]
base = "Ocel"

[STR_CARGO_NAME_AGGREGATES]
base = "Kámen"

[STR_CARGO_NAME_SUGAR_BEET]
base = "Cukrová řepa"

[STR_CARGO_NAME_SULPHUR]
base = "Síra"

[STR_CARGO_NAME_VEHICLE_BODIES]
base = "Karoserie vozidel"

[STR_CARGO_NAME_VEHICLE_PARTS]
base = "Díly vozidel"

[STR_CARGO_NAME_VEHICLES]
base = "Vozidla"

[STR_CARGO_NAME_WOOL]
base = "Vlna"

[STR_CARGO_NAME_ZINC]
base = "Zinek"

[STR_CARGO_UNIT_ACID]
base = "{VOLUME} kyseliny"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} alkoholu"

[STR_CARGO_UNIT_BAUXITE]
base = "{WEIGHT} bauxitu"

[STR_CARGO_UNIT_BEANS]
base = "{WEIGHT} fazolí"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} stavebních materiálů"

[STR_CARGO_UNIT_CASSAVA]
base = "{WEIGHT} manioku"

[STR_CARGO_UNIT_CEMENT]
base = "{WEIGHT} cementu"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} chemikálií"

[STR_CARGO_UNIT_CHLORINE]
base = "{VOLUME} chlóru"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} jílu"

[STR_CARGO_UNIT_COFFEE]
base = "{SIGNED_WORD} pyt{P 0 el le lů} kávy"

[STR_CARGO_UNIT_COKE]
base = "{WEIGHT} koksu"

[STR_CARGO_UNIT_COPPER]
base = "{WEIGHT} mědi"

[STR_CARGO_UNIT_EDIBLE_OIL]
base = "{VOLUME} potravinářského oleje"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} bed{P 0 na ny en} strojírenských potřeb"

[STR_CARGO_UNIT_EXPLOSIVES]
base = "{SIGNED_WORD} bed{P 0 na ny en} výbušnin"

[STR_CARGO_UNIT_FERTILISER]
base = "{WEIGHT} hnojiva"

[STR_CARGO_UNIT_FIBRES]
base = "{SIGNED_WORD} balík{P 0 \"\" y ů} rostlinných vláken"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} ryb"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} bed{P 0 na ny en} zemědělských potřeb"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} ovoce a zeleniny"

[STR_CARGO_UNIT_KAOLIN]
base = "{WEIGHT} kaolinu"

[STR_CARGO_UNIT_LIMESTONE]
base = "{WEIGHT} vápence"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} řeziva"

[STR_CARGO_UNIT_LYE]
base = "{VOLUME} louhu"

[STR_CARGO_UNIT_MANGANESE]
base = "{WEIGHT} manganu"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} mléka"

[STR_CARGO_UNIT_NICKEL]
base = "{WEIGHT} niklu"

[STR_CARGO_UNIT_NITRATES]
base = "{WEIGHT} ledku"

[STR_CARGO_UNIT_NUTS]
base = "{SIGNED_WORD} pyt{P 0 el le lů} ořechů"

[STR_CARGO_UNIT_PEAT]
base = "{WEIGHT} rašeliny"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} paliv"

[STR_CARGO_UNIT_PHOSPHATE]
base = "{WEIGHT} fosfátu"

[STR_CARGO_UNIT_PIG_IRON]
base = "{WEIGHT} surového železa"

[STR_CARGO_UNIT_POTASH]
base = "{WEIGHT} potaše"

[STR_CARGO_UNIT_PYRITE_ORE]
base = "{WEIGHT} pyritu"

[STR_CARGO_UNIT_QUICKLIME]
base = "{WEIGHT} nehašeného vápna"

[STR_CARGO_UNIT_RECYCLABLES]
base = "{WEIGHT} recyklovatelných materiálů"

[STR_CARGO_UNIT_SALT]
base = "{WEIGHT} soli"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} písku"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} kovového šrotu"

[STR_CARGO_UNIT_SLAG]
base = "{WEIGHT} strusky"

[STR_CARGO_UNIT_SODA_ASH]
base = "{WEIGHT} sody"

[STR_CARGO_UNIT_STEEL]
base = "{WEIGHT} oceli"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} kamenů"

[STR_CARGO_UNIT_SUGAR_BEET]
base = "{WEIGHT} cukrové řepy"

[STR_CARGO_UNIT_SULPHUR]
base = "{WEIGHT} síry"

[STR_CARGO_UNIT_VEHICLE_BODIES]
base = "{WEIGHT} karoserií vozidel"

[STR_CARGO_UNIT_VEHICLE_PARTS]
base = "{WEIGHT} dílů vozidel"

[STR_CARGO_UNIT_VEHICLES]
base = "{WEIGHT} vozidel"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} balík{P 0 \"\" y ů} vlny"

[STR_CARGO_UNIT_ZINC]
base = "{WEIGHT} zinku"

[STR_CID_ACID]
base = "{TINYFONT}KYS"

[STR_CID_ALCOHOL]
base = "{TINYFONT}AL"

[STR_CID_BAUXITE]
base = "{TINYFONT}BX"

[STR_CID_BEANS]
base = "{TINYFONT}FA"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}BM"

[STR_CID_CASSAVA]
base = "{TINYFONT}MA"

[STR_CID_CEMENT]
base = "{TINYFONT}CE"

[STR_CID_CHEMICALS]
base = "{TINYFONT}CH"

[STR_CID_CHLORINE]
base = "{TINYFONT}CL"

[STR_CID_CLAY]
base = "{TINYFONT}CL"

[STR_CID_COFFEE]
base = "{TINYFONT}KA"

[STR_CID_COKE]
base = "{TINYFONT}KO"

[STR_CID_COPPER]
base = "{TINYFONT}MD"

[STR_CID_EDIBLE_OIL]
base = "{TINYFONT}PO"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}ES"

[STR_CID_EXPLOSIVES]
base = "{TINYFONT}EX"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}FS"

[STR_CID_FERTILISER]
base = "{TINYFONT}HN"

[STR_CID_FIBRES]
base = "{TINYFONT}PF"

[STR_CID_FISH]
base = "{TINYFONT}FI"

[STR_CID_KAOLIN]
base = "{TINYFONT}KA"

[STR_CID_LIMESTONE]
base = "{TINYFONT}VP"

[STR_CID_TIMBER]
base = "{TINYFONT}LU"

[STR_CID_LYE]
base = "{TINYFONT}LO"

[STR_CID_MANGANESE]
base = "{TINYFONT}MN"

[STR_CID_MILK]
base = "{TINYFONT}MK"

[STR_CID_NICKEL]
base = "{TINYFONT}NK"

[STR_CID_NITRATES]
base = "{TINYFONT}LE"

[STR_CID_NUTS]
base = "{TINYFONT}OŘ"

[STR_CID_PEAT]
base = "{TINYFONT}RA"

[STR_CID_PETROL]
base = "{TINYFONT}PT"

[STR_CID_PIG_IRON]
base = "{TINYFONT}SŽ"

[STR_CID_PHOSPHATE]
base = "{TINYFONT}FT"

[STR_CID_POTASH]
base = "{TINYFONT}PO"

[STR_CID_PYRITE_ORE]
base = "{TINYFONT}PY"

[STR_CID_QUICKLIME]
base = "{TINYFONT}NV"

[STR_CID_RECYCLABLES]
base = "{TINYFONT}RM"

[STR_CID_SALT]
base = "{TINYFONT}SA"

[STR_CID_SAND]
base = "{TINYFONT}SA"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}SM"

[STR_CID_SLAG]
base = "{TINYFONT}ST"

[STR_CID_SODA_ASH]
base = "{TINYFONT}SO"

[STR_CID_STEEL]
base = "{TINYFONT}OL"

[STR_CID_AGGREGATES]
base = "{TINYFONT}ST"

[STR_CID_SUGAR_BEET]
base = "{TINYFONT}CŘ"

[STR_CID_SULPHUR]
base = "{TINYFONT}SI"

[STR_CID_VEHICLE_BODIES]
base = "{TINYFONT}KV"

[STR_CID_VEHICLE_PARTS]
base = "{TINYFONT}DV"

[STR_CID_VEHICLES]
base = "{TINYFONT}VO"

[STR_CID_WOOL]
base = "{TINYFONT}WL"

[STR_CID_ZINC]
base = "{TINYFONT}ZN"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}FIRS není navržen pro použití v Zemi hraček"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "musí být umístěn pod sněžnou čarou"

[STR_ERR_LOCATION_NOT_BELOW_SNOWLINE]
base = "musí být umístěn nad sněžnou čarou."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "musí být umístěn na suchu."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "nesmí být umístěn v poušti."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "nelze umístit na příkrých svazích."

[STR_ERR_LOCATION_LIMIT_1_PER_TOWN]
base = "povolen pouze jeden průmysl tohoto typu na město."

[STR_IND_ALUMINIUM_PLANT]
base = "Hliníková huť"

[STR_IND_AMMONIA_PLANT]
base = "Čpavkárna"

[STR_IND_ARABLE_FARM]
base = "Rostlinná farma"

[STR_IND_ASSEMBLY_PLANT]
base = "Montážní závod"

[STR_IND_BASIC_OXYGEN_FURNACE]
base = "Kyslíková pec"

[STR_IND_BIOREFINERY]
base = "Biorafinerie"

[STR_IND_BLAST_FURNACE]
base = "Vysoká pec"

[STR_IND_BREWERY]
base = "Pivovar"

[STR_IND_CIDER_MILL]
base = "Pálenka"

[STR_IND_BRICK_WORKS]
base = "Cihelna"

[STR_IND_BUILDERS_YARD]
base = "Stavebniny"

[STR_IND_BULK_TERMINAL]
base = "Nákladový terminál"

[STR_IND_CEMENT_PLANT]
base = "Cementárna"

[STR_IND_CHEMICAL_PLANT]
base = "Chemička"

[STR_IND_CLAY_PIT]
base = "Jílový důl"

[STR_IND_COFFEE_ESTATE]
base = "Kávová plantáž"

[STR_IND_COKE_OVEN]
base = "Koksová pec"

[STR_IND_COPPER_SMELTER]
base = "Slévárna mědi"

[STR_IND_DAIRY]
base = "Mlékárna"

[STR_IND_DAIRY_FARM]
base = "Mléčná farma"

[STR_IND_DREDGING_SITE]
base = "Těžba podvodních sedimentů"

[STR_IND_ELECTRIC_ARC_FURNACE]
base = "Oblouková pec"

[STR_IND_FISHING_GROUND]
base = "Loviště ryb"

[STR_IND_FISHING_HARBOUR]
base = "Rybí trh"

[STR_IND_FISHING_VILLAGE]
base = "Rybářská vesnice"

[STR_IND_FLOUR_MILL]
base = "Mlýn"

[STR_IND_FOOD_MARKET]
base = "Obchod"

[STR_IND_FOOD_PROCESSOR]
base = "Potravinářský závod"

[STR_IND_FURNITURE_FACTORY]
base = "Truhlářství"

[STR_IND_GENERAL_STORE]
base = "Obchod se smíšeným zbožím"

[STR_IND_GLASS_WORKS]
base = "Sklárna"

[STR_IND_HARDWARE_STORE]
base = "Železářství"

[STR_IND_HOTEL]
base = "Hotel"

[STR_IND_HERDING_COOP]
base = "Drůbežárna"

[STR_IND_IRON_WORKS]
base = "Železárna"

[STR_IND_SCRAP_YARD]
base = "Smetiště"

[STR_IND_LIME_KILN]
base = "Vápenka"

[STR_IND_LIMESTONE_MINE]
base = "Vápencový důl"

[STR_IND_LIQUIDS_TERMINAL]
base = "Skladiště kapalin"

[STR_IND_TIMBER_YARD]
base = "Řezárna"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "Obchod se stroji"

[STR_IND_MANGANESE_MINE]
base = "Manganový důl"

[STR_IND_MIXEDFARM]
base = "Smíšená farma"

[STR_IND_NITRATE_MINE]
base = "Dusičnanový důl"

[STR_IND_ORCHARD_PIGGERY]
base = "Sad a vepřín"

[STR_IND_PEATLANDS]
base = "Rašeliniště"

[STR_IND_PETROLPUMP]
base = "Benzínová stanice"

[STR_IND_PHOSPHATE_MINE]
base = "Fosfátový důl"

[STR_IND_PLASTICS_PLANT]
base = "Továrna na plasty"

[STR_IND_PORT]
base = "Přístav"

[STR_IND_POTASH_MINE]
base = "Potašový důl"

[STR_IND_PYRITE_MINE]
base = "Pyritový důl"

[STR_IND_PYRITE_SMELTER]
base = "Pyritová huť"

[STR_IND_POWER_PLANT]
base = "Elektrárna"

[STR_IND_QUARRY]
base = "Kamenolom"

[STR_IND_RANCH]
base = "Ranč"

[STR_IND_RECYCLING_DEPOT]
base = "Sklad tříděného odpadu"

[STR_IND_RECYCLING_PLANT]
base = "Třídírna odpadů"

[STR_IND_REINDEER_FARM]
base = "Sobí farma"

[STR_IND_SHEEPFARM]
base = "Ovčí farma"

[STR_IND_SLAG_GRINDING_PLANT]
base = "Drtič strusky"

[STR_IND_SMITHY_FORGE]
base = "Kovárna"

[STR_IND_SODA_ASH_MINE]
base = "Důl na sodu"

[STR_IND_STOCKYARD]
base = "Masokombinát"

[STR_IND_SUGAR_REFINERY]
base = "Cukrovar"

[STR_IND_SUPPLY_YARD]
base = "Sklad zásob"

[STR_IND_TEXTILE_MILL]
base = "Tkalcovna"

[STR_IND_TRADING_POST]
base = "Obchodní místo"

[STR_IND_TYRE_PLANT]
base = "Továrna na pneumatiky"

[STR_IND_VINEYARD]
base = "Vinice"

[STR_IND_WHARF]
base = "Přístaviště"

[STR_CARGO_SUBTYPE_DISPLAY_CARGO_SUPPLIED_FLAG]
base = "{BLACK}(doručeno)"

[STR_EXTRA_TEXT_SECONDARY_NON_COMBINATORY]
base = "{BLACK}Maximální produkce pokud je doručen{WHITE}jakýkoli {BLACK}z požadovaných nákladů."

[STR_PRIMARY_PRODUCTION_1X]
base = "{BLACK}Aktuální produkce: {YELLOW}Normální{}{}{BLACK}Pro {WHITE}Zvýšenou {BLACK}produkci je třeba doručit {SIGNED_WORD} krabic spotřebního materiálu během tří měsíců.{}Pro {WHITE}Gung-ho {BLACK}produkci je třeba doručit {SIGNED_WORD} krabic."

[STR_PRIMARY_PRODUCTION_2X]
base = "{BLACK}Aktuální produkce: {YELLOW}Zvýšená{}{}{BLACK}Pro udržení této úrovně je třeba doručit {SIGNED_WORD} krabic zásob během tří měsíců.{}Pro {WHITE}Gung-ho {BLACK}produkci je třeba doručit{SIGNED_WORD} krabic."

[STR_PRIMARY_PRODUCTION_4X]
base = "{BLACK}Aktuální produkce: {YELLOW}Gung-ho{}{}{BLACK}Pro udržení této úrovně je třeba doručit {SKIP}{SIGNED_WORD} krabic zásob během tří měsíců."

[STR_PORT_PRODUCTION_1X]
base = "{BLACK}Aktuální produkce: {YELLOW}Normální{}{}{BLACK}Pro {WHITE}Zvýšenou {BLACK}produkc je třeba doručit {SIGNED_WORD} jednotek nákladu během tří měsíců.{}Pro {WHITE}Gung-ho {BLACK}produkci je třeba doručit {SIGNED_WORD} jednotek."

[STR_PORT_PRODUCTION_2X]
base = "{BLACK}Aktuální produkce: {YELLOW}Zvýšená{}{}{BLACK}Pro udržení této úrovně je třeba doručit {SIGNED_WORD} jednotek nákladu během tří měsíců.{}Pro {WHITE}Gung-ho {BLACK}produkci je třeba doručit {SIGNED_WORD} jednotek."

[STR_PORT_PRODUCTION_4X]
base = "{BLACK}Aktuální produkce: {YELLOW}Gung-ho{}{}{BLACK}Pro udržení této úrovně je třeba doručit {SKIP}{SIGNED_WORD} jednotek nákladu během tří měsíců."

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Umístění: {YELLOW}Nelze založit na sněhu nebo v pouštích."

[STR_FUND_COFFEE_ESTATE]
base = "{}{BLACK}Umístění: {YELLOW}Nelze založit na sněhu nebo v pouštích."

[STR_FUND_DAIRY_FARM]
base = "{}{BLACK}Umístění: {YELLOW}Nelze založit na sněhu nebo v pouštích."

[STR_FUND_FOREST]
base = "{}{BLACK}Poloha: {YELLOW}Nelze založit v poušti"

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Umístění: {YELLOW}Nelze založit na sněhu."

[STR_FUND_HERDING_COOP]
base = "{}{BLACK}Umístění: {YELLOW}Lze založit pouze na sněhu."

[STR_FUND_ORCHARD_PIGGERY]
base = "{}{BLACK}Umístění: {YELLOW}Nelze založit na sněhu nebo v pouštích"

[STR_FUND_RUBBER_PLANTATION]
base = "{}{BLACK}Umístění: {YELLOW}Nelze založit na sněhu nebo v pouštích."

[STR_FUND_VINEYARD]
base = "{}{BLACK}Umístění: {YELLOW}Nelze založit na sněhu nebo v pouštích."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}K dispozici z: {YELLOW}{COMMA}"

[STR_FUND_AVAILABLE_UNTIL]
base = "{}{BLACK}Není k dispozici po: {YELLOW}{COMMA}"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING} {STRING}"

[STR_STATION_ANIMALS]
base = "Koňský trh"

[STR_STATION_AUTOMOTIVE]
base = "Automobilka"

[STR_STATION_BAR_GRILL_AND_ROOMS]
base = "Bar, gril a pokoje"

[STR_STATION_BARNS]
base = "Stodoly"

[STR_STATION_BARREL_AND_KEG]
base = "Barel a sud"

[STR_STATION_BASE]
base = "Základna"

[STR_STATION_BONEYARD]
base = "Pohřebiště"

[STR_STATION_BANK_TOP]
base = "Koksovna"

[STR_STATION_CASTINGS]
base = "Slévárny"

[STR_STATION_COLLIERY]
base = "Jáma"

[STR_STATION_COPPER_LODE]
base = "Měděná žíla"

[STR_STATION_CREOSOTING]
base = "Moření"

[STR_STATION_DAIRY_LANE]
base = "Mlékárenská"

[STR_STATION_ESTATE]
base = "Plantáž"

[STR_STATION_EXCHANGE]
base = "Překladiště"

[STR_STATION_FARM_1]
base = "Panství"

[STR_STATION_FARM_2]
base = "Luka"

[STR_STATION_FARM_3]
base = "Ranč"

[STR_STATION_FISHMARKET]
base = "Rybí trh"

[STR_STATION_FOOD_CORPORATION]
base = "Potravinářská Společnost"

[STR_STATION_FOREST]
base = "Skladiště klád"

[STR_STATION_FORGE]
base = "Kovárna"

[STR_STATION_FURNACE]
base = "Pece"

[STR_STATION_HEAVY_EQUIPMENT_YARD]
base = "Sklad Těžkého vybavení"

[STR_STATION_HEAVY_INDUSTRY_2]
base = "Dílny"

[STR_STATION_HERDING_COOP]
base = "Chata"

[STR_STATION_INDUSTRY_ESTATE_1]
base = "Průmyslová zóna"

[STR_STATION_INDUSTRY_HARBOUR_1]
base = "Přílivový dvůr"

[STR_STATION_INDUSTRY_HARBOUR_2]
base = "Břeh"

[STR_STATION_INDUSTRY_HARBOUR_3]
base = "Přístavní můstek"

[STR_STATION_IRONSTONE]
base = "Železná ruda"

[STR_STATION_JOINERS_SHOP]
base = "Spojovací materiál"

[STR_STATION_KILNS]
base = "Pece"

[STR_STATION_KIMBERLITE_DEPOSITS]
base = "Úložiště kimberlitu"

[STR_STATION_LIMESTONE_MINES]
base = "Vápencové doly"

[STR_STATION_MANGANESE_MINES]
base = "Manganové doly"

[STR_STATION_MARKET]
base = "Trh"

[STR_STATION_MILL]
base = "Mlýn"

[STR_STATION_MINE]
base = "Koželužna"

[STR_STATION_MOULDINGS]
base = "Litiny"

[STR_STATION_OIL_RIG]
base = "Ropná pole"

[STR_STATION_ORCHARDS]
base = "Sady"

[STR_STATION_PIT]
base = "Důl"

[STR_STATION_PLANTATION]
base = "Plantáž"

[STR_STATION_POWERHUNGRY]
base = "Elektrárna"

[STR_STATION_PUMPS]
base = "Benzínka"

[STR_STATION_PYRITES]
base = "Úložiště Pyritu"

[STR_STATION_REFINERY]
base = "Rafinerie"

[STR_STATION_RUBBER_COMPANY]
base = "Gumárna"

[STR_STATION_SALTPETER_WORKS]
base = "Ledkový důl"

[STR_STATION_SHARP_STREET]
base = "Ostrá ulice"

[STR_STATION_SHEEP_FOLD]
base = "Ovčín"

[STR_STATION_SHOALS]
base = "Hejna"

[STR_STATION_SILO]
base = "Silo"

[STR_STATION_SMELTER]
base = "Huť"

[STR_STATION_STACKS]
base = "Hromady"

[STR_STATION_STAMP_AND_PLATE]
base = "Razítko a talíř"

[STR_STATION_SUGAR_COMPANY]
base = "Cukrová Společnost"

[STR_STATION_TANK_FARM]
base = "Tankoviště"

[STR_STATION_TAPPERS_SHED]
base = "Nálevna"

[STR_STATION_TOWN_1]
base = "Stará radnice"

[STR_STATION_TOWN_2]
base = "Hlavní silnice"

[STR_STATION_TOWN_3]
base = "Prodejny"

[STR_STATION_TRONA_BEDS]
base = "Lehátka"

[STR_STATION_WATER]
base = "Písčina"

[STR_STATION_WEAVE_AND_DYE]
base = "Vázání  a barvení"

[STR_STATION_WELLS]
base = "Prameny"

[STR_STATION_WINERY]
base = "Vinárna"
