[GLOBAL_PRAGMA]
grflangid = "0x2d"
plural = "0"

[STR_GRF_DESC]
base = "{ORANGE}FIRS Industry Replacement Set{}{BLACK}Bragt til dig af andythenorth, FooBar, planetmaker, Terkhen og Yexo, med hjælp fra mange andre. {SILVER}Se \"readme\"-filen for mere information, inklusiv hvordan man anvender FIRS. {BLACK}Licens: GPL v2."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maksimal afstand mellem fiskeområder, boreplatforme og uddybningssteder og kysten i felter."

[STR_PARAM_DESC_ECONOMIES]
base = "Hver økonomi har sin egen kombination af godstyper og industrier.{}{}\"Basis\" økonomien indeholder færre industrier og godstyper end andre FIRS økonomier, og er velegnet for nye spillere, eller spillere der ønsker et mere simpelt gameplay."

[STR_PARAM_DESC_NO_OPENINGS]
base = "Som standard vil nye FIRS-industrier åbne i løbet af spillet.{}{}hvis 'Forhindre industrier i at åbne under spillet' er slået til, vil industrier ikke åbne i løbet af spillet, og spillere vil heller ikke kunne bygge nye industrier."

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maksimal afstand mellem kysten og marine industrier, i felter"

[STR_PARAM_NAME_ECONOMIES]
base = "Økonomi"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Forhindre industrier i at åbne under spillet"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Ingen begrænsning"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TEMPERATE]
base = "Tempereret basis"

[STR_PARAM_VALUE_ECONOMIES_BASIC_ARCTIC]
base = "Subarktisk basis"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TROPIC]
base = "Subtropisk basis"

[STR_PARAM_VALUE_ECONOMIES_IN_A_HOT_COUNTRY]
base = "Heart of Darkness"

[STR_CARGO_NAME_ALCOHOL]
base = "Alkohol"

[STR_CARGO_NAME_BAUXITE]
base = "Bauxit"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "Byggematerialer"

[STR_CARGO_NAME_CHEMICALS]
base = "Kemikalier"

[STR_CARGO_NAME_CLAY]
base = "Ler"

[STR_CARGO_NAME_COFFEE]
base = "Kaffe"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "Konstruktionsmaterialer"

[STR_CARGO_NAME_FIBRES]
base = "Plantefibre"

[STR_CARGO_NAME_FISH]
base = "Fisk"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "Landbrugsmaterialer"

[STR_CARGO_NAME_FRUITS]
base = "Frugt"

[STR_CARGO_NAME_TIMBER]
base = "Tømmer"

[STR_CARGO_NAME_MILK]
base = "Mælk"

[STR_CARGO_NAME_PETROL]
base = "Benzin"

[STR_CARGO_NAME_RECYCLABLES]
base = "Genbrugsmaterialer"

[STR_CARGO_NAME_SAND]
base = "Sand"

[STR_CARGO_NAME_SCRAP_METAL]
base = "Skrotmetal"

[STR_CARGO_NAME_AGGREGATES]
base = "Sten"

[STR_CARGO_NAME_SUGAR_BEET]
base = "Sukkerroer"

[STR_CARGO_NAME_WOOL]
base = "Uld"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} alkohol"

[STR_CARGO_UNIT_BAUXITE]
base = "{WEIGHT} bauxit"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} byggematerialer"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} kemikalier"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} ler"

[STR_CARGO_UNIT_COFFEE]
base = "{SIGNED_WORD} sæk{P 0 \"\" ke} kaffe"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} kasse{P 0 \"\" r} konstruktionsmaterialer"

[STR_CARGO_UNIT_FIBRES]
base = "{SIGNED_WORD} bal{P 0 \"\" le} plantefibre"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} fisk"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} kasse{P 0 \"\" er} landbrugsmaterialer"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} frugt"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} tømmer"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} mælk"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} benzin"

[STR_CARGO_UNIT_RECYCLABLES]
base = "{WEIGHT} genbrugsmaterialer"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} sand"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} skrotmetal"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} sten"

[STR_CARGO_UNIT_SUGAR_BEET]
base = "{WEIGHT} sukkerroer"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} bal{P 0 \"\" er} uld"

[STR_CID_ALCOHOL]
base = "{TINYFONT}AL"

[STR_CID_BAUXITE]
base = "{TINYFONT}BX"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}BM"

[STR_CID_CHEMICALS]
base = "{TINYFONT}KE"

[STR_CID_CLAY]
base = "{TINYFONT}LE"

[STR_CID_COFFEE]
base = "{TINYFONT}KA"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}KM"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}LM"

[STR_CID_FIBRES]
base = "{TINYFONT}PF"

[STR_CID_FISH]
base = "{TINYFONT}FI"

[STR_CID_TIMBER]
base = "{TINYFONT}TØ"

[STR_CID_MILK]
base = "{TINYFONT}MK"

[STR_CID_PETROL]
base = "{TINYFONT}BZ"

[STR_CID_RECYCLABLES]
base = "{TINYFONT}GM"

[STR_CID_SAND]
base = "{TINYFONT}SA"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}SM"

[STR_CID_AGGREGATES]
base = "{TINYFONT}ST"

[STR_CID_SUGAR_BEET]
base = "{TINYFONT}RO"

[STR_CID_WOOL]
base = "{TINYFONT}UL"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}FIRS er ikke designet til anvendelse i \"legetøjs\" (Toyland) landskab."

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "skal være placeret over snelinjen."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "skal være placeret på land."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "må ikke placeres i ørkenen."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "kan ikke placeres på skrå felter."

[STR_ERR_LOCATION_LIMIT_1_PER_TOWN]
base = "kun en industri af denne type tilladt pr. by."

[STR_IND_ALUMINIUM_PLANT]
base = "Aluminiumsværk"

[STR_IND_ARABLE_FARM]
base = "Jordbrugsgård"

[STR_IND_BIOREFINERY]
base = "Bioraffinaderi"

[STR_IND_BREWERY]
base = "Bryggeri"

[STR_IND_CIDER_MILL]
base = "Cider bryggeri"

[STR_IND_BRICK_WORKS]
base = "Teglværk"

[STR_IND_BUILDERS_YARD]
base = "Byggeplads"

[STR_IND_BULK_TERMINAL]
base = "Bulk terminal"

[STR_IND_CEMENT_PLANT]
base = "Cementfabrik"

[STR_IND_CLAY_PIT]
base = "Lergrav"

[STR_IND_COFFEE_ESTATE]
base = "Kaffeplantage"

[STR_IND_DAIRY]
base = "Mejeri"

[STR_IND_DREDGING_SITE]
base = "Uddybningssted"

[STR_IND_FISHING_GROUND]
base = "Fiskeriområder"

[STR_IND_FISHING_HARBOUR]
base = "Fiskerihavn"

[STR_IND_FOOD_MARKET]
base = "Fødevarebutik"

[STR_IND_FURNITURE_FACTORY]
base = "Møbelfabrik"

[STR_IND_GENERAL_STORE]
base = "Butik"

[STR_IND_GLASS_WORKS]
base = "Glasværk"

[STR_IND_HARDWARE_STORE]
base = "Isenkræmmer"

[STR_IND_HOTEL]
base = "Hotel"

[STR_IND_IRON_WORKS]
base = "Stålværk"

[STR_IND_SCRAP_YARD]
base = "Skrotplads"

[STR_IND_LIME_KILN]
base = "Kalkbrænderi"

[STR_IND_TIMBER_YARD]
base = "Tømmerplads"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "Maskinfabrik"

[STR_IND_MIXEDFARM]
base = "Bondegård"

[STR_IND_ORCHARD_PIGGERY]
base = "Frugthave og svinestald"

[STR_IND_PETROLPUMP]
base = "Tankstation"

[STR_IND_PLASTICS_PLANT]
base = "Plastikfabrik"

[STR_IND_PORT]
base = "Havn"

[STR_IND_QUARRY]
base = "Grusgrav"

[STR_IND_RANCH]
base = "Ranch"

[STR_IND_RECYCLING_DEPOT]
base = "Genbrugsstation"

[STR_IND_RECYCLING_PLANT]
base = "Genanvendingsanlæg"

[STR_IND_SHEEPFARM]
base = "Fårefarm"

[STR_IND_SMITHY_FORGE]
base = "Smedie"

[STR_IND_STOCKYARD]
base = "Slagteri"

[STR_IND_SUGAR_REFINERY]
base = "Sukkerfabrik"

[STR_IND_TEXTILE_MILL]
base = "Tekstilfabrik"

[STR_IND_TRADING_POST]
base = "Handelsstation"

[STR_PRIMARY_PRODUCTION_1X]
base = "{BLACK}Nuværrende produktion: {YELLOW}Normal{}{}{BLACK}For at fordoble produktionen, aflever {SIGNED_WORD} kasser materialer (or {SIGNED_WORD} kasser for firedobble produktionen)"

[STR_PRIMARY_PRODUCTION_2X]
base = "{BLACK}Nuværrende produktion: {YELLOW}Forbedret (dobbelt){}{}{BLACK}For at fastholde dette niveau, aflever {SIGNED_WORD} kasser materialer inden tre måneder, eller {SIGNED_WORD} kasser for at firedobble produktionen"

[STR_PRIMARY_PRODUCTION_4X]
base = "{BLACK}Nuværrende produktion: {YELLOW}Gung ho (firedobbelt){}{}{BLACK}For at fastholde dette niveau, aflever {SKIP}{SIGNED_WORD} kasser materialer inden tre måneder"

[STR_PORT_PRODUCTION_1X]
base = "{BLACK}Nuværrende produktion: {YELLOW}Normal{}{}{BLACK}For at fordoble produktionen, aflever {SIGNED_WORD} enheder af fragt inden tre måneder{}For at firedobble produktionen, aflever {SIGNED_WORD} enheder af fragt inden tre måneder"

[STR_PORT_PRODUCTION_2X]
base = "{BLACK}Nuværrende produktion: {YELLOW}Forbedret (dobbelt){}{}{BLACK}For at fastholde dette niveau, aflever {SIGNED_WORD} enheder af fragt inden tre måneder, eller {SIGNED_WORD} enheder af fragt for at opnå firedobbelt produktion"

[STR_PORT_PRODUCTION_4X]
base = "{BLACK}Nuværrende produktion: {YELLOW}Gung ho (firedobbelt){}{}{BLACK}For at fastholde dette niveau, aflever {SKIP}{SIGNED_WORD} enheder af fragt inden tre måneder"

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Placering: {YELLOW}Kan ikke bygges i sne eller i ørkener."

[STR_FUND_COFFEE_ESTATE]
base = "{}{BLACK}Placering: {YELLOW}Kan ikke bygges i sne eller i ørkener."

[STR_FUND_FOREST]
base = "{}{BLACK}Placering: {YELLOW}Kan ikke bygges i ørkener."

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Placering: {YELLOW}Kan ikke bygges i sne."

[STR_FUND_ORCHARD_PIGGERY]
base = "{}{BLACK}Placering: {YELLOW}Kan ikke bygges i sne eller i ørkener."

[STR_FUND_RUBBER_PLANTATION]
base = "{}{BLACK}Placering: {YELLOW}Kan ikke bygges i sne eller i ørkener."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}Tilgængelig fra: {YELLOW}{COMMA}"

[STR_FUND_AVAILABLE_UNTIL]
base = "{}{BLACK}Ikke tilgængelig efter: {YELLOW}{COMMA}"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING} {STRING}"

[STR_STATION_ANIMALS]
base = "Hestemarked"

[STR_STATION_FARM_1]
base = "Gård"

[STR_STATION_FISHMARKET]
base = "Fiskemarked"

[STR_STATION_INDUSTRY_ESTATE_1]
base = "Industripark"

[STR_STATION_INDUSTRY_HARBOUR_1]
base = "Trafikhavn"

[STR_STATION_MARKET]
base = "Marked"

[STR_STATION_MILL]
base = "Mølle"

[STR_STATION_MINE]
base = "Mine"

[STR_STATION_PIT]
base = "Grav"

[STR_STATION_PLANTATION]
base = "Plantage"

[STR_STATION_POWERHUNGRY]
base = "Kraftværk"

[STR_STATION_REFINERY]
base = "Raffinaderi"

[STR_STATION_TOWN_1]
base = "Bymidte"

[STR_STATION_WATER]
base = "Sandbanke"
