[GLOBAL_PRAGMA]
grflangid = "0x1f"
plural = "0"

[STR_GRF_DESC]
base = "{ORANGE}FIRS Industry Replacement Set{}{BLACK}Gemaakt door andythenorth, FooBar, planetmaker, Terkhen en Yexo met hulp van vele anderen. {SILVER}Lees de 'readme' voor meer informatie, inclusief hoe je FIRS kunt gebruiken. {BLACK}Licentie: GPL V2."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maximale afstand tot de kust in tegels voor visgebieden en baggermolens."

[STR_PARAM_DESC_ECONOMIES]
base = "Elke economie heeft een andere combinatie van goederen en industrieën.{}{}Voor spelers die een eenvoudig spelverloop willen zijn er {SILVER}basis{BLACK} economieën die minder industrieën en goederen bevatten.{}{}De FIRS website (Engelstalig) geeft gedetailleerde informatie over elke economie."

[STR_PARAM_DESC_NO_OPENINGS]
base = "Normaal worden er nieuwe industrieën gebouwd tijdens het spel.{}{}Als {SILVER}voorkom bouwen van nieuwe industrieën{BLACK} aan staat, worden geen nieuwe industrieën gebouwd tijdens het spel. Spelers kunnen nieuwe industrieën ook niet kopen of proberen."

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maximale afstand tot de kust in tegels voor zee-industrieën"

[STR_PARAM_NAME_ECONOMIES]
base = "Economie"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Voorkom bouwen van nieuwe industrieën tijdens het spel"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Geen limiet"

[STR_PARAM_NAME_PRIMARY_LEVEL1_REQUIREMENT]
base = "Aantal benodigde kratten voor verhoogde productie (standaard 16)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_REQUIREMENT]
base = "Aantal benodigde kratten voor gepassioneerde productie (standaard 80)"

[STR_PARAM_DESC_PRIMARY_LEVEL_REQUIREMENT]
base = "Boerderijen, mijnen en soortgelijke industrieën verhogen naar {SILVER}verhoogd{BLACK} productieniveau als er kratten goederen worden afgeleverd. Bij voldoende leveringen wordt het prudctieniveau gewijzigd naar {SILVER}gepassioneerd{BLACK}.{}{}De standaard waardes zijn goed werkbaar, maar indien nodig kunnen ze hier veranderd worden.{}{}Goedereneisen van havens-achtige industrieën zijn 8 keer zo hoog als de getallen die hier opgegeven worden."

[STR_PARAM_NAME_PRIMARY_LEVEL1_BONUS]
base = "Productieniveau van verhoogde productie (%)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_BONUS]
base = "Productieniveau van gepassioneerde productie (%)"

[STR_PARAM_DESC_PRIMARY_LEVEL_BONUS]
base = "Productie van boerderijen, mijnen en soortgelijke industrieën bij het vervullen van de bevoorradingseisen (als percentage van {SILVER}normale{BLACK} productie)."

[STR_PARAM_VALUE_ECONOMIES_BASIC_TEMPERATE]
base = "Basiseconomie voor het gematigde klimaat"

[STR_PARAM_VALUE_ECONOMIES_BASIC_ARCTIC]
base = "Basiseconomie voor het subarctisch klimaat"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TROPIC]
base = "Basiseconomie voor het subtropisch klimaat"

[STR_PARAM_VALUE_ECONOMIES_IN_A_HOT_COUNTRY]
base = "In een heet land"

[STR_PARAM_VALUE_ECONOMIES_STEELTOWN]
base = "Staalstad"

[STR_CARGO_NAME_ACID]
base = "Zuren"

[STR_CARGO_NAME_ALCOHOL]
base = "Alcohol"

[STR_CARGO_NAME_BEANS]
base = "Bonen"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "Bouwmaterialen"

[STR_CARGO_NAME_CASSAVA]
base = "Cassave"

[STR_CARGO_NAME_CEMENT]
base = "Cement"

[STR_CARGO_NAME_CHEMICALS]
base = "Chemicaliën"

[STR_CARGO_NAME_CHLORINE]
base = "Chloor"

[STR_CARGO_NAME_CLAY]
base = "Klei"

[STR_CARGO_NAME_COFFEE]
base = "Koffie"

[STR_CARGO_NAME_COKE]
base = "Cokes"

[STR_CARGO_NAME_COPPER]
base = "Koper"

[STR_CARGO_NAME_EDIBLE_OIL]
base = "Spijsolie"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "Constructiematerialen"

[STR_CARGO_NAME_EXPLOSIVES]
base = "Explosieven"

[STR_CARGO_NAME_FISH]
base = "Vis"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "Landbouwmaterialen"

[STR_CARGO_NAME_FERTILISER]
base = "Kunstmest"

[STR_CARGO_NAME_FRUITS]
base = "Groente en fruit"

[STR_CARGO_NAME_KAOLIN]
base = "Kaolien"

[STR_CARGO_NAME_LIMESTONE]
base = "Kalksteen"

[STR_CARGO_NAME_TIMBER]
base = "Timmerhout"

[STR_CARGO_NAME_MILK]
base = "Melk"

[STR_CARGO_NAME_MANGANESE]
base = "Mangaan"

[STR_CARGO_NAME_NITRATES]
base = "Nitraat"

[STR_CARGO_NAME_NUTS]
base = "Noten"

[STR_CARGO_NAME_PEAT]
base = "Turf"

[STR_CARGO_NAME_PETROL]
base = "Benzine"

[STR_CARGO_NAME_PHOSPHATE]
base = "Fosfaat"

[STR_CARGO_NAME_PIG_IRON]
base = "Ruwijzer"

[STR_CARGO_NAME_POTASH]
base = "Potas"

[STR_CARGO_NAME_PYRITE_ORE]
base = "Pyriet"

[STR_CARGO_NAME_QUICKLIME]
base = "Calciumoxide"

[STR_CARGO_NAME_SALT]
base = "Zout"

[STR_CARGO_NAME_SAND]
base = "Zand"

[STR_CARGO_NAME_SCRAP_METAL]
base = "Schroot"

[STR_CARGO_NAME_SLAG]
base = "Slak"

[STR_CARGO_NAME_SODA_ASH]
base = "Natriumcarbonaat"

[STR_CARGO_NAME_STEEL]
base = "Staal"

[STR_CARGO_NAME_AGGREGATES]
base = "Grind"

[STR_CARGO_NAME_SULPHUR]
base = "Zwavel"

[STR_CARGO_NAME_VEHICLE_BODIES]
base = "Carrosserieën"

[STR_CARGO_NAME_VEHICLE_PARTS]
base = "Voertuigonderdelen"

[STR_CARGO_NAME_VEHICLES]
base = "Voertuigen"

[STR_CARGO_NAME_WOOL]
base = "Wol"

[STR_CARGO_NAME_ZINC]
base = "Zink"

[STR_CARGO_UNIT_ACID]
base = "{VOLUME} zuren"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} alcohol"

[STR_CARGO_UNIT_BEANS]
base = "{WEIGHT} bonen"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} bouwmaterialen"

[STR_CARGO_UNIT_CASSAVA]
base = "{WEIGHT} cassave"

[STR_CARGO_UNIT_CEMENT]
base = "{WEIGHT} cement"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} chemicaliën"

[STR_CARGO_UNIT_CHLORINE]
base = "{VOLUME} chloor"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} klei"

[STR_CARGO_UNIT_COFFEE]
base = "{SIGNED_WORD} zak{P 0 \"\" ken} koffie"

[STR_CARGO_UNIT_COKE]
base = "{WEIGHT} cokes"

[STR_CARGO_UNIT_COPPER]
base = "{WEIGHT} koper"

[STR_CARGO_UNIT_EDIBLE_OIL]
base = "{VOLUME} spijsolie"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} krat{P 0 \"\" ten} constructiematerialen"

[STR_CARGO_UNIT_EXPLOSIVES]
base = "{SIGNED_WORD} krat{P 0 \"\" ten} explosieven"

[STR_CARGO_UNIT_FERTILISER]
base = "{WEIGHT} kunstmest"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} vis"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} krat{P 0 \"\" ten} landbouwmaterialen"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} groente en fruit"

[STR_CARGO_UNIT_KAOLIN]
base = "{WEIGHT} kaolien"

[STR_CARGO_UNIT_LIMESTONE]
base = "{WEIGHT} kalksteen"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} timmerhout"

[STR_CARGO_UNIT_LYE]
base = "{VOLUME} natronloog"

[STR_CARGO_UNIT_MANGANESE]
base = "{WEIGHT} mangaan"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} melk"

[STR_CARGO_UNIT_NICKEL]
base = "{WEIGHT} nikkel"

[STR_CARGO_UNIT_NITRATES]
base = "{WEIGHT} nitraat"

[STR_CARGO_UNIT_NUTS]
base = "{SIGNED_WORD} zak{P 0 \"\" ken} noten"

[STR_CARGO_UNIT_PEAT]
base = "{WEIGHT} turf"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} benzine"

[STR_CARGO_UNIT_PHOSPHATE]
base = "{WEIGHT} fosfaat"

[STR_CARGO_UNIT_PIG_IRON]
base = "{WEIGHT} ruwijzer"

[STR_CARGO_UNIT_POTASH]
base = "{WEIGHT} potas"

[STR_CARGO_UNIT_PYRITE_ORE]
base = "{WEIGHT} pyriet"

[STR_CARGO_UNIT_QUICKLIME]
base = "{WEIGHT} calciumoxide"

[STR_CARGO_UNIT_SALT]
base = "{WEIGHT} zout"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} zand"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} schroot"

[STR_CARGO_UNIT_SLAG]
base = "{WEIGHT} slak"

[STR_CARGO_UNIT_SODA_ASH]
base = "{WEIGHT} natriumcarbonaat"

[STR_CARGO_UNIT_STEEL]
base = "{WEIGHT} staal"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} grind"

[STR_CARGO_UNIT_SULPHUR]
base = "{WEIGHT} zwavel"

[STR_CARGO_UNIT_VEHICLE_BODIES]
base = "{WEIGHT} carrosserieën"

[STR_CARGO_UNIT_VEHICLE_PARTS]
base = "{WEIGHT} voertuigonderdelen"

[STR_CARGO_UNIT_VEHICLES]
base = "{WEIGHT} voertuig{P 0 \"\" en}"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} ba{P 0 al len} wol"

[STR_CARGO_UNIT_ZINC]
base = "{WEIGHT} zink"

[STR_CID_ACID]
base = "{TINYFONT}ZR"

[STR_CID_ALCOHOL]
base = "{TINYFONT}AL"

[STR_CID_BEANS]
base = "{TINYFONT}BN"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}BM"

[STR_CID_CASSAVA]
base = "{TINYFONT}CA"

[STR_CID_CEMENT]
base = "{TINYFONT}CE"

[STR_CID_CHEMICALS]
base = "{TINYFONT}CM"

[STR_CID_CHLORINE]
base = "{TINYFONT}CL"

[STR_CID_CLAY]
base = "{TINYFONT}KL"

[STR_CID_COFFEE]
base = "{TINYFONT}KF"

[STR_CID_COKE]
base = "{TINYFONT}CK"

[STR_CID_COPPER]
base = "{TINYFONT}KR"

[STR_CID_EDIBLE_OIL]
base = "{TINYFONT}EO"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}CH"

[STR_CID_EXPLOSIVES]
base = "{TINYFONT}EX"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}LH"

[STR_CID_FERTILISER]
base = "{TINYFONT}KM"

[STR_CID_FISH]
base = "{TINYFONT}VS"

[STR_CID_KAOLIN]
base = "{TINYFONT}KA"

[STR_CID_LIMESTONE]
base = "{TINYFONT}KS"

[STR_CID_TIMBER]
base = "{TINYFONT}HT"

[STR_CID_LYE]
base = "{TINYFONT}NL"

[STR_CID_MANGANESE]
base = "{TINYFONT}MN"

[STR_CID_MILK]
base = "{TINYFONT}ML"

[STR_CID_NICKEL]
base = "{TINYFONT}NK"

[STR_CID_NITRATES]
base = "{TINYFONT}NI"

[STR_CID_NUTS]
base = "{TINYFONT}NT"

[STR_CID_PEAT]
base = "{TINYFONT}TU"

[STR_CID_PETROL]
base = "{TINYFONT}BZ"

[STR_CID_PIG_IRON]
base = "{TINYFONT}RY"

[STR_CID_PHOSPHATE]
base = "{TINYFONT}FF"

[STR_CID_POTASH]
base = "{TINYFONT}PA"

[STR_CID_PYRITE_ORE]
base = "{TINYFONT}PY"

[STR_CID_QUICKLIME]
base = "{TINYFONT}CO"

[STR_CID_SALT]
base = "{TINYFONT}ZT"

[STR_CID_SAND]
base = "{TINYFONT}ZD"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}ST"

[STR_CID_SLAG]
base = "{TINYFONT}SK"

[STR_CID_SODA_ASH]
base = "{TINYFONT}NC"

[STR_CID_STEEL]
base = "{TINYFONT}SL"

[STR_CID_AGGREGATES]
base = "{TINYFONT}GD"

[STR_CID_SULPHUR]
base = "{TINYFONT}ZW"

[STR_CID_VEHICLE_BODIES]
base = "{TINYFONT}CA"

[STR_CID_VEHICLE_PARTS]
base = "{TINYFONT}VO"

[STR_CID_VEHICLES]
base = "{TINYFONT}VN"

[STR_CID_WOOL]
base = "{TINYFONT}WL"

[STR_CID_ZINC]
base = "{TINYFONT}ZN"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}FIRS is niet ontworpen om in het speelgoedlandschap gebruikt te worden."

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "moet onder de sneeuwgrens geplaatst worden."

[STR_ERR_LOCATION_NOT_BELOW_SNOWLINE]
base = "moet boven de sneeuwgrens geplaatst worden."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "moet op droog land geplaatst worden."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "moet niet in de woestijn geplaatst worden."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "kan niet op een steile helling geplaatst worden."

[STR_ERR_LOCATION_LIMIT_1_PER_TOWN]
base = "slechts één industrie van dit type toegestaan per plaats."

[STR_IND_ALUMINIUM_PLANT]
base = "Aluminiumfabriek"

[STR_IND_AMMONIA_PLANT]
base = "Ammoniakfabriek"

[STR_IND_ARABLE_FARM]
base = "Landbouwbedrijf"

[STR_IND_ASSEMBLY_PLANT]
base = "Autofabriek"

[STR_IND_BASIC_OXYGEN_FURNACE]
base = "Oxystaalfabriek"

[STR_IND_BIOREFINERY]
base = "Bioraffinaderij"

[STR_IND_BLAST_FURNACE]
base = "Hoogoven"

[STR_IND_BREWERY]
base = "Brouwerij"

[STR_IND_CIDER_MILL]
base = "Distilleerderij"

[STR_IND_BRICK_WORKS]
base = "Steenfabriek"

[STR_IND_BUILDERS_YARD]
base = "Aannemeropslagplaats"

[STR_IND_BULK_TERMINAL]
base = "Bulkoverslagterminal"

[STR_IND_CEMENT_PLANT]
base = "Cementfabriek"

[STR_IND_CHEMICAL_PLANT]
base = "Chemische fabriek"

[STR_IND_CLAY_PIT]
base = "Kleiwinning"

[STR_IND_COFFEE_ESTATE]
base = "Koffieplantage"

[STR_IND_COKE_OVEN]
base = "Cokesoven"

[STR_IND_COPPER_SMELTER]
base = "Koperraffinaderij"

[STR_IND_DAIRY]
base = "Zuivelfabriek"

[STR_IND_DAIRY_FARM]
base = "Veehouderij"

[STR_IND_DREDGING_SITE]
base = "Baggermolen"

[STR_IND_ELECTRIC_ARC_FURNACE]
base = "Vlamboogoven"

[STR_IND_FISHING_GROUND]
base = "Visgebied"

[STR_IND_FISHING_HARBOUR]
base = "Vissershaven"

[STR_IND_FISHING_VILLAGE]
base = "Vissersdorp"

[STR_IND_FLOUR_MILL]
base = "Graanmolen"

[STR_IND_FOOD_MARKET]
base = "Kruidenier"

[STR_IND_FOOD_PROCESSOR]
base = "Voedselfabriek"

[STR_IND_FURNITURE_FACTORY]
base = "Meubelfabriek"

[STR_IND_GENERAL_STORE]
base = "Winkel"

[STR_IND_GLASS_WORKS]
base = "Glasfabriek"

[STR_IND_HARDWARE_STORE]
base = "IJzerhandel"

[STR_IND_HOTEL]
base = "Hotel"

[STR_IND_HERDING_COOP]
base = "Schapenhouderij"

[STR_IND_SCRAP_YARD]
base = "Schroothoop"

[STR_IND_LIME_KILN]
base = "Kalkoven"

[STR_IND_LIMESTONE_MINE]
base = "Mergelgroeve"

[STR_IND_LIQUIDS_TERMINAL]
base = "Vloeistoffenterminal"

[STR_IND_TIMBER_YARD]
base = "Houtwerkplaats"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "Machinewerkplaats"

[STR_IND_MANGANESE_MINE]
base = "Mangaanmijn"

[STR_IND_MIXEDFARM]
base = "Gemengd boerenbedrijf"

[STR_IND_NITRATE_MINE]
base = "Nitraatmijn"

[STR_IND_ORCHARD_PIGGERY]
base = "Boomgaard en varkensstallen"

[STR_IND_PEATLANDS]
base = "Veengronden"

[STR_IND_PETROLPUMP]
base = "Tankstation"

[STR_IND_PHOSPHATE_MINE]
base = "Fosfaatmijn"

[STR_IND_PLASTICS_PLANT]
base = "Kunststoffabriek"

[STR_IND_PORT]
base = "Haven"

[STR_IND_POTASH_MINE]
base = "Potasmijn"

[STR_IND_PYRITE_MINE]
base = "Pyrietmijn"

[STR_IND_PYRITE_SMELTER]
base = "Pyrietmenger"

[STR_IND_POWER_PLANT]
base = "Energiecentrale"

[STR_IND_QUARRY]
base = "Zandwinning"

[STR_IND_RANCH]
base = "Ranch"

[STR_IND_SHEEPFARM]
base = "Schapenhouderij"

[STR_IND_SLAG_GRINDING_PLANT]
base = "Slakmaalfabriek"

[STR_IND_SMITHY_FORGE]
base = "Smederij"

[STR_IND_SODA_ASH_MINE]
base = "Zoutmijn"

[STR_IND_STOCKYARD]
base = "Slachterij"

[STR_IND_SUGAR_REFINERY]
base = "Suikerfabriek"

[STR_IND_SUPPLY_YARD]
base = "Zware machinehandel"

[STR_IND_TEXTILE_MILL]
base = "Textielfabriek"

[STR_IND_TRADING_POST]
base = "Handelspost"

[STR_IND_TYRE_PLANT]
base = "Bandenfabriek"

[STR_IND_VINEYARD]
base = "Wijngaard"

[STR_IND_WHARF]
base = "Scheepswerf"

[STR_CARGO_SUBTYPE_DISPLAY_CARGO_SUPPLIED_FLAG]
base = "{BLACK}(geleverd)"

[STR_EXTRA_TEXT_SECONDARY_NON_COMBINATORY]
base = "{BLACK} Produceert op maximaal niveau als {WHITE}een van de {BLACK} benodigde goederen wordt geleverd."

[STR_PRIMARY_PRODUCTION_1X]
base = "{BLACK}Huidige productie: {YELLOW}Normaal{}{}{BLACK}Lever binnen drie maanden {SIGNED_WORD} eenheden vracht om {WHITE}verhoogd{BLACK} productieniveau te verkrijgen{}Lever {SIGNED_WORD} eenheden vracht voor {WHITE}gepassioneerde{BLACK} productie"

[STR_PRIMARY_PRODUCTION_2X]
base = "{BLACK}Huidige productie: {YELLOW}Verhoogd{}{}{BLACK}Lever binnen drie maanden {SIGNED_WORD} kratten constructie-, landbouw- of productiematerialen af om dit productieniveau te handhaven{}Voor {WHITE}gepassioneerde{BLACK} productie, lever {SIGNED_WORD} eenheden"

[STR_PRIMARY_PRODUCTION_4X]
base = "{BLACK}Huidige productie: {YELLOW}Gepassioneerd{}{}{BLACK}Lever binnen drie maanden {SKIP}{SIGNED_WORD} kratten constructie-, landbouw- of productiematerialen af om dit productieniveau te handhaven."

[STR_PORT_PRODUCTION_1X]
base = "{BLACK}Huidige productie: {YELLOW}Normaal{}{}{BLACK}Lever binnen drie maanden {SIGNED_WORD} eenheden vracht om {WHITE}verhoogd{BLACK} productieniveau te verkrijgen{}Lever {SIGNED_WORD} eenheden vracht voor {WHITE}gepassioneerde{BLACK} productie"

[STR_PORT_PRODUCTION_2X]
base = "{BLACK}Huidige productie: {YELLOW}Verhoogd{}{}{BLACK}Lever binnen drie maanden {SIGNED_WORD} eenheden vracht om dit productieniveau te handhaven{}Voor {WHITE}gepassioneerde{BLACK} productie, lever {SIGNED_WORD} eenheden"

[STR_PORT_PRODUCTION_4X]
base = "{BLACK}Huidige productie: {YELLOW}Gepassioneerd{}{}{BLACK}Lever binnen drie maanden {SKIP}{SIGNED_WORD} eenheden vracht om dit productieniveau te handhaven."

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Plaats: {YELLOW}Kan niet boven de sneeuwgrens of in woestijnen gebouwd worden."

[STR_FUND_COFFEE_ESTATE]
base = "{}{BLACK}Plaats: {YELLOW}Kan niet boven de sneeuwgrens of in woestijnen gebouwd worden."

[STR_FUND_DAIRY_FARM]
base = "{}{BLACK}Plaats: {YELLOW}Kan niet boven de sneeuwgrens of in woestijnen gebouwd worden."

[STR_FUND_FOREST]
base = "{}{BLACK}Plaats: {YELLOW}Kan niet in woestijnen gebouwd worden."

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Plaats: {YELLOW}Kan niet boven de sneeuwgrens gebouwd worden."

[STR_FUND_HERDING_COOP]
base = "{}{BLACK}Plaats: {YELLOW}Kan alleen op sneeuw geplaatst worden."

[STR_FUND_ORCHARD_PIGGERY]
base = "{}{BLACK}Plaats: {YELLOW}Kan niet boven de sneeuwgrens of in woestijnen gebouwd worden."

[STR_FUND_RUBBER_PLANTATION]
base = "{}{BLACK}Plaats: {YELLOW}Kan niet boven de sneeuwgrens of in woestijnen gebouwd worden."

[STR_FUND_VINEYARD]
base = "{}{BLACK}Plaats: {YELLOW}Kan niet op sneeuw of in woestijnen gebouwd worden."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}Beschikbaar vanaf: {YELLOW}{COMMA}"

[STR_FUND_AVAILABLE_UNTIL]
base = "{}{BLACK}Niet meer beschikbaar na: {YELLOW}{COMMA}"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING} {STRING}"

[STR_STATION_ANIMALS]
base = "Veehandel"

[STR_STATION_AUTOMOTIVE]
base = "Autodealer"

[STR_STATION_BAR_GRILL_AND_ROOMS]
base = "Hotel"

[STR_STATION_BARNS]
base = "Schuren"

[STR_STATION_BARREL_AND_KEG]
base = "Brouwerij"

[STR_STATION_BASE]
base = "Werf"

[STR_STATION_BONEYARD]
base = "Schroothoop"

[STR_STATION_BANK_TOP]
base = "Heuvelrug"

[STR_STATION_COLLIERY]
base = "Kolenmijn"

[STR_STATION_COPPER_LODE]
base = "Kopermijn"

[STR_STATION_CREOSOTING]
base = "Paal & Perk"

[STR_STATION_DAIRY_LANE]
base = "Melkweg"

[STR_STATION_ESTATE]
base = "Landgoed"

[STR_STATION_FARM_1]
base = "Landhuis"

[STR_STATION_FARM_2]
base = "Weiden"

[STR_STATION_FARM_3]
base = "Ranch"

[STR_STATION_FISHMARKET]
base = "Vismarkt"

[STR_STATION_FOOD_CORPORATION]
base = "Voedselfabriek"

[STR_STATION_FOREST]
base = "Bosweg"

[STR_STATION_FURNACE]
base = "Hoogovens"

[STR_STATION_HEAVY_INDUSTRY_2]
base = "Werken"

[STR_STATION_HERDING_COOP]
base = "Herdershut"

[STR_STATION_INDUSTRY_ESTATE_1]
base = "Industriegebied"

[STR_STATION_INDUSTRY_HARBOUR_1]
base = "Haven"

[STR_STATION_INDUSTRY_HARBOUR_2]
base = "Kade"

[STR_STATION_INDUSTRY_HARBOUR_3]
base = "Rede"

[STR_STATION_IRONSTONE]
base = "IJzermijn"

[STR_STATION_KILNS]
base = "Kalkovens"

[STR_STATION_KIMBERLITE_DEPOSITS]
base = "Kimberlietpijp"

[STR_STATION_LIMESTONE_MINES]
base = "Mergelgrotten"

[STR_STATION_MANGANESE_MINES]
base = "Mangaanmijn"

[STR_STATION_MILL]
base = "Molenweg"

[STR_STATION_MOULDINGS]
base = "Kunststoffabriek"

[STR_STATION_OIL_RIG]
base = "Booreiland"

[STR_STATION_ORCHARDS]
base = "Boomgaard"

[STR_STATION_PIT]
base = "Groeve"

[STR_STATION_PLANTATION]
base = "Plantage"

[STR_STATION_POWERHUNGRY]
base = "Energiecentrale"

[STR_STATION_PUMPS]
base = "Pompen"

[STR_STATION_PYRITES]
base = "Klatergoud"

[STR_STATION_REFINERY]
base = "Raffinaderij"

[STR_STATION_RUBBER_COMPANY]
base = "Rubberfabriek"

[STR_STATION_SALTPETER_WORKS]
base = "Salpetergroeve"

[STR_STATION_SHARP_STREET]
base = "Scherpe Bocht"

[STR_STATION_SHEEP_FOLD]
base = "Schapenstal"

[STR_STATION_SHOALS]
base = "Visgronden"

[STR_STATION_SILO]
base = "Silo"

[STR_STATION_SMELTER]
base = "Smeltoven"

[STR_STATION_SUGAR_COMPANY]
base = "Bietenbrug"

[STR_STATION_TANK_FARM]
base = "Olieterminal"

[STR_STATION_TAPPERS_SHED]
base = "Tappershutje"

[STR_STATION_TOWN_1]
base = "Centrum"

[STR_STATION_TOWN_3]
base = "Winkelcentrum"

[STR_STATION_TRONA_BEDS]
base = "Zoutpannen"

[STR_STATION_WATER]
base = "Zandbank"

[STR_STATION_WELLS]
base = "Bronnen"

[STR_STATION_WINERY]
base = "Château"
