[GLOBAL_PRAGMA]
grflangid = "0x3d"
plural = "0"

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maximum distance of fishing grounds, oil rigs and dredging sites from the coast in tiles."

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maximum coastal distance of marine industries in tiles"

[STR_PARAM_NAME_PRIMARY_LEVEL2_REQUIREMENT]
base = "Supply crates required for Gung-ho primary production (default 80)"

[STR_PARAM_DESC_PRIMARY_LEVEL_REQUIREMENT]
base = "Farms, mines and similar industries will increase production when supply crates are delivered, first to {SILVER}Enhanced{BLACK}, and then to {SILVER}Gung-ho{BLACK}, if enough crates are delivered.{}{}The default values are good, but if you need to, you can change them here.{}{}Cargo requirements for port-type industries will be 8x the values set here."

[STR_PARAM_DESC_PRIMARY_LEVEL_BONUS]
base = "Production at farms, mines and similar industries when supply requirements are met (as percentage of {SILVER}Normal {BLACK}production level)."

[STR_CARGO_NAME_ACID]
base = "Acid"

[STR_CARGO_NAME_BEANS]
base = "Beans"

[STR_CARGO_NAME_CLAY]
base = "Clay"

[STR_CARGO_NAME_COKE]
base = "Coke"

[STR_CARGO_NAME_COPPER]
base = "Copper"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "Farm Supplies"

[STR_CARGO_NAME_KAOLIN]
base = "Kaolin"

[STR_CARGO_NAME_LIMESTONE]
base = "Limestone"

[STR_CARGO_NAME_NITRATES]
base = "Nitrates"

[STR_CARGO_NAME_POTASH]
base = "Potash"

[STR_CARGO_NAME_PYRITE_ORE]
base = "Pyrite Ore"

[STR_CARGO_UNIT_ACID]
base = "{VOLUME} of acid"

[STR_CARGO_UNIT_BEANS]
base = "{WEIGHT} of beans"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} of building materials"

[STR_CARGO_UNIT_CASSAVA]
base = "{WEIGHT} of cassava"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} of clay"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} of fruit"

[STR_CARGO_UNIT_KAOLIN]
base = "{WEIGHT} of kaolin"

[STR_CARGO_UNIT_POTASH]
base = "{WEIGHT} of potash"

[STR_CARGO_UNIT_SLAG]
base = "{WEIGHT} of slag"

[STR_CID_CASSAVA]
base = "{TINYFONT}CA"

[STR_CID_COFFEE]
base = "{TINYFONT}CF"

[STR_CID_COKE]
base = "{TINYFONT}CK"

[STR_CID_LIMESTONE]
base = "{TINYFONT}LS"

[STR_CID_MANGANESE]
base = "{TINYFONT}MN"

[STR_CID_NITRATES]
base = "{TINYFONT}NI"

[STR_CID_PETROL]
base = "{TINYFONT}PT"

[STR_CID_SALT]
base = "{TINYFONT}NA"

[STR_CID_STEEL]
base = "{TINYFONT}SL"

[STR_CID_WOOL]
base = "{TINYFONT}WL"

[STR_IND_ALUMINIUM_PLANT]
base = "Aluminium Plant"

[STR_IND_CEMENT_PLANT]
base = "Cement Plant"

[STR_IND_DREDGING_SITE]
base = "Dredging Site"

[STR_IND_FISHING_VILLAGE]
base = "Fishing Village"

[STR_IND_FLOUR_MILL]
base = "Flour Mill"

[STR_IND_GLASS_WORKS]
base = "Glass Works"

[STR_IND_SCRAP_YARD]
base = "Wrecking Yard"

[STR_IND_NITRATE_MINE]
base = "Nitrate Mine"

[STR_IND_PETROLPUMP]
base = "Service Station"

[STR_IND_PLASTICS_PLANT]
base = "Plastics Plant"

[STR_IND_PYRITE_SMELTER]
base = "Pyrite Smelter"

[STR_IND_SHEEPFARM]
base = "Sheep Farm"

[STR_FUND_COFFEE_ESTATE]
base = "{}{BLACK}Location: {YELLOW}Cannot be funded on snow or in deserts."

[STR_STATION_ANIMALS]
base = "Horse Market"

[STR_STATION_COPPER_LODE]
base = "Copper Lode"

[STR_STATION_DAIRY_LANE]
base = "Dairy Lane"

[STR_STATION_FOREST]
base = "Log Landing"

[STR_STATION_INDUSTRY_HARBOUR_3]
base = "Landing Stage"

[STR_STATION_KIMBERLITE_DEPOSITS]
base = "Kimberlite Deposits"

[STR_STATION_REFINERY]
base = "Refinery"

[STR_STATION_SHARP_STREET]
base = "Sharp Street"

[STR_STATION_SILO]
base = "Silo"
