[GLOBAL_PRAGMA]
grflangid = "0x05"
plural = "0"
case = "n"

[STR_GRF_DESC]
base = "{ORANGE}FIRS Industry Replacement Set{}{BLACK}De {SILVER}andythenorth{BLACK} kaj {SILVER}FooBar{BLACK}.{}{BLACK}'1,000 revizoj kaj nombranta...'{BLACK}{}{}Retpaĝo: {SILVER}www.tt-foundry.com/sets/FIRS{BLACK}.Licenco: {SILVER}GPL v2{BLACK}.Specialiaj dankoj al {SILVER}Ammler{BLACK}, {SILVER}Core Xii{BLACK}, {SILVER}Irwe{BLACK}, {SILVER}planetmaker{BLACK} kaj {SILVER}Zephyris{BLACK}.Uzas partojn de {SILVER}eGRVTS{BLACK}, {SILVER}ISR{BLACK} kaj {SILVER}OpenGFX{BLACK}."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maksimuma distanco de fiŝkaptejoj, oleplatformoj, kaj skrapejoj de la marbordo en kaheloj."

[STR_PARAM_DESC_ECONOMIES]
base = "Kiam elfinis, FIRS havos diversajn ekonomiojn. Ŝarĝoj kaj industrioj varias en ĉiu ekonomio. Ŝarĝaj pagaj procentoj ankaŭ estas diferenca en ĉiu ekonomio.{}{}{SILVER}Hodiaŭa nur unu ekonomio estas disponebla :)"

[STR_PARAM_DESC_NO_OPENINGS]
base = "Ne novajn industriojn estos konstruata dum la ludo.{}Ludistoj ne povos fundi aŭ prospektori.{}Industrioj estos konstruata je la eko de la ludo per la mapa kreinto(dependi de la mapa agordoj estas uzata)."

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maksimuma marborda distanco de mara industrioj en kaheloj"

[STR_PARAM_NAME_ECONOMIES]
base = "Ekonomio"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Ne permesi industriajn konstruo dum la ludo"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Ne limigo"

[STR_CARGO_NAME_ALCOHOL]
base = "Alkoholo"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "Konstruaj Materialoj"

[STR_CARGO_NAME_CHEMICALS]
base = "Ĥemiaĵoj"

[STR_CARGO_NAME_CLAY]
base = "Argilo"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "Inĝenieraprovizoj"

[STR_CARGO_NAME_FISH]
base = "Fiŝo"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "Terkulturaprovizoj"

[STR_CARGO_NAME_FRUITS]
base = "Fruktoj"

[STR_CARGO_NAME_TIMBER]
base = "Prilaborita Ligno"

[STR_CARGO_NAME_MILK]
base = "Lakto"

[STR_CARGO_NAME_PETROL]
base = "Petrolo"

[STR_CARGO_NAME_SAND]
base = "Sablo"

[STR_CARGO_NAME_SCRAP_METAL]
base = "Peceta Metalo"

[STR_CARGO_NAME_AGGREGATES]
base = "Ŝtono"

[STR_CARGO_NAME_WOOL]
base = "Lano"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} da alkoholo"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} da konstruaj materialoj"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} da ĥemiaĵoj"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} da argilo"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} kesto{P 0 \"\" j} da inĝenieraprovizoj"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} da fiŝo"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} kesto{P 0 \"\" j} da terkultulaprovizoj"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} da fruktoj"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} da prilaborita ligno"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} da lakto"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} da petrolo"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} da sablo"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} da peceta metalo"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} da ŝtono"

[STR_CARGO_UNIT_WOOL]
base = "{WEIGHT} da lano"

[STR_CID_ALCOHOL]
base = "{TINYFONT}AL"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}KM"

[STR_CID_CHEMICALS]
base = "{TINYFONT}ĤE"

[STR_CID_CLAY]
base = "{TINYFONT}AR"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}IP"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}TP"

[STR_CID_FISH]
base = "{TINYFONT}FI"

[STR_CID_TIMBER]
base = "{TINYFONT}PL"

[STR_CID_MILK]
base = "{TINYFONT}LK"

[STR_CID_PETROL]
base = "{TINYFONT}PT"

[STR_CID_SAND]
base = "{TINYFONT}SA"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}PM"

[STR_CID_AGGREGATES]
base = "{TINYFONT}ŜT"

[STR_CID_WOOL]
base = "{TINYFONT}LN"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}FIRS ne estas farata por kongrui ĉe la Toyland klimato"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "devas loki sub la neĝa linio."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "devas loki sur seka tero."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "ne devas loki en la dezerto."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "ne povas loki sur krutaj deklivoj."

[STR_IND_ALUMINIUM_PLANT]
base = "Aluminifarejo"

[STR_IND_ARABLE_FARM]
base = "Plugebla Farmo"

[STR_IND_BIOREFINERY]
base = "Organrafinejo"

[STR_IND_BREWERY]
base = "Alkoholfarejo"

[STR_IND_BRICK_WORKS]
base = "Brikfarejo"

[STR_IND_BUILDERS_YARD]
base = "Konstruistkorto"

[STR_IND_CEMENT_PLANT]
base = "Cementfarejo"

[STR_IND_CLAY_PIT]
base = "Argila Fosaĵo"

[STR_IND_DAIRY]
base = "Laktfarejo"

[STR_IND_DREDGING_SITE]
base = "Skrapejo"

[STR_IND_FISHING_GROUND]
base = "Fiŝkaptejo"

[STR_IND_FISHING_HARBOUR]
base = "Fiŝkapta Haveno"

[STR_IND_FOOD_MARKET]
base = "Manĝaĵa Vendejo"

[STR_IND_FURNITURE_FACTORY]
base = "Meblarfarejo"

[STR_IND_GLASS_WORKS]
base = "Glasfarejo"

[STR_IND_HARDWARE_STORE]
base = "Laborila Vendejo"

[STR_IND_HOTEL]
base = "Hotelo"

[STR_IND_IRON_WORKS]
base = "Fermetiejo"

[STR_IND_SCRAP_YARD]
base = "Forĵetaĵejo"

[STR_IND_LIME_KILN]
base = "Kalkforno"

[STR_IND_TIMBER_YARD]
base = "Prilaboritejo de Ligno"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "Maŝinfarejo"

[STR_IND_MIXEDFARM]
base = "Miksa Farmo"

[STR_IND_PETROLPUMP]
base = "Petrolpumpilo"

[STR_IND_PLASTICS_PLANT]
base = "Plastfarejo"

[STR_IND_QUARRY]
base = "Ŝtonejo"

[STR_IND_RECYCLING_DEPOT]
base = "Reuzada Tenejo"

[STR_IND_RECYCLING_PLANT]
base = "Reuzada Faciligo"

[STR_IND_SHEEPFARM]
base = "Ŝafa Farmo"

[STR_IND_SMITHY_FORGE]
base = "Forĝejo de Metalisto"

[STR_IND_STOCKYARD]
base = "Prilaboritejo de Brutaro"

[STR_IND_SUGAR_REFINERY]
base = "Sukerarafinejo"

[STR_IND_TEXTILE_MILL]
base = "Teksaĵfarejo"

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Loko: {YELLOW}Ne povas esti fondata sur neĝo aŭ en dezertoj aŭ sur krutaj deklivoj."

[STR_FUND_FOREST]
base = "{}{BLACK}Loko: {YELLOW}Ne povas esti fondata en dezertoj."

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Loko: {YELLOW}Ne povas esti fondata sur neĝo."
