[GLOBAL_PRAGMA]
grflangid = "0x35"
plural = "0"

[STR_GRF_DESC]
base = "{ORANGE}FIRS Industry Replacement Set{}{BLACK}Tekijät: andythenorth, FooBar, planetmaker, Terkhen and Yexo sekä kaikki muut apuna olleet. {SILVER}Lisätietoja, mukaan lukien käyttöoppaan, löydät readme-tiedostosta. {BLACK}Lisenssi: GPL v2."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Kalastus- ja ruoppausalueiden sekä öljylauttojen etäisyys rannasta ruutuina."

[STR_PARAM_DESC_ECONOMIES]
base = "Jokainen talousvaihtoehto mahdollistaa erilaisen yhdistelmän rahteja ja teollisuuksia.{}{}Yksinkertaisesta pelityylistä pitävien kannattaa kokeilla {SILVER}pelkistettyjä {BLACK}talouksia, joissa on vähemmän teollisuustyyppejä ja rahteja verrattuna muihin FIRS:in talouksiin.{}{}FIRS:in kotisivu antaa tarkempaa tietoa erilaisista talouksista."

[STR_PARAM_DESC_NO_OPENINGS]
base = "Oletuksena uusia teollisuuslaitoksia avautuu pelin aikana.{}{}{SILVER}Avautumisen eston{BLACK} ollessa käytössä ensisijaisia teollisuuslaitoksia ei avaudu pelin aikana, eivätkä pelaajat voi rahoittaa niitä."

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Meriteollisuuden vähimmäismatka rantaan, ruutuina"

[STR_PARAM_NAME_ECONOMIES]
base = "Talous"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Estä teollisuuslaitosten avaaminen pelin aikana"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Ei rajaa"

[STR_PARAM_NAME_PRIMARY_LEVEL1_REQUIREMENT]
base = "Toimita laatikoita vaadittuna tehostettuun alkutuotantoon (oletus 16)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_REQUIREMENT]
base = "Tarvikelaatikoita vaaditaan lietsottuun alkutuotantoon (oletusarvo 80)"

[STR_PARAM_DESC_PRIMARY_LEVEL_REQUIREMENT]
base = "Maatilat, kaivokset, ja vastaavat teollisuudet lisäävät tuotantoa kun tarvikelaatikoita  toimitetaan, ensin {SILVER}Tehostetuksi{BLACK}, ja sitten {SILVER}Lietsotuksi{BLACK}, jos tarvikelaatikoita toimitetaan tarpeeksi.{}{}Esiasetellut arvot ovat hyviä, mutta jos haluat, voit vaihtaa niitä tässä.{}{}Rahtivaatimukset satama-tyyppisille teollisuuksille ovat  8x täällä asetettuihin arvoihin nähden."

[STR_PARAM_NAME_PRIMARY_LEVEL1_BONUS]
base = "Tehostettu alkutuotannon taso (%)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_BONUS]
base = "Lietsottu alkutuotannon taso (%)"

[STR_PARAM_DESC_PRIMARY_LEVEL_BONUS]
base = "Tuotanto maatiloilla, kaivoksissa ja vastaavissa teollisuuslaitoksissa kun toimitusvaatimukset ovat saavutettu (prosentteina {SILVER}normaalista {BLACK}tuotantotasosta)."

[STR_PARAM_VALUE_ECONOMIES_BASIC_TEMPERATE]
base = "Lauhkea ilmasto, pelkistetty"

[STR_PARAM_VALUE_ECONOMIES_BASIC_ARCTIC]
base = "Pohjoinen ilmasto, pelkistetty"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TROPIC]
base = "Trooppinen, pelkistetty"

[STR_PARAM_VALUE_ECONOMIES_IN_A_HOT_COUNTRY]
base = "Kuumassa maassa"

[STR_PARAM_VALUE_ECONOMIES_STEELTOWN]
base = "Teräskylä"

[STR_CARGO_NAME_ALCOHOL]
base = "Alkoholi"

[STR_CARGO_NAME_BAUXITE]
base = "Bauksiitti"

[STR_CARGO_NAME_BEANS]
base = "Pavut"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "Rakennusmateriaalit"

[STR_CARGO_NAME_CASSAVA]
base = "Maniokki"

[STR_CARGO_NAME_CEMENT]
base = "Sementti"

[STR_CARGO_NAME_CHEMICALS]
base = "Kemikaalit"

[STR_CARGO_NAME_CLAY]
base = "Savi"

[STR_CARGO_NAME_COFFEE]
base = "Kahvi"

[STR_CARGO_NAME_COKE]
base = "Koksi"

[STR_CARGO_NAME_COPPER]
base = "Kupari"

[STR_CARGO_NAME_EDIBLE_OIL]
base = "Ruokaöljy"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "Tekniset tarvikkeet"

[STR_CARGO_NAME_EXPLOSIVES]
base = "Räjähteet"

[STR_CARGO_NAME_FIBRES]
base = "Kasvikuidut"

[STR_CARGO_NAME_FISH]
base = "Kala"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "Maataloustarvikkeet"

[STR_CARGO_NAME_FERTILISER]
base = "Lannoite"

[STR_CARGO_NAME_FRUITS]
base = "Hedelmät"

[STR_CARGO_NAME_KAOLIN]
base = "Kaoliini"

[STR_CARGO_NAME_LIMESTONE]
base = "Kalkkikivi"

[STR_CARGO_NAME_TIMBER]
base = "Puutavara"

[STR_CARGO_NAME_MILK]
base = "Maito"

[STR_CARGO_NAME_MANGANESE]
base = "Mangaani"

[STR_CARGO_NAME_NITRATES]
base = "Nitraatit"

[STR_CARGO_NAME_NUTS]
base = "Pähkinöitä"

[STR_CARGO_NAME_PEAT]
base = "Turve"

[STR_CARGO_NAME_PETROL]
base = "Bensiinipolttoaine"

[STR_CARGO_NAME_PHOSPHATE]
base = "Fosfaatti"

[STR_CARGO_NAME_PIG_IRON]
base = "Takkirauta"

[STR_CARGO_NAME_POTASH]
base = "Kaliumkarbonaatti"

[STR_CARGO_NAME_PYRITE_ORE]
base = "Pyriittimalmi"

[STR_CARGO_NAME_QUICKLIME]
base = "Poltettu kalkki"

[STR_CARGO_NAME_RECYCLABLES]
base = "Kierrätystavara"

[STR_CARGO_NAME_SALT]
base = "Suola"

[STR_CARGO_NAME_SAND]
base = "Hiekka"

[STR_CARGO_NAME_SCRAP_METAL]
base = "Romumetalli"

[STR_CARGO_NAME_SLAG]
base = "Kuona"

[STR_CARGO_NAME_SODA_ASH]
base = "Soodatuhka"

[STR_CARGO_NAME_STEEL]
base = "Teräs"

[STR_CARGO_NAME_AGGREGATES]
base = "Kivi"

[STR_CARGO_NAME_SUGAR_BEET]
base = "Sokerijuurikas"

[STR_CARGO_NAME_SULPHUR]
base = "Rikki"

[STR_CARGO_NAME_VEHICLE_BODIES]
base = "Ajoneuvojen korit"

[STR_CARGO_NAME_VEHICLE_PARTS]
base = "Ajoneuvojen osat"

[STR_CARGO_NAME_VEHICLES]
base = "Ajoneuvot"

[STR_CARGO_NAME_WOOL]
base = "Villa"

[STR_CARGO_NAME_ZINC]
base = "Sinkki"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} alkoholia"

[STR_CARGO_UNIT_BAUXITE]
base = "{WEIGHT} bauksiittia"

[STR_CARGO_UNIT_BEANS]
base = "{WEIGHT} papuja"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} rakennusmateriaaleja"

[STR_CARGO_UNIT_CASSAVA]
base = "{WEIGHT} maniokkia"

[STR_CARGO_UNIT_CEMENT]
base = "{WEIGHT} sementtiä"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} kemikaaleja"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} savea"

[STR_CARGO_UNIT_COFFEE]
base = "{SIGNED_WORD} säkki{P 0 \"\" ä} kahvia"

[STR_CARGO_UNIT_COKE]
base = "{WEIGHT} koksia"

[STR_CARGO_UNIT_COPPER]
base = "{WEIGHT} kuparia"

[STR_CARGO_UNIT_EDIBLE_OIL]
base = "{VOLUME} ruokaöljyä"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} laatikko{P 0 \"\" a} teknisiä tarvikkeita"

[STR_CARGO_UNIT_EXPLOSIVES]
base = "{SIGNED_WORD} laatikko{P 0 \"\" a} räjähteitä"

[STR_CARGO_UNIT_FERTILISER]
base = "{WEIGHT} lannoitetta"

[STR_CARGO_UNIT_FIBRES]
base = "{SIGNED_WORD} paali{P 0 \"\" a} kasvikuituja"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} kalaa"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} laatikko{P 0 \"\" a} maataloustarvikkeita"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} hedelmiä"

[STR_CARGO_UNIT_KAOLIN]
base = "{WEIGHT} kaoliinia"

[STR_CARGO_UNIT_LIMESTONE]
base = "{WEIGHT} kalkkikiveä"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} puutavaraa"

[STR_CARGO_UNIT_MANGANESE]
base = "{WEIGHT} mangaania"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} maitoa"

[STR_CARGO_UNIT_NICKEL]
base = "{WEIGHT} nikkeliä"

[STR_CARGO_UNIT_NITRATES]
base = "{WEIGHT} nitraatteja"

[STR_CARGO_UNIT_NUTS]
base = "{SIGNED_WORD} säkki{P 0 \"\" ä} of pähkinöitä"

[STR_CARGO_UNIT_PEAT]
base = "{WEIGHT} turvetta"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} bensiinipolttoainetta"

[STR_CARGO_UNIT_PHOSPHATE]
base = "{WEIGHT} fosfaattia"

[STR_CARGO_UNIT_PIG_IRON]
base = "{WEIGHT} takkirautaa"

[STR_CARGO_UNIT_POTASH]
base = "{WEIGHT} kaliumkarbonaattia"

[STR_CARGO_UNIT_PYRITE_ORE]
base = "{WEIGHT} pyriittimalmia"

[STR_CARGO_UNIT_QUICKLIME]
base = "{WEIGHT} poltettua kalkkia"

[STR_CARGO_UNIT_RECYCLABLES]
base = "{WEIGHT} kierrätystavaraa"

[STR_CARGO_UNIT_SALT]
base = "{WEIGHT} suolaa"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} hiekkaa"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} romumetallia"

[STR_CARGO_UNIT_SLAG]
base = "{WEIGHT} kuonaa"

[STR_CARGO_UNIT_SODA_ASH]
base = "{WEIGHT} soodatuhkaa"

[STR_CARGO_UNIT_STEEL]
base = "{WEIGHT} terästä"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} kiveä"

[STR_CARGO_UNIT_SUGAR_BEET]
base = "{WEIGHT} sokerijuurikasta"

[STR_CARGO_UNIT_SULPHUR]
base = "{WEIGHT} rikkiä"

[STR_CARGO_UNIT_VEHICLE_BODIES]
base = "{WEIGHT} ajoneuvojen koreja"

[STR_CARGO_UNIT_VEHICLE_PARTS]
base = "{WEIGHT} ajoneuvojen osia"

[STR_CARGO_UNIT_VEHICLES]
base = "{WEIGHT} ajoneuvoja"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} paali{P 0 \"\" a} villaa"

[STR_CARGO_UNIT_ZINC]
base = "{WEIGHT} sinkkiä"

[STR_CID_ALCOHOL]
base = "{TINYFONT}AL"

[STR_CID_BAUXITE]
base = "{TINYFONT}BS"

[STR_CID_BEANS]
base = "{TINYFONT}PA"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}RK"

[STR_CID_CASSAVA]
base = "{TINYFONT}MA"

[STR_CID_CEMENT]
base = "{TINYFONT}SE"

[STR_CID_CHEMICALS]
base = "{TINYFONT}KM"

[STR_CID_CLAY]
base = "{TINYFONT}SV"

[STR_CID_COFFEE]
base = "{TINYFONT}KA"

[STR_CID_COKE]
base = "{TINYFONT}KO"

[STR_CID_COPPER]
base = "{TINYFONT}KU"

[STR_CID_EDIBLE_OIL]
base = "{TINYFONT}RÖ"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}TK"

[STR_CID_EXPLOSIVES]
base = "{TINYFONT}RÄ"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}MT"

[STR_CID_FERTILISER]
base = "{TINYFONT}LN"

[STR_CID_FIBRES]
base = "{TINYFONT}KK"

[STR_CID_FISH]
base = "{TINYFONT}KL"

[STR_CID_KAOLIN]
base = "{TINYFONT}KA"

[STR_CID_LIMESTONE]
base = "{TINYFONT}KK"

[STR_CID_TIMBER]
base = "{TINYFONT}PT"

[STR_CID_MANGANESE]
base = "{TINYFONT}MN"

[STR_CID_MILK]
base = "{TINYFONT}MA"

[STR_CID_NICKEL]
base = "{TINYFONT}NK"

[STR_CID_NITRATES]
base = "{TINYFONT}NI"

[STR_CID_NUTS]
base = "{TINYFONT}PÄ"

[STR_CID_PEAT]
base = "{TINYFONT}TU"

[STR_CID_PETROL]
base = "{TINYFONT}BN"

[STR_CID_PIG_IRON]
base = "{TINYFONT}TR"

[STR_CID_PHOSPHATE]
base = "{TINYFONT}FO"

[STR_CID_POTASH]
base = "{TINYFONT}PA"

[STR_CID_PYRITE_ORE]
base = "{TINYFONT}PY"

[STR_CID_QUICKLIME]
base = "{TINYFONT}SK"

[STR_CID_RECYCLABLES]
base = "{TINYFONT}KT"

[STR_CID_SALT]
base = "{TINYFONT}SL"

[STR_CID_SAND]
base = "{TINYFONT}HK"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}RM"

[STR_CID_SLAG]
base = "{TINYFONT}KN"

[STR_CID_SODA_ASH]
base = "{TINYFONT}ST"

[STR_CID_STEEL]
base = "{TINYFONT}TE"

[STR_CID_AGGREGATES]
base = "{TINYFONT}KV"

[STR_CID_SUGAR_BEET]
base = "{TINYFONT}SJ"

[STR_CID_SULPHUR]
base = "{TINYFONT}RI"

[STR_CID_VEHICLE_BODIES]
base = "{TINYFONT}AR"

[STR_CID_VEHICLE_PARTS]
base = "{TINYFONT}AO"

[STR_CID_VEHICLES]
base = "{TINYFONT}AJ"

[STR_CID_WOOL]
base = "{TINYFONT}VL"

[STR_CID_ZINC]
base = "{TINYFONT}SI"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}FIRS:iä ei ole suunniteltu toimivaksi Lelumaassa"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "sijoitettava lumirajan alapuolelle."

[STR_ERR_LOCATION_NOT_BELOW_SNOWLINE]
base = "sijoitettava lumirajan yläpuolelle."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "sijoitettava kuivalle maalle."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "ei voida sijoittaa aavikolle."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "ei voida sijoittaa jyrkkiin rinteisiin."

[STR_ERR_LOCATION_LIMIT_1_PER_TOWN]
base = "yhtä kaupunkia kohden sallitaan vain yksi tämän tyypin teollisuus."

[STR_IND_ALUMINIUM_PLANT]
base = "Alumiinitehdas"

[STR_IND_AMMONIA_PLANT]
base = "Ammoniakkitehdas"

[STR_IND_ARABLE_FARM]
base = "Viljelytila"

[STR_IND_ASSEMBLY_PLANT]
base = "Ajoneuvotehdas"

[STR_IND_BASIC_OXYGEN_FURNACE]
base = "Happipuhallusmasuuni"

[STR_IND_BIOREFINERY]
base = "Biojalostamo"

[STR_IND_BLAST_FURNACE]
base = "Masuuni"

[STR_IND_BREWERY]
base = "Panimo"

[STR_IND_CIDER_MILL]
base = "Panimo"

[STR_IND_BRICK_WORKS]
base = "Tiilitehdas"

[STR_IND_BUILDERS_YARD]
base = "Rakennustarvikevarasto"

[STR_IND_BULK_TERMINAL]
base = "Bulkkiterminaali"

[STR_IND_CEMENT_PLANT]
base = "Sementtitehdas"

[STR_IND_CHEMICAL_PLANT]
base = "Kemiantehdas"

[STR_IND_CLAY_PIT]
base = "Savenottoalue"

[STR_IND_COFFEE_ESTATE]
base = "Kahvitila"

[STR_IND_COKE_OVEN]
base = "Koksiuuni"

[STR_IND_COPPER_SMELTER]
base = "Kuparinjalostamo"

[STR_IND_DAIRY]
base = "Meijeri"

[STR_IND_DAIRY_FARM]
base = "Maitotila"

[STR_IND_DREDGING_SITE]
base = "Ruoppausalue"

[STR_IND_ELECTRIC_ARC_FURNACE]
base = "Valokaariuuni"

[STR_IND_FISHING_GROUND]
base = "Kalastusalue"

[STR_IND_FISHING_HARBOUR]
base = "Kalasatama"

[STR_IND_FISHING_VILLAGE]
base = "Kalastajakylä"

[STR_IND_FLOUR_MILL]
base = "Jauhomylly"

[STR_IND_FOOD_MARKET]
base = "Ruokakauppa"

[STR_IND_FOOD_PROCESSOR]
base = "Ruokatehdas"

[STR_IND_FURNITURE_FACTORY]
base = "Huonekalutehdas"

[STR_IND_GENERAL_STORE]
base = "Sekatavarakauppa"

[STR_IND_GLASS_WORKS]
base = "Lasitehdas"

[STR_IND_HARDWARE_STORE]
base = "Rautakauppa"

[STR_IND_HOTEL]
base = "Hotelli"

[STR_IND_HERDING_COOP]
base = "Metsästysleiri"

[STR_IND_IRON_WORKS]
base = "Rautaruukki"

[STR_IND_SCRAP_YARD]
base = "Romuttamo"

[STR_IND_LIME_KILN]
base = "Kalkkiuuni"

[STR_IND_LIMESTONE_MINE]
base = "Kalkkikivikaivos"

[STR_IND_LIQUIDS_TERMINAL]
base = "Nesteterminaali"

[STR_IND_TIMBER_YARD]
base = "Taapeli"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "Konepaja"

[STR_IND_MANGANESE_MINE]
base = "Mangaanikaivos"

[STR_IND_MIXEDFARM]
base = "Maatila"

[STR_IND_NITRATE_MINE]
base = "Nitraattikaivos"

[STR_IND_ORCHARD_PIGGERY]
base = "Hedelmätarha ja sikala"

[STR_IND_PEATLANDS]
base = "Turvesuo"

[STR_IND_PETROLPUMP]
base = "Huoltoasema"

[STR_IND_PHOSPHATE_MINE]
base = "Fosfaattikaivos"

[STR_IND_PLASTICS_PLANT]
base = "Muovitehdas"

[STR_IND_PORT]
base = "Satama"

[STR_IND_POTASH_MINE]
base = "Kaliumkarbonaattikaivos"

[STR_IND_PYRITE_MINE]
base = "Pyriittikaivos"

[STR_IND_PYRITE_SMELTER]
base = "Pyriittipasuttamo"

[STR_IND_POWER_PLANT]
base = "Voimalaitos"

[STR_IND_QUARRY]
base = "Hiekanottoalue"

[STR_IND_RANCH]
base = "Karjatila"

[STR_IND_RECYCLING_DEPOT]
base = "Kierrätyskeskus"

[STR_IND_RECYCLING_PLANT]
base = "Kierrätyslaitos"

[STR_IND_REINDEER_FARM]
base = "Porotila"

[STR_IND_SHEEPFARM]
base = "Lammastila"

[STR_IND_SLAG_GRINDING_PLANT]
base = "Kuonankäsittelytehdas"

[STR_IND_SMITHY_FORGE]
base = "Takomo"

[STR_IND_SODA_ASH_MINE]
base = "Soodatuhkakaivos"

[STR_IND_STOCKYARD]
base = "Teurastamo"

[STR_IND_SUGAR_REFINERY]
base = "Sokerinjalostamo"

[STR_IND_SUPPLY_YARD]
base = "Tarvikevarasto"

[STR_IND_TEXTILE_MILL]
base = "Tekstiilitehdas"

[STR_IND_TRADING_POST]
base = "Kauppa-asema"

[STR_IND_TYRE_PLANT]
base = "Rengastehdas"

[STR_IND_VINEYARD]
base = "Viinitarha"

[STR_CARGO_SUBTYPE_DISPLAY_CARGO_SUPPLIED_FLAG]
base = "{BLACK}(toimitettu)"

[STR_EXTRA_TEXT_SECONDARY_NON_COMBINATORY]
base = "{BLACK}Tuottaa maksimitasolla jos {WHITE}mitä tahansa {BLACK}vaadittua rahtia on toimitettu."

[STR_PRIMARY_PRODUCTION_1X]
base = "{BLACK}Nykyinen tuotanto: {YELLOW}Normaali{}{}{BLACK}Kuljeta {SIGNED_WORD} laatikkoa tarvikkeita kolmen kuukauden aikana {WHITE}tehostetulle{BLACK} tuotannolle.{}{WHITE}Lietsotulle{BLACK} tuotannolle  kuljeta {SIGNED_WORD} laatikkoa tarvikkeita."

[STR_PRIMARY_PRODUCTION_2X]
base = "{BLACK}Nykyinen tuotanto: {YELLOW}Tehostettu{}{}{BLACK}Kuljeta {SIGNED_WORD} laatikkoa tarvikkeita kolmen kuukauden sisällä pitääksesi tämän tason.{}{WHITE}Lietsotulle{BLACK} tuotannolle kuljeta {SIGNED_WORD} laatikkoa tarvikkeita."

[STR_PRIMARY_PRODUCTION_4X]
base = "{BLACK}Nykyinen tuotanto: {YELLOW}Lietsottu{}{}{BLACK}Kuljeta {SKIP}{SIGNED_WORD} laatikkoa tarvikkeita kolmen kuukauden sisällä pitääksesi tämän tason"

[STR_PORT_PRODUCTION_1X]
base = "{BLACK}Nykyinen tuotanto: {YELLOW}Normaali{}{}{BLACK}Kuljeta {SIGNED_WORD} yksikköä rahtia kolmen kuukauden aikana {WHITE}tehostetulle{BLACK} tuotannolle.{}{WHITE}Lietsotulle{BLACK} tuotannolle kuljeta {SIGNED_WORD} yksikköä rahtia."

[STR_PORT_PRODUCTION_2X]
base = "{BLACK}Nykyinen tuotanto: {YELLOW}Tehostettu{}{}{BLACK}Kuljeta {SIGNED_WORD} yksikköä tavaroita kolmen kuukauden sisällä pitääksesi tämän tason.{}{WHITE}Lietsotulle{BLACK} tuotannolle  kuljeta {SIGNED_WORD} yksikköä tavaroita."

[STR_PORT_PRODUCTION_4X]
base = "{BLACK}Nykyinen tuotanto: {YELLOW}Lietsottu{}{}{BLACK}Kuljeta {SKIP}{SIGNED_WORD} yksikköä tavaroita kolmen kuukauden sisällä pitääksesi tämän tason"

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Sijainti: {YELLOW}Ei voida sijoittaa lumeen, aavikoille eikä rinteisiin."

[STR_FUND_COFFEE_ESTATE]
base = "{}{BLACK}Sijainti: {YELLOW}Ei voida rahoittaa lumelle tai aavikolle."

[STR_FUND_DAIRY_FARM]
base = "{}{BLACK}Sijainti: {YELLOW}Ei voida rahoittaa lumelle tai aavikolle."

[STR_FUND_FOREST]
base = "{}{BLACK}Sijainti: {YELLOW}Ei voida sijoittaa aavikoille."

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Sijainti: {YELLOW}Ei voida sijoittaa lumeen."

[STR_FUND_HERDING_COOP]
base = "{}{BLACK}Sijainti: {YELLOW}Voidaan sijoittaa vain lumelle."

[STR_FUND_ORCHARD_PIGGERY]
base = "{}{BLACK}Sijainti: {YELLOW}Ei voida rahoittaa lumelle tai aavikolle."

[STR_FUND_RUBBER_PLANTATION]
base = "{}{BLACK}Sijainti: {YELLOW}Ei voida rahoittaa lumelle tai aavikolle."

[STR_FUND_VINEYARD]
base = "{}{BLACK}Sijainti: {YELLOW}Ei voida rahoittaa lumelle tai aavikolle."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}Saatavilla alkaen: {YELLOW}{COMMA}"

[STR_FUND_AVAILABLE_UNTIL]
base = "{}{BLACK}Ei saatavilla alkaen: {YELLOW}{COMMA}"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING}{STRING}"

[STR_STATION_ANIMALS]
base = ", hevostori"

[STR_STATION_AUTOMOTIVE]
base = ", autoteollisuus"

[STR_STATION_BAR_GRILL_AND_ROOMS]
base = ", baari, grilli ja huoneet"

[STR_STATION_BARNS]
base = ", aitat"

[STR_STATION_BARREL_AND_KEG]
base = ", tynnyri ja lekkeri"

[STR_STATION_BASE]
base = ", tukikohta"

[STR_STATION_BONEYARD]
base = ", luumaa"

[STR_STATION_BANK_TOP]
base = ", pankki"

[STR_STATION_CASTINGS]
base = ", valimo"

[STR_STATION_COLLIERY]
base = ", hiilikaivos"

[STR_STATION_COPPER_LODE]
base = ", kuparisuoni"

[STR_STATION_CREOSOTING]
base = ", kyllästämö"

[STR_STATION_DAIRY_LANE]
base = ", maitokatu"

[STR_STATION_ESTATE]
base = ", kartano"

[STR_STATION_EXCHANGE]
base = ", pörssi"

[STR_STATION_FARM_1]
base = ", tila"

[STR_STATION_FARM_2]
base = ", niityt"

[STR_STATION_FARM_3]
base = ", maatila"

[STR_STATION_FISHMARKET]
base = ", kalatori"

[STR_STATION_FOOD_CORPORATION]
base = ", ruokatehdas"

[STR_STATION_FOREST]
base = ", kuormausalue"

[STR_STATION_FORGE]
base = ", takomo"

[STR_STATION_FURNACE]
base = ", masuuni"

[STR_STATION_HEAVY_EQUIPMENT_YARD]
base = ", raskaan kaluston alue"

[STR_STATION_HEAVY_INDUSTRY_2]
base = ", paja"

[STR_STATION_HERDING_COOP]
base = ", maja"

[STR_STATION_INDUSTRY_ESTATE_1]
base = ", teollisuusalue"

[STR_STATION_INDUSTRY_HARBOUR_1]
base = ", teollisuussatama"

[STR_STATION_INDUSTRY_HARBOUR_2]
base = ", ranta"

[STR_STATION_INDUSTRY_HARBOUR_3]
base = ", laskualue"

[STR_STATION_IRONSTONE]
base = ", rautakivi"

[STR_STATION_JOINERS_SHOP]
base = ", yhdistäjän kauppa"

[STR_STATION_KILNS]
base = ", polttouunit"

[STR_STATION_KIMBERLITE_DEPOSITS]
base = ", kimberliittiesiintymä"

[STR_STATION_LIMESTONE_MINES]
base = ", kalkkikivikaivos"

[STR_STATION_MANGANESE_MINES]
base = ", mangaanikaivokset"

[STR_STATION_MARKET]
base = ", tori"

[STR_STATION_MILL]
base = ", mylly"

[STR_STATION_MINE]
base = ", kaivos"

[STR_STATION_MOULDINGS]
base = ", valut"

[STR_STATION_OIL_RIG]
base = ", kenttä"

[STR_STATION_ORCHARDS]
base = ", puutarha"

[STR_STATION_PIT]
base = ", monttu"

[STR_STATION_PLANTATION]
base = ", plantaasi"

[STR_STATION_POWERHUNGRY]
base = ", voimalaitos"

[STR_STATION_PUMPS]
base = ", pumput"

[STR_STATION_PYRITES]
base = ", pyriittiesiintymä"

[STR_STATION_REFINERY]
base = ", jalostamo"

[STR_STATION_RUBBER_COMPANY]
base = ", kumitehdas"

[STR_STATION_SALTPETER_WORKS]
base = ", ruutitehdas"

[STR_STATION_SHARP_STREET]
base = ", teräväkatu"

[STR_STATION_SHEEP_FOLD]
base = ", lammastarha"

[STR_STATION_SHOALS]
base = ", matalikot"

[STR_STATION_SILO]
base = ", siilo"

[STR_STATION_SMELTER]
base = ", sulatto"

[STR_STATION_STAMP_AND_PLATE]
base = ", leimasin ja levy"

[STR_STATION_SUGAR_COMPANY]
base = ", sokerinjalostamo"

[STR_STATION_TANK_FARM]
base = ", tankkifarmi"

[STR_STATION_TAPPERS_SHED]
base = ", kierteytysvaja"

[STR_STATION_TOWN_1]
base = ", vanha kaupungintalo"

[STR_STATION_TOWN_2]
base = ", korkeatie"

[STR_STATION_TOWN_3]
base = ", kauppa"

[STR_STATION_TRONA_BEDS]
base = ", karbonaattiesiintymä"

[STR_STATION_WATER]
base = ", hiekkasärkkä"

[STR_STATION_WEAVE_AND_DYE]
base = ", kutomo"

[STR_STATION_WELLS]
base = ", lähteet"

[STR_STATION_WINERY]
base = ", viinitila"
