[GLOBAL_PRAGMA]
grflangid = "0x13"
plural = "13"
gender = "m f"
case = "dat gen nom voc"

[STR_PARAM_NAME_ECONOMIES]
base = "Eaconamaidh"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Gun chuingeachadh"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TROPIC]
base = "Tropaigeach bunasach"

[STR_CARGO_NAME_ALCOHOL]
base = "Deoch làidir"

["STR_CARGO_NAME_ALCOHOL.dat"]
base = "Deoch làidir"

["STR_CARGO_NAME_ALCOHOL.gen"]
base = "Dighe làidir"

["STR_CARGO_NAME_ALCOHOL.nom"]
base = "Deoch làidir"

[STR_CARGO_NAME_BAUXITE]
base = "Clach-almain"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "Stuthan togail"

[STR_CARGO_NAME_CHEMICALS]
base = "Stuthan ceimigeach"

[STR_CARGO_NAME_CLAY]
base = "Criadh"

[STR_CARGO_NAME_COFFEE]
base = "Cofaidh"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "Goireasan innleadaireachd"

[STR_CARGO_NAME_FIBRES]
base = "Snàithlichean lusa"

[STR_CARGO_NAME_FISH]
base = "Iasg"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "Goireasan tuathanais"

[STR_CARGO_NAME_FRUITS]
base = "Measan"

[STR_CARGO_NAME_TIMBER]
base = "Fiodh"

[STR_CARGO_NAME_MILK]
base = "Bainne"

[STR_CARGO_NAME_PETROL]
base = "Peatral"

[STR_CARGO_NAME_RECYCLABLES]
base = "Stuthan ath-chuairteachaidh"

[STR_CARGO_NAME_SAND]
base = "Gainmheach"

[STR_CARGO_NAME_SCRAP_METAL]
base = "Fuighill meatailt"

[STR_CARGO_NAME_AGGREGATES]
base = "Clach"

[STR_CARGO_NAME_SUGAR_BEET]
base = "Biatas-siùcair"

[STR_CARGO_NAME_WOOL]
base = "Clòimh"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} de dheoch làidir"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} de stuthan togail"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} {P chreat chreat creataichean creat} de ghoireasan innleadaireachd"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} de bhainne"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} de peatrail"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} ce chlachan"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}FM"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "feumar a chur nas ìsle na an loidhne-sneachda"

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "feumar a chur air tìr thioram."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "chan fhad thu a chur ann am fàsach."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "cha ghabh a chur air slèibhtean casa."

[STR_IND_ARABLE_FARM]
base = "Tuineachas-àitich"

[STR_IND_BULK_TERMINAL]
base = "Togalach tomaid"

[STR_IND_CLAY_PIT]
base = "Sloc criadha"

[STR_IND_SCRAP_YARD]
base = "Fuigheall-lann"

[STR_IND_QUARRY]
base = "Coireall"

[STR_IND_SMITHY_FORGE]
base = "Ceàrdach gobhainn"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Ionad: {YELLOW}cha ghabh a stèidheachadh air sneachd no ann am fàsach."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}Ri fhaighinn o: {YELLOW}{COMMA}"

[STR_STATION_FISHMARKET]
base = "Margaid iasg"

[STR_STATION_MILL]
base = "Muileann"

[STR_STATION_POWERHUNGRY]
base = "Taigh-cumhachd"
