[GLOBAL_PRAGMA]
grflangid = "0x39"
plural = "1"

[STR_CARGO_NAME_ACID]
base = "硫酸"

[STR_CARGO_NAME_ALCOHOL]
base = "酒"

[STR_CARGO_NAME_BEANS]
base = "大豆"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "建材"

[STR_CARGO_NAME_CASSAVA]
base = "キャッサバ"

[STR_CARGO_NAME_CEMENT]
base = "セメント"

[STR_CARGO_NAME_COKE]
base = "コークス"

[STR_CARGO_NAME_EDIBLE_OIL]
base = "食用油"

[STR_CARGO_NAME_FISH]
base = "魚"

[STR_CARGO_NAME_FERTILISER]
base = "肥料"

[STR_CARGO_NAME_KAOLIN]
base = "陶土"

[STR_CARGO_NAME_MILK]
base = "牛乳"

[STR_CARGO_NAME_PETROL]
base = "ガソリン"

[STR_CARGO_NAME_PIG_IRON]
base = "銑鉄"

[STR_CARGO_NAME_SLAG]
base = "スラグ"

[STR_CARGO_NAME_SODA_ASH]
base = "ソーダ灰"

[STR_CARGO_NAME_AGGREGATES]
base = "石材"

[STR_CARGO_NAME_VEHICLE_BODIES]
base = "車体ボデー"

[STR_CARGO_NAME_WOOL]
base = "ウール"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME}の牛乳"

[STR_CARGO_UNIT_PEAT]
base = "{WEIGHT}の泥炭"

[STR_CARGO_UNIT_SAND]
base = "砂の {WEIGHT}"

[STR_CARGO_UNIT_ZINC]
base = "亜鉛 {WEIGHT}"

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "急斜面には設置できません"

[STR_IND_ARABLE_FARM]
base = "耕地"

[STR_IND_BASIC_OXYGEN_FURNACE]
base = "転炉"

[STR_IND_CIDER_MILL]
base = "リンゴ酒造所"

[STR_IND_BUILDERS_YARD]
base = "倉庫"

[STR_IND_CHEMICAL_PLANT]
base = "科学工場"

[STR_IND_CLAY_PIT]
base = "耐火粘土採掘所"

[STR_IND_COKE_OVEN]
base = "コークス炉"

[STR_IND_COPPER_SMELTER]
base = "製銅工場"

[STR_IND_DAIRY]
base = "酪農"

[STR_IND_DREDGING_SITE]
base = "浚渫工事現場"

[STR_IND_ELECTRIC_ARC_FURNACE]
base = "電気炉"

[STR_IND_FISHING_GROUND]
base = "漁場"

[STR_IND_FOOD_MARKET]
base = "八百屋"

[STR_IND_GENERAL_STORE]
base = "雑貨店"

[STR_IND_GLASS_WORKS]
base = "硝子工場"

[STR_IND_HARDWARE_STORE]
base = "ホームセンター"

[STR_IND_MANGANESE_MINE]
base = "マンガン鉱山"

[STR_IND_PETROLPUMP]
base = "ガソリンスタンド"

[STR_IND_PYRITE_MINE]
base = "黄鉄鉱鉱山"

[STR_IND_PYRITE_SMELTER]
base = "黄鉄鉱製錬所"

[STR_IND_RANCH]
base = "牧場"

[STR_IND_SHEEPFARM]
base = "羊牧場"

[STR_IND_STOCKYARD]
base = "家畜置き場"

[STR_IND_SUGAR_REFINERY]
base = "製糖工場"

[STR_IND_VINEYARD]
base = "ぶどう園"

[STR_STATION_BASE]
base = "ふもと"

[STR_STATION_FISHMARKET]
base = "魚市場"

[STR_STATION_MANGANESE_MINES]
base = "マンガン鉱山"

[STR_STATION_ORCHARDS]
base = "農園"

[STR_STATION_TOWN_3]
base = "商店街"
