[GLOBAL_PRAGMA]
grflangid = "0x23"
plural = "0"

[STR_GRF_DESC]
base = "{ORANGE}FIRS Industry Replacement Set{}{BLACK}Codéiert vum andythenorth, FooBar, planetmaker, Terkhen an Yexo, mat der Hëllef vun villen aneren. {SILVER}Lies de readme fir méi Informatiounen iwwert d'Benotzung vun FIRS. {BLACK}Lizenz: GPL v2."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maximalen Ofstand vun Fëschgrënn, Buerinselen an Baggerweiheren vun der Küst a Felder ausgedréckt."

[STR_PARAM_DESC_ECONOMIES]
base = "All Wiertschaftstyp stellt verschidden Industrien a Frachtarten bereed.{}{}De Wiertschaftstyp {SILVER}Einfach {BLACK}bidd manner Industrien a Frachtarten un, wéi déi aner Wiertschaftstypen.{}{}Op der FIRS Websäit kann een weider Informatiounen iwwer déi verschidden Wiertschaftstypen noliesen."

[STR_PARAM_DESC_NO_OPENINGS]
base = "Standardméisseg ginn nei Industrie während dem Spill opgemet.{}{}Wann {SILVER}net opmaachen{BLACK} ugewielt ass, maachen keng nei Industrien während dem Spill op, an d'Spiller kënnen och keng nei Industrien bauen oder fördern."

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maximalen Ofstand vun Séindustrien vun der Küst a Felder ausgedréckt"

[STR_PARAM_NAME_ECONOMIES]
base = "Wiertschaftstyp"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Verhënner, datt nei Industrien während dem Spill gegrënnt ginn"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Ouni Limite"

[STR_PARAM_NAME_PRIMARY_LEVEL1_REQUIREMENT]
base = "Këschten déi fir erweidert Produktioun gebraucht ginn (Standard 16)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_REQUIREMENT]
base = "Këschten déi fir extrem Produktioun gebraucht ginn (Standard 80)"

[STR_PARAM_DESC_PRIMARY_LEVEL_REQUIREMENT]
base = "Baurenhäff, Minen an ähnlech Industrien wäerten hier Produktioun verbesseren, als éischt op {SILVER}Erweidert{BLACK}, an dann op {SILVER}Extrem{BLACK}, wa genuch Këschte geliwwert ginn.{}{}D'Standardwäerter si gutt, mee falls néideg, kënnen se geännert ginn.{}{}Wuerewäerter fir Industrien vum Typ \"Hafen\", sinn 8x déi hei agestallte Wäerter."

[STR_PARAM_NAME_PRIMARY_LEVEL1_BONUS]
base = "Erweiderte Primärproduktiounsniveau (%)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_BONUS]
base = "Extreme Primärproduktiounsniveau (%)"

[STR_PARAM_DESC_PRIMARY_LEVEL_BONUS]
base = "Produktioun op Häff, Minnen an ähnlëchen Industrien déi d'Beliwwerungsbedéngungen erfëllen  (als Prozentsaz vum Produktiounswert {SILVER}Normal {BLACK})."

[STR_PARAM_VALUE_ECONOMIES_BASIC_TEMPERATE]
base = "Geméissegt Klima (Einfach)"

[STR_PARAM_VALUE_ECONOMIES_BASIC_ARCTIC]
base = "Arktesch (Einfach)"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TROPIC]
base = "Tropesch (Einfach)"

[STR_PARAM_VALUE_ECONOMIES_IN_A_HOT_COUNTRY]
base = "An engem waarme Land"

[STR_PARAM_VALUE_ECONOMIES_STEELTOWN]
base = "Steeltown"

[STR_CARGO_NAME_ALCOHOL]
base = "Alkohol"

[STR_CARGO_NAME_BEANS]
base = "Bounen"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "Baumaterial"

[STR_CARGO_NAME_CASSAVA]
base = "Maniok"

[STR_CARGO_NAME_CEMENT]
base = "Zement"

[STR_CARGO_NAME_CHEMICALS]
base = "Chemikalien"

[STR_CARGO_NAME_CLAY]
base = "Toun"

[STR_CARGO_NAME_COFFEE]
base = "Kaffi"

[STR_CARGO_NAME_COKE]
base = "Koks"

[STR_CARGO_NAME_COPPER]
base = "Koffer"

[STR_CARGO_NAME_EDIBLE_OIL]
base = "Speiseueleg"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "Ersatzdeeler"

[STR_CARGO_NAME_EXPLOSIVES]
base = "Sprengstoff"

[STR_CARGO_NAME_FISH]
base = "Fësch"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "Akerbaumëttel"

[STR_CARGO_NAME_FERTILISER]
base = "Dünger"

[STR_CARGO_NAME_FRUITS]
base = "Friichten"

[STR_CARGO_NAME_KAOLIN]
base = "Kaolin"

[STR_CARGO_NAME_TIMBER]
base = "Holzbrieder"

[STR_CARGO_NAME_MILK]
base = "Mëllech"

[STR_CARGO_NAME_MANGANESE]
base = "Mangan"

[STR_CARGO_NAME_NITRATES]
base = "Nitrater"

[STR_CARGO_NAME_NUTS]
base = "Nëss"

[STR_CARGO_NAME_PEAT]
base = "Torf"

[STR_CARGO_NAME_PETROL]
base = "Pëtrol"

[STR_CARGO_NAME_PHOSPHATE]
base = "Phosphat"

[STR_CARGO_NAME_PIG_IRON]
base = "réit Eisen"

[STR_CARGO_NAME_POTASH]
base = "Kalium"

[STR_CARGO_NAME_PYRITE_ORE]
base = "Pyritäerz"

[STR_CARGO_NAME_QUICKLIME]
base = "Ätzkalk"

[STR_CARGO_NAME_SAND]
base = "Sand"

[STR_CARGO_NAME_SCRAP_METAL]
base = "Schrott"

[STR_CARGO_NAME_SLAG]
base = "Schlaken"

[STR_CARGO_NAME_SODA_ASH]
base = "Natriumkarbonat"

[STR_CARGO_NAME_STEEL]
base = "Stol"

[STR_CARGO_NAME_AGGREGATES]
base = "Steng"

[STR_CARGO_NAME_SULPHUR]
base = "Schwefel"

[STR_CARGO_NAME_VEHICLE_BODIES]
base = "Chassisen"

[STR_CARGO_NAME_VEHICLE_PARTS]
base = "Autosdeeler"

[STR_CARGO_NAME_VEHICLES]
base = "Gefierer"

[STR_CARGO_NAME_WOOL]
base = "Woll"

[STR_CARGO_NAME_ZINC]
base = "Zénk"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} Alkohol"

[STR_CARGO_UNIT_BEANS]
base = "{WEIGHT} Bounen"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} Baumaterial"

[STR_CARGO_UNIT_CASSAVA]
base = "{WEIGHT} Maniok"

[STR_CARGO_UNIT_CEMENT]
base = "{WEIGHT} Zement"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} Chemikalien"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} Toun"

[STR_CARGO_UNIT_COFFEE]
base = "{SIGNED_WORD} S{P 0 ak äck} Kaffi"

[STR_CARGO_UNIT_COKE]
base = "{WEIGHT} Koks"

[STR_CARGO_UNIT_COPPER]
base = "{WEIGHT} Koffer"

[STR_CARGO_UNIT_EDIBLE_OIL]
base = "{VOLUME} Speiseueleg"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} Këscht{P 0 \"\" en} Ersatzdeeler"

[STR_CARGO_UNIT_EXPLOSIVES]
base = "{SIGNED_WORD} Këscht{P 0 \"\" e} Sprengstoff"

[STR_CARGO_UNIT_FERTILISER]
base = "{WEIGHT} Dünger"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} Fësch"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} Këscht{P 0 \"\" en} Akerbaumëttel"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} Friichten"

[STR_CARGO_UNIT_KAOLIN]
base = "{WEIGHT} Kaolin"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} Holzbrieder"

[STR_CARGO_UNIT_MANGANESE]
base = "{WEIGHT} Mangan"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} Mëllech"

[STR_CARGO_UNIT_NICKEL]
base = "{WEIGHT} Nickel"

[STR_CARGO_UNIT_NITRATES]
base = "{WEIGHT} Nitrater"

[STR_CARGO_UNIT_NUTS]
base = "{SIGNED_WORD} S{P 0 ak äck} Nëss"

[STR_CARGO_UNIT_PEAT]
base = "{WEIGHT} Torf"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} Pëtrol"

[STR_CARGO_UNIT_PHOSPHATE]
base = "{WEIGHT} Phosphat"

[STR_CARGO_UNIT_PIG_IRON]
base = "{WEIGHT} réit Eisen"

[STR_CARGO_UNIT_POTASH]
base = "{WEIGHT} Kalium"

[STR_CARGO_UNIT_PYRITE_ORE]
base = "{WEIGHT} Pyritäerz"

[STR_CARGO_UNIT_QUICKLIME]
base = "{WEIGHT} Ätzkalk"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} Sand"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} Schrott"

[STR_CARGO_UNIT_SLAG]
base = "{WEIGHT} Schlaken"

[STR_CARGO_UNIT_SODA_ASH]
base = "{WEIGHT} Natriumkarbonat"

[STR_CARGO_UNIT_STEEL]
base = "{WEIGHT} Stol"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} Steng"

[STR_CARGO_UNIT_SULPHUR]
base = "{WEIGHT} Schwefel"

[STR_CARGO_UNIT_VEHICLE_BODIES]
base = "{WEIGHT} Chassisen"

[STR_CARGO_UNIT_VEHICLE_PARTS]
base = "{SIGNED_WORD} Këscht{P 0 \"\" en} Autosdeeler"

[STR_CARGO_UNIT_VEHICLES]
base = "{SIGNED_WORD} Gefier{P 0 \"\" er}"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} Wollballen"

[STR_CARGO_UNIT_ZINC]
base = "{WEIGHT} Zénk"

[STR_CID_ALCOHOL]
base = "{TINYFONT}AL"

[STR_CID_BEANS]
base = "{TINYFONT}BN"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}BM"

[STR_CID_CASSAVA]
base = "{TINYFONT}MA"

[STR_CID_CEMENT]
base = "{TINYFONT}ZE"

[STR_CID_CHEMICALS]
base = "{TINYFONT}CH"

[STR_CID_CLAY]
base = "{TINYFONT}TN"

[STR_CID_COFFEE]
base = "{TINYFONT}KF"

[STR_CID_COKE]
base = "{TINYFONT}KK"

[STR_CID_COPPER]
base = "{TINYFONT}KO"

[STR_CID_EDIBLE_OIL]
base = "{TINYFONT}SP"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}ED"

[STR_CID_EXPLOSIVES]
base = "{TINYFONT}SP"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}AM"

[STR_CID_FERTILISER]
base = "{TINYFONT}DU"

[STR_CID_FISH]
base = "{TINYFONT}FE"

[STR_CID_KAOLIN]
base = "{TINYFONT}KA"

[STR_CID_TIMBER]
base = "{TINYFONT}HO"

[STR_CID_MANGANESE]
base = "{TINYFONT}MN"

[STR_CID_MILK]
base = "{TINYFONT}ML"

[STR_CID_NICKEL]
base = "{TINYFONT}NK"

[STR_CID_NITRATES]
base = "{TINYFONT}NI"

[STR_CID_NUTS]
base = "{TINYFONT}NE"

[STR_CID_PEAT]
base = "{TINYFONT}TO"

[STR_CID_PETROL]
base = "{TINYFONT}PT"

[STR_CID_PIG_IRON]
base = "{TINYFONT}RE"

[STR_CID_PHOSPHATE]
base = "{TINYFONT}PH"

[STR_CID_POTASH]
base = "{TINYFONT}KA"

[STR_CID_PYRITE_ORE]
base = "{TINYFONT}PY"

[STR_CID_QUICKLIME]
base = "{TINYFONT}KO"

[STR_CID_SAND]
base = "{TINYFONT}SA"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}SC"

[STR_CID_SLAG]
base = "{TINYFONT}SK"

[STR_CID_SODA_ASH]
base = "{TINYFONT}SA"

[STR_CID_STEEL]
base = "{TINYFONT}SL"

[STR_CID_AGGREGATES]
base = "{TINYFONT}ST"

[STR_CID_SULPHUR]
base = "{TINYFONT}SW"

[STR_CID_VEHICLE_BODIES]
base = "{TINYFONT}CH"

[STR_CID_VEHICLE_PARTS]
base = "{TINYFONT}AD"

[STR_CID_VEHICLES]
base = "{TINYFONT}GE"

[STR_CID_WOOL]
base = "{TINYFONT}WL"

[STR_CID_ZINC]
base = "{TINYFONT}ZN"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "muss ënnert der Schnéilinn gebaut ginn."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "dierf net op Waasser gebaut ginn."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "dierf net d'Wüst gesat ginn."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "kann net op schiefen Häng gebaut ginn."

[STR_ERR_LOCATION_LIMIT_1_PER_TOWN]
base = "nëmmen eng Industrie vun dësem Typ ass pro Stad erlabt"

[STR_IND_ALUMINIUM_PLANT]
base = "Aluminiumfabrik"

[STR_IND_ARABLE_FARM]
base = "Bauerenhaff (Akerbau)"

[STR_IND_ASSEMBLY_PLANT]
base = "Autosfabrik"

[STR_IND_BASIC_OXYGEN_FURNACE]
base = "LD Héichuewen"

[STR_IND_BLAST_FURNACE]
base = "Gebléisuewen"

[STR_IND_BREWERY]
base = "Brauerei"

[STR_IND_CIDER_MILL]
base = "Brennerei"

[STR_IND_BRICK_WORKS]
base = "Zillebäckerei"

[STR_IND_BUILDERS_YARD]
base = "Ponts et Chaussées"

[STR_IND_BULK_TERMINAL]
base = "Gidderterminal"

[STR_IND_CEMENT_PLANT]
base = "Zementfabrik"

[STR_IND_CHEMICAL_PLANT]
base = "Chemiepark"

[STR_IND_CLAY_PIT]
base = "Toungruef"

[STR_IND_COFFEE_ESTATE]
base = "Kaffisplantage"

[STR_IND_COKE_OVEN]
base = "Koksuewen"

[STR_IND_COPPER_SMELTER]
base = "Kofferraffinerie"

[STR_IND_DAIRY]
base = "Molkerei"

[STR_IND_DAIRY_FARM]
base = "Mëllechfarm"

[STR_IND_DREDGING_SITE]
base = "Baggersite"

[STR_IND_ELECTRIC_ARC_FURNACE]
base = "Elektrouewen"

[STR_IND_FISHING_GROUND]
base = "Fëschgrënn"

[STR_IND_FISHING_HARBOUR]
base = "Fëscherhafen"

[STR_IND_FLOUR_MILL]
base = "Mielmillen"

[STR_IND_FOOD_PROCESSOR]
base = "Liewensmëttelfabrik"

[STR_IND_FURNITURE_FACTORY]
base = "Miwwelfabrik"

[STR_IND_GENERAL_STORE]
base = "Buttek"

[STR_IND_GLASS_WORKS]
base = "Glasmécherbetrib"

[STR_IND_HARDWARE_STORE]
base = "Baumaart"

[STR_IND_HOTEL]
base = "Hotel"

[STR_IND_HERDING_COOP]
base = "Herde Co-Op"

[STR_IND_SCRAP_YARD]
base = "Schrottplaz"

[STR_IND_LIME_KILN]
base = "Kallekbrennerei"

[STR_IND_LIQUIDS_TERMINAL]
base = "Flësseggidderterminal"

[STR_IND_TIMBER_YARD]
base = "Holzverarbëschtung"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "Maschinnebuttek"

[STR_IND_MANGANESE_MINE]
base = "Manganminn"

[STR_IND_NITRATE_MINE]
base = "Nitratstollen"

[STR_IND_ORCHARD_PIGGERY]
base = "Bongert a Schwéngshaff"

[STR_IND_PEATLANDS]
base = "Torfland"

[STR_IND_PETROLPUMP]
base = "Tankstell"

[STR_IND_PHOSPHATE_MINE]
base = "Phosphatminn"

[STR_IND_PLASTICS_PLANT]
base = "Plastikfabrik"

[STR_IND_PORT]
base = "Hafen"

[STR_IND_POTASH_MINE]
base = "Kaliumminn"

[STR_IND_PYRITE_MINE]
base = "Pyritminn"

[STR_IND_PYRITE_SMELTER]
base = "Pyritschmelz"

[STR_IND_POWER_PLANT]
base = "Kraaftwierk"

[STR_IND_QUARRY]
base = "Steebroch"

[STR_IND_RANCH]
base = "Ranch"

[STR_IND_SHEEPFARM]
base = "Schofshaff"

[STR_IND_SLAG_GRINDING_PLANT]
base = "Zementmillenanlag"

[STR_IND_SMITHY_FORGE]
base = "Schmëtt"

[STR_IND_SODA_ASH_MINE]
base = "Natriumkarbonatminn"

[STR_IND_STOCKYARD]
base = "Schluechthaus"

[STR_IND_SUGAR_REFINERY]
base = "Zockerraffinerie"

[STR_IND_SUPPLY_YARD]
base = "Landmaschinneverkaf"

[STR_IND_TEXTILE_MILL]
base = "Textilfabrik"

[STR_IND_TRADING_POST]
base = "Handelsposten"

[STR_IND_TYRE_PLANT]
base = "Pneuefabrik"

[STR_IND_VINEYARD]
base = "Wéngert"

[STR_CARGO_SUBTYPE_DISPLAY_CARGO_SUPPLIED_FLAG]
base = "{BLACK}(geliwwert)"

[STR_EXTRA_TEXT_SECONDARY_NON_COMBINATORY]
base = "{BLACK}Produzéiert um Maximum wann {WHITE}iergendeng {BLACK}gebrauchte Wuer geliwwert gëtt."

[STR_PRIMARY_PRODUCTION_1X]
base = "{BLACK}Aktuell Produktioun: {YELLOW}Normal{}{}{BLACK}Fir d'Produktioun op {WHITE}erweidert{BLACK} ze hiewen, liwwer {SIGNED_WORD} Këschten innerhalb dräi Méint{}Fir d'Produktioun op {WHITE}extrem{BLACK} ze hiewen, liwwer {SIGNED_WORD} Këschten."

[STR_PRIMARY_PRODUCTION_2X]
base = "{BLACK}Aktuell Produktioun: {YELLOW}Erweidert{}{}{BLACK}Fir dësen Niveau ze halen, liwwer {SIGNED_WORD} Eenheete Gidder innerhalb dräi Méint{}Fir eng {WHITE}extrem {BLACK}Produktioun, liwwer {SIGNED_WORD} Këschten."

[STR_PRIMARY_PRODUCTION_4X]
base = "{BLACK}Aktuell Produktioun: {YELLOW}Enorm{}{}{BLACK}Fir dësen Niveau ze halen, liwwer {SKIP}{SIGNED_WORD} Këschte Material innerhalb dräi Méint."

[STR_PORT_PRODUCTION_1X]
base = "{BLACK}Aktuell Produktioun: {YELLOW}Normal{}{}{BLACK}Fir eng {WHITE}erweidert {BLACK}Produktioun, liwwer {SIGNED_WORD} Eenheete Gidder innerhalb dräi Méint{}Fir eng {WHITE}extrem {BLACK}Produktioun, liwwer {SIGNED_WORD} Eenheete Gidder."

[STR_PORT_PRODUCTION_2X]
base = "{BLACK}Aktuell Produktioun: {YELLOW}Erweidert{}{}{BLACK}Fir dësen Niveau ze halen, liwwer {SIGNED_WORD} Eenheete Gidder innerhalb dräi Méint. Fir eng {WHITE}extrem {BLACK}Produktioun, liwwer {SIGNED_WORD} Eenheeten."

[STR_PORT_PRODUCTION_4X]
base = "{BLACK}Aktuell Produktioun: {YELLOW}Enorm{}{}{BLACK}Fir dësen Niveau ze halen, liwwer {SKIP}{SIGNED_WORD} Eenheete Gidder innerhalb dräi Méint."

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Plaz: {YELLOW}Kann net op Schnéi oder an der Wüst gebaut ginn."

[STR_FUND_COFFEE_ESTATE]
base = "{}{BLACK}Plaz: {YELLOW}Kann net op Schnéi oder an der Wüst gebaut ginn."

[STR_FUND_DAIRY_FARM]
base = "{}{BLACK}Plaz: {YELLOW}Kann net op Schnéi oder an der Wüst gebaut ginn."

[STR_FUND_FOREST]
base = "{}{BLACK}Plaz: {YELLOW}Kann net an der Wüst gebaut ginn."

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Plaz: {YELLOW}Kann net op Schnéi gebaut ginn."

[STR_FUND_HERDING_COOP]
base = "{}{BLACK}Plaz: {YELLOW}Kann nëmmen um Schnéi gebaut ginn."

[STR_FUND_ORCHARD_PIGGERY]
base = "{}{BLACK}Plaz: {YELLOW}Kann net op Schnéi oder an der Wüst gebaut ginn."

[STR_FUND_RUBBER_PLANTATION]
base = "{}{BLACK}Plaz: {YELLOW}Kann net op Schnéi oder an der Wüst gebaut ginn."

[STR_FUND_VINEYARD]
base = "{}{BLACK}Plaz: {YELLOW}Kann net op Schnéi oder an der Wüst gebaut ginn."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}Verfügbar ab: {YELLOW}{COMMA}"

[STR_FUND_AVAILABLE_UNTIL]
base = "{}{BLACK}Nëmmi verfügbar no: {YELLOW}{COMMA}"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING} {STRING}"

[STR_STATION_ANIMALS]
base = "Véimaart"

[STR_STATION_BANK_TOP]
base = "Damm"

[STR_STATION_DAIRY_LANE]
base = "Mëllechwee"

[STR_STATION_FARM_1]
base = "Landsëtz"

[STR_STATION_FARM_2]
base = "Heed"

[STR_STATION_FARM_3]
base = "Ranch"

[STR_STATION_FISHMARKET]
base = "Fëschmaart"

[STR_STATION_FOREST]
base = "Bamstemmlager"

[STR_STATION_FURNACE]
base = "Héichuewen"

[STR_STATION_HEAVY_INDUSTRY_2]
base = "Wierk"

[STR_STATION_HERDING_COOP]
base = "Lodge"

[STR_STATION_INDUSTRY_ESTATE_1]
base = "Industriepark"

[STR_STATION_INDUSTRY_HARBOUR_1]
base = "Industriehafen"

[STR_STATION_INDUSTRY_HARBOUR_2]
base = "Miersäit"

[STR_STATION_INDUSTRY_HARBOUR_3]
base = "Bootsquai"

[STR_STATION_KILNS]
base = "Uewen"

[STR_STATION_MILL]
base = "Millen"

[STR_STATION_OIL_RIG]
base = "Feld"

[STR_STATION_PIT]
base = "Gruef"

[STR_STATION_PLANTATION]
base = "Plantage"

[STR_STATION_POWERHUNGRY]
base = "Kraaftwierk"

[STR_STATION_REFINERY]
base = "Raffinerie"

[STR_STATION_SILO]
base = "Silo"

[STR_STATION_SMELTER]
base = "Schmelz"

[STR_STATION_TANK_FARM]
base = "Tanken"

[STR_STATION_TOWN_1]
base = "Aal Märei"

[STR_STATION_TOWN_3]
base = "Buttéker"

[STR_STATION_WATER]
base = "Sandbänk"

[STR_STATION_WELLS]
base = "Quellen"
