[GLOBAL_PRAGMA]
grflangid = "0x2f"
plural = "0"
gender = "masculine feminine neuter"
case = "small"

[STR_GRF_DESC]
base = "{ORANGE}FIRS Industri Erstatnings-sett{}{BLACK}Bringes til deg av andythenorth, FooBar, planetmaker, Terkhen og Yexo, med hjelp fra mange andre. {SILVER}Se readme for mer informasjon, inkludert hvordan man bruker FIRS. {BLACK}Lisens: GPL v2."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Største avstand for fiskebanker, oljeplattformer og mudderbanker fra kysten (i brikker)."

[STR_PARAM_DESC_ECONOMIES]
base = "Hver økonomi tilbyr en ulik kombinasjon av varer og industrier.{}{}For spillere som ønsker et enklere spill, har {SILVER}basis{BLACK}økonomiene færre industrier og varer enn andre økonomier.{}{}Nettstedet for FIRS har detaljert informasjon om hver enkelt økonomi."

[STR_PARAM_DESC_NO_OPENINGS]
base = "Som standard vil nye industrier åpne i løpet av spillet.{}{}Hvis {SILVER}Forhindre at industrier åpner{BLACK} er slått på, vil ikke nye industrier åpne i løpet av spillet, og spillere kan ikke finansiere eller prospektere nye industrier."

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Største avstand fra kysten for marine industrier (i brikker)."

[STR_PARAM_NAME_ECONOMIES]
base = "Økonomi"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Forhindre at industrier åpner under spillet"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Ingen begrensning"

[STR_PARAM_NAME_PRIMARY_LEVEL1_REQUIREMENT]
base = "Antall kasser utstyr for Forbedret primær produksjon (standard 16)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_REQUIREMENT]
base = "Antall kasser utstyr for Gung-ho primær produksjon (standard 80)"

[STR_PARAM_DESC_PRIMARY_LEVEL_REQUIREMENT]
base = "Gårder, gruver og lignende industrier vil øke produksjonen hvis det blir levert utstyr, først til {SILVER}Forbedret{BLACK}, deretter til {SILVER}Gung-ho{BLACK} hvis mange nok kasser blir levert.{}{}Forhåndsinnstillingene er gode, men kan om nødvendig endres her.{}{}Varebehov for havneindustrier vil være 8 ganger de verdiene som angis her."

[STR_PARAM_NAME_PRIMARY_LEVEL1_BONUS]
base = "Forbedret primært produksjonsnivå (%)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_BONUS]
base = "Gung-ho primært produksjonsnivå (%)"

[STR_PARAM_DESC_PRIMARY_LEVEL_BONUS]
base = "Produksjon ved gårder, gruver og lignende industrier når krav til utstyr er innfridd (som prosentandel av {SILVER}Normalt{BLACK} produksjonsnivå)."

[STR_PARAM_VALUE_ECONOMIES_BASIC_TEMPERATE]
base = "Temperert basis"

[STR_PARAM_VALUE_ECONOMIES_BASIC_ARCTIC]
base = "Arktisk basis"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TROPIC]
base = "Tropisk basis"

[STR_PARAM_VALUE_ECONOMIES_IN_A_HOT_COUNTRY]
base = "I et hett land"

[STR_PARAM_VALUE_ECONOMIES_STEELTOWN]
base = "Stålbyen"

[STR_CARGO_NAME_ACID]
base = "Syre"

[STR_CARGO_NAME_ALCOHOL]
base = "Alkohol"

[STR_CARGO_NAME_BEANS]
base = "Bønner"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "Byggematerialer"

[STR_CARGO_NAME_CASSAVA]
base = "Kassava"

[STR_CARGO_NAME_CEMENT]
base = "Sement"

[STR_CARGO_NAME_CHEMICALS]
base = "Kjemikalier"

[STR_CARGO_NAME_CHLORINE]
base = "Klor"

[STR_CARGO_NAME_CLAY]
base = "Leire"

[STR_CARGO_NAME_COFFEE]
base = "Kaffe"

[STR_CARGO_NAME_COKE]
base = "Koks"

[STR_CARGO_NAME_COPPER]
base = "Kobber"

[STR_CARGO_NAME_EDIBLE_OIL]
base = "Matolje"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "Anleggsutstyr"

[STR_CARGO_NAME_EXPLOSIVES]
base = "Sprengstoff"

[STR_CARGO_NAME_FISH]
base = "Fisk"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "Gårdsutstyr"

[STR_CARGO_NAME_FERTILISER]
base = "Gjødsel"

[STR_CARGO_NAME_FRUITS]
base = "Frukt"

[STR_CARGO_NAME_KAOLIN]
base = "Kaolin"

[STR_CARGO_NAME_LIMESTONE]
base = "Kalkstein"

[STR_CARGO_NAME_TIMBER]
base = "Trelast"

[STR_CARGO_NAME_MILK]
base = "Melk"

[STR_CARGO_NAME_MANGANESE]
base = "Mangan"

[STR_CARGO_NAME_NITRATES]
base = "Nitrater"

[STR_CARGO_NAME_NUTS]
base = "Nøtter"

[STR_CARGO_NAME_PEAT]
base = "Torv"

[STR_CARGO_NAME_PETROL]
base = "Bensin"

[STR_CARGO_NAME_PHOSPHATE]
base = "Fosfat"

[STR_CARGO_NAME_PIG_IRON]
base = "Råjern"

[STR_CARGO_NAME_POTASH]
base = "Kalium"

[STR_CARGO_NAME_PYRITE_ORE]
base = "Pyrittmalm"

[STR_CARGO_NAME_QUICKLIME]
base = "Ulesket kalk"

[STR_CARGO_NAME_SALT]
base = "Salt"

[STR_CARGO_NAME_SAND]
base = "Sand"

[STR_CARGO_NAME_SCRAP_METAL]
base = "Skrapmetall"

[STR_CARGO_NAME_SLAG]
base = "Slagg"

[STR_CARGO_NAME_SODA_ASH]
base = "Soda"

[STR_CARGO_NAME_STEEL]
base = "Stål"

[STR_CARGO_NAME_AGGREGATES]
base = "Stein"

[STR_CARGO_NAME_SULPHUR]
base = "Svovel"

[STR_CARGO_NAME_VEHICLE_BODIES]
base = "Karosserier"

[STR_CARGO_NAME_VEHICLE_PARTS]
base = "Kjøretøydeler"

[STR_CARGO_NAME_VEHICLES]
base = "Kjøretøy"

[STR_CARGO_NAME_WOOL]
base = "Ull"

[STR_CARGO_NAME_ZINC]
base = "Sink"

[STR_CARGO_UNIT_ACID]
base = "{VOLUME} syre"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} alkohol"

[STR_CARGO_UNIT_BEANS]
base = "{WEIGHT} bønner"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} byggematerialer"

[STR_CARGO_UNIT_CASSAVA]
base = "{WEIGHT} kassava"

[STR_CARGO_UNIT_CEMENT]
base = "{WEIGHT} sement"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} kjemikalier"

[STR_CARGO_UNIT_CHLORINE]
base = "{VOLUME} klor"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} leire"

[STR_CARGO_UNIT_COFFEE]
base = "{SIGNED_WORD} sekk{P 0 \"\" er} kaffe"

[STR_CARGO_UNIT_COKE]
base = "{WEIGHT} koks"

[STR_CARGO_UNIT_COPPER]
base = "{WEIGHT} kobber"

[STR_CARGO_UNIT_EDIBLE_OIL]
base = "{VOLUME} matolje"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} kasse{P 0 \"\" r} anleggsutstyr"

[STR_CARGO_UNIT_EXPLOSIVES]
base = "{SIGNED_WORD} kasse{P 0 \"\" r} sprengstoff"

[STR_CARGO_UNIT_FERTILISER]
base = "{WEIGHT} gjødsel"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} fisk"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} kasse{P 0 \"\" r} gårdsutstyr"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} frukt"

[STR_CARGO_UNIT_KAOLIN]
base = "{WEIGHT} kaolin"

[STR_CARGO_UNIT_LIMESTONE]
base = "{WEIGHT} kalkstein"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} trelast"

[STR_CARGO_UNIT_LYE]
base = "{VOLUME} lut"

[STR_CARGO_UNIT_MANGANESE]
base = "{WEIGHT} mangan"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} melk"

[STR_CARGO_UNIT_NICKEL]
base = "{WEIGHT} nikkel"

[STR_CARGO_UNIT_NITRATES]
base = "{WEIGHT} nitrater"

[STR_CARGO_UNIT_NUTS]
base = "{SIGNED_WORD} sekk{P 0 \"\" er}  nøtter"

[STR_CARGO_UNIT_PEAT]
base = "{WEIGHT} torv"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} bensin"

[STR_CARGO_UNIT_PHOSPHATE]
base = "{WEIGHT} fosfat"

[STR_CARGO_UNIT_PIG_IRON]
base = "{WEIGHT} råjern"

[STR_CARGO_UNIT_POTASH]
base = "{WEIGHT} kalium"

[STR_CARGO_UNIT_PYRITE_ORE]
base = "{WEIGHT} pyrittmalm"

[STR_CARGO_UNIT_QUICKLIME]
base = "{WEIGHT} ulesket kalk"

[STR_CARGO_UNIT_SALT]
base = "{WEIGHT} salt"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} sand"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} skrapmetall"

[STR_CARGO_UNIT_SLAG]
base = "{WEIGHT} slagg"

[STR_CARGO_UNIT_SODA_ASH]
base = "{WEIGHT}  soda"

[STR_CARGO_UNIT_STEEL]
base = "{WEIGHT} stål"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} stein"

[STR_CARGO_UNIT_SULPHUR]
base = "{WEIGHT} svovel"

[STR_CARGO_UNIT_VEHICLE_BODIES]
base = "{WEIGHT} karosserier"

[STR_CARGO_UNIT_VEHICLE_PARTS]
base = "{WEIGHT} kjøretøydeler"

[STR_CARGO_UNIT_VEHICLES]
base = "{WEIGHT} kjøretøy"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} balle{P 0 \"\" r} ull"

[STR_CARGO_UNIT_ZINC]
base = "{WEIGHT} sink"

[STR_CID_ACID]
base = "{TINYFONT}AC"

[STR_CID_ALCOHOL]
base = "{TINYFONT}AL"

[STR_CID_BEANS]
base = "{TINYFONT}BN"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}BM"

[STR_CID_CASSAVA]
base = "{TINYFONT}CA"

[STR_CID_CEMENT]
base = "{TINYFONT}CE"

[STR_CID_CHEMICALS]
base = "{TINYFONT}CH"

[STR_CID_CHLORINE]
base = "{TINYFONT}CL"

[STR_CID_CLAY]
base = "{TINYFONT}CY"

[STR_CID_COFFEE]
base = "{TINYFONT}CF"

[STR_CID_COKE]
base = "{TINYFONT}CK"

[STR_CID_COPPER]
base = "{TINYFONT}CR"

[STR_CID_EDIBLE_OIL]
base = "{TINYFONT}EO"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}ES"

[STR_CID_EXPLOSIVES]
base = "{TINYFONT}EX"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}FS"

[STR_CID_FERTILISER]
base = "{TINYFONT}FL"

[STR_CID_FISH]
base = "{TINYFONT}FI"

[STR_CID_KAOLIN]
base = "{TINYFONT}KA"

[STR_CID_LIMESTONE]
base = "{TINYFONT}LS"

[STR_CID_TIMBER]
base = "{TINYFONT}LU"

[STR_CID_LYE]
base = "{TINYFONT}LY"

[STR_CID_MANGANESE]
base = "{TINYFONT}MN"

[STR_CID_MILK]
base = "{TINYFONT}MK"

[STR_CID_NICKEL]
base = "{TINYFONT}NK"

[STR_CID_NITRATES]
base = "{TINYFONT}NI"

[STR_CID_NUTS]
base = "{TINYFONT}NT"

[STR_CID_PEAT]
base = "{TINYFONT}PE"

[STR_CID_PETROL]
base = "{TINYFONT}PT"

[STR_CID_PIG_IRON]
base = "{TINYFONT}PI"

[STR_CID_PHOSPHATE]
base = "{TINYFONT}PH"

[STR_CID_POTASH]
base = "{TINYFONT}PA"

[STR_CID_PYRITE_ORE]
base = "{TINYFONT}PY"

[STR_CID_QUICKLIME]
base = "{TINYFONT}QL"

[STR_CID_SALT]
base = "{TINYFONT}NA"

[STR_CID_SAND]
base = "{TINYFONT}SA"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}SM"

[STR_CID_SLAG]
base = "{TINYFONT}SG"

[STR_CID_SODA_ASH]
base = "{TINYFONT}SO"

[STR_CID_STEEL]
base = "{TINYFONT}SL"

[STR_CID_AGGREGATES]
base = "{TINYFONT}ST"

[STR_CID_SULPHUR]
base = "{TINYFONT}SU"

[STR_CID_VEHICLE_BODIES]
base = "{TINYFONT}VB"

[STR_CID_VEHICLE_PARTS]
base = "{TINYFONT}VP"

[STR_CID_VEHICLES]
base = "{TINYFONT}VS"

[STR_CID_WOOL]
base = "{TINYFONT}WL"

[STR_CID_ZINC]
base = "{TINYFONT}ZN"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}FIRS er ikke laget for bruk i Lekeland"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "må plasseres under snøgrensa."

[STR_ERR_LOCATION_NOT_BELOW_SNOWLINE]
base = "må plasseres over snøgrensa."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "må plasseres på tørt land."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "kan ikke plasseres i ørken."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "kan ikke plasseres i bratte skråninger"

[STR_ERR_LOCATION_LIMIT_1_PER_TOWN]
base = "kun en industri av denne typen er tillatt pr. by."

[STR_IND_ALUMINIUM_PLANT]
base = "{G=neuter}Aluminiumsverk"

[STR_IND_AMMONIA_PLANT]
base = "{G=masculine}Ammoniakkfabrikk"

[STR_IND_ARABLE_FARM]
base = "{G=masculine}Jordbruksgård"

[STR_IND_ASSEMBLY_PLANT]
base = "{G=masculine}Kjøretøyfabrikk"

[STR_IND_BASIC_OXYGEN_FURNACE]
base = "{G=masculine}Enkel smelteovn"

[STR_IND_BIOREFINERY]
base = "{G=neuter}Bioraffineri"

[STR_IND_BLAST_FURNACE]
base = "{G=masculine}Blåseovn"

[STR_IND_BREWERY]
base = "{G=neuter}Bryggeri"

[STR_IND_CIDER_MILL]
base = "{G=neuter}Siderbryggeri"

[STR_IND_BRICK_WORKS]
base = "{G=neuter}Teglverk"

[STR_IND_BUILDERS_YARD]
base = "{G=masculine}Byggevareforretning"

[STR_IND_BULK_TERMINAL]
base = "{G=masculine}Bulkterminal"

[STR_IND_CEMENT_PLANT]
base = "{G=masculine}Sementfabrikk"

[STR_IND_CHEMICAL_PLANT]
base = "{G=masculine}Kjemisk fabrikk"

[STR_IND_CLAY_PIT]
base = "{G=feminine}Leirgruve"

[STR_IND_COFFEE_ESTATE]
base = "{G=masculine}Kaffeplantasje"

[STR_IND_COKE_OVEN]
base = "{G=masculine}Koksovn"

[STR_IND_COPPER_SMELTER]
base = "{G=neuter}Kobberraffineri"

[STR_IND_DAIRY]
base = "{G=neuter}Meieri"

[STR_IND_DAIRY_FARM]
base = "{G=masculine}Melkegård"

[STR_IND_DREDGING_SITE]
base = "{G=masculine}Mudderbanke"

[STR_IND_ELECTRIC_ARC_FURNACE]
base = "{G=masculine}Elektrobueovn"

[STR_IND_FISHING_GROUND]
base = "{G=masculine}Fiskebanke"

[STR_IND_FISHING_HARBOUR]
base = "{G=neuter}Fiskemottak"

[STR_IND_FISHING_VILLAGE]
base = "{G=masculine}Fiskerlandsby"

[STR_IND_FLOUR_MILL]
base = "{G=feminine}Mølle"

[STR_IND_FOOD_MARKET]
base = "{G=masculine}Matbutikk"

[STR_IND_FOOD_PROCESSOR]
base = "{G=masculine}Hermetikkfabrikk"

[STR_IND_FURNITURE_FACTORY]
base = "{G=masculine}Møbelfabrikk"

[STR_IND_GENERAL_STORE]
base = "{G=masculine}Landhandel"

[STR_IND_GLASS_WORKS]
base = "{G=neuter}Glassverk"

[STR_IND_HARDWARE_STORE]
base = "{G=masculine}Jernvarehandel"

[STR_IND_HOTEL]
base = "{G=neuter}Hotell"

[STR_IND_HERDING_COOP]
base = "{G=neuter}Utmarksbeite"

[STR_IND_SCRAP_YARD]
base = "{G=masculine}Skraphandel"

[STR_IND_LIME_KILN]
base = "{G=masculine}Kalkovn"

[STR_IND_LIMESTONE_MINE]
base = "{G=neuter}Kalkbrudd"

[STR_IND_LIQUIDS_TERMINAL]
base = "{G=masculine}Tankterminal"

[STR_IND_TIMBER_YARD]
base = "{G=masculine}Trevarefabrikk"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "{G=neuter}Mekanisk verksted"

[STR_IND_MANGANESE_MINE]
base = "{G=feminine}Mangangruve"

[STR_IND_MIXEDFARM]
base = "{G=masculine}Blandingsgård"

[STR_IND_NITRATE_MINE]
base = "{G=feminine}Nitratgruve"

[STR_IND_ORCHARD_PIGGERY]
base = "{G=masculine}Frukt- og grisegård"

[STR_IND_PEATLANDS]
base = "{G=feminine}Torvmyr"

[STR_IND_PETROLPUMP]
base = "{G=masculine}Bensinstasjon"

[STR_IND_PHOSPHATE_MINE]
base = "{G=feminine}Fosfatgruve"

[STR_IND_PLASTICS_PLANT]
base = "{G=masculine}Plastfabrikk"

[STR_IND_PORT]
base = "{G=feminine}Havn"

[STR_IND_POTASH_MINE]
base = "{G=feminine}Kaliumgruve"

[STR_IND_PYRITE_MINE]
base = "{G=feminine}Pyrittgruve"

[STR_IND_PYRITE_SMELTER]
base = "{G=neuter}Pyrittverk"

[STR_IND_POWER_PLANT]
base = "{G=neuter}Kraftverk"

[STR_IND_QUARRY]
base = "{G=neuter}Steinbrudd"

[STR_IND_RANCH]
base = "{G=masculine}Ranch"

[STR_IND_SHEEPFARM]
base = "{G=masculine}Sauegård"

[STR_IND_SLAG_GRINDING_PLANT]
base = "{G=neuter}Slaggknuseverk"

[STR_IND_SMITHY_FORGE]
base = "{G=feminine}Smie"

[STR_IND_SODA_ASH_MINE]
base = "{G=feminine}Natriumgruve"

[STR_IND_STOCKYARD]
base = "{G=neuter}Slakteri"

[STR_IND_SUGAR_REFINERY]
base = "{G=neuter}Sukkerraffineri"

[STR_IND_SUPPLY_YARD]
base = "{G=neuter}Utstyrslager"

[STR_IND_TEXTILE_MILL]
base = "{G=masculine}Tekstilfabrikk"

[STR_IND_TRADING_POST]
base = "{G=masculine}Handelsstasjon"

[STR_IND_TYRE_PLANT]
base = "{G=masculine}Dekkfabrikk"

[STR_IND_VINEYARD]
base = "{G=masculine}Vingård"

[STR_IND_WHARF]
base = "{G=masculine}Slipp"

[STR_CARGO_SUBTYPE_DISPLAY_CARGO_SUPPLIED_FLAG]
base = "{BLACK}(levert)"

[STR_EXTRA_TEXT_SECONDARY_NON_COMBINATORY]
base = "{BLACK}Produserer maksimalt hvis {WHITE}hvilken som helst {BLACK}nødvendig vare leveres."

[STR_PRIMARY_PRODUCTION_1X]
base = "{BLACK}Produserer nå: {YELLOW}Normal{}{}{BLACK}For {WHITE}Forbedret produksjon{BLACK} må du levere {SIGNED_WORD} kasser utstyr innen tre måneder.{}For {WHITE}Gung-ho {BLACK}produksjon lever {SIGNED_WORD} kasser."

[STR_PRIMARY_PRODUCTION_2X]
base = "{BLACK}Produserer nå: {YELLOW}Forbedret{}{}{BLACK}For å opprettholde dette nivået, lever {SIGNED_WORD} kasser utstyr innen tre måneder{}For {WHITE}Gung-ho {BLACK}produksjon lever {SIGNED_WORD} kasser."

[STR_PRIMARY_PRODUCTION_4X]
base = "{BLACK}Produserer nå: {YELLOW}Gung-ho{}{}{BLACK}For å opprettholde dette nivået, lever {SKIP}{SIGNED_WORD} kasser utstyr innen tre måneder."

[STR_PORT_PRODUCTION_1X]
base = "{BLACK}Produserer nå: {YELLOW}Normal{}{}{BLACK}For {WHITE}Forbedret {BLACK}produksjon må du levere {SIGNED_WORD} vareenheter innen tre måneder.{}For {WHITE}Gung-ho {BLACK}produksjon lever {SIGNED_WORD} vareenheter."

[STR_PORT_PRODUCTION_2X]
base = "{BLACK}Produserer nå: {YELLOW}Forbedret{}{}{BLACK}For å opprettholde dette nivået, lever {SIGNED_WORD} vareenheter innen tre måneder{}For {WHITE}Gung-ho {BLACK}produksjon lever {SIGNED_WORD} vareenheter."

[STR_PORT_PRODUCTION_4X]
base = "{BLACK}Produserer nå: {YELLOW}Gung-ho{}{}{BLACK}For å opprettholde dette nivået, lever {SKIP}{SIGNED_WORD} vareenheter innen tre måneder."

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Plassering: {YELLOW}Kan ikke startes i snø eller ørken."

[STR_FUND_COFFEE_ESTATE]
base = "{}{BLACK}Plassering: {YELLOW}Kan ikke startes i snø eller ørken."

[STR_FUND_DAIRY_FARM]
base = "{}{BLACK}Plassering: {YELLOW}Kan ikke startes i snø eller ørken."

[STR_FUND_FOREST]
base = "{}{BLACK}Plassering: {YELLOW}Kan ikke startes i ørken."

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Plassering: {YELLOW}Kan ikke startes i snø."

[STR_FUND_HERDING_COOP]
base = "{}{BLACK}Plassering: {YELLOW}Kan bare grunnlegges på snø."

[STR_FUND_ORCHARD_PIGGERY]
base = "{}{BLACK}Plassering: {YELLOW}Kan ikke startes i snø eller ørken."

[STR_FUND_RUBBER_PLANTATION]
base = "{}{BLACK}Plassering: {YELLOW}Kan ikke startes i snø eller ørken."

[STR_FUND_VINEYARD]
base = "{}{BLACK}Plassering: {YELLOW}Kan ikke startes i snø eller ørken."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}Tilgjengelig fra: {YELLOW}{COMMA}"

[STR_FUND_AVAILABLE_UNTIL]
base = "{}{BLACK}Ikke tilgjengelig etter: {YELLOW}{COMMA}"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING} {STRING}"

[STR_STATION_ANIMALS]
base = "Hestemarked"

[STR_STATION_AUTOMOTIVE]
base = "Kjøretøy"

[STR_STATION_BAR_GRILL_AND_ROOMS]
base = "Motell"

[STR_STATION_BARNS]
base = "Låver"

[STR_STATION_BARREL_AND_KEG]
base = "Tønner og kagger"

[STR_STATION_BASE]
base = "Base"

[STR_STATION_BONEYARD]
base = "Huggeri"

[STR_STATION_BANK_TOP]
base = "Grunne"

[STR_STATION_COLLIERY]
base = "Kullgruve"

[STR_STATION_COPPER_LODE]
base = "Kobberåre"

[STR_STATION_CREOSOTING]
base = "Kreosot"

[STR_STATION_DAIRY_LANE]
base = "Meierigate"

[STR_STATION_ESTATE]
base = "Plantasje"

[STR_STATION_FARM_1]
base = "Hovedgård"

[STR_STATION_FARM_2]
base = "Gårdsbruk"

[STR_STATION_FARM_3]
base = "Ranch"

[STR_STATION_FISHMARKET]
base = "Fiskemottak"

[STR_STATION_FOOD_CORPORATION]
base = "Fødevare"

[STR_STATION_FOREST]
base = "Tømmerdeponi"

[STR_STATION_FURNACE]
base = "Ovn"

[STR_STATION_HEAVY_INDUSTRY_2]
base = "Verk"

[STR_STATION_HERDING_COOP]
base = "Hytte"

[STR_STATION_INDUSTRY_ESTATE_1]
base = "Industripark"

[STR_STATION_INDUSTRY_HARBOUR_1]
base = "Industrihavn"

[STR_STATION_INDUSTRY_HARBOUR_2]
base = "Kai"

[STR_STATION_INDUSTRY_HARBOUR_3]
base = "Flytekai"

[STR_STATION_IRONSTONE]
base = "Jernmalm"

[STR_STATION_KILNS]
base = "Ovner"

[STR_STATION_KIMBERLITE_DEPOSITS]
base = "Kimberlittleie"

[STR_STATION_LIMESTONE_MINES]
base = "Kalkbrudd"

[STR_STATION_MANGANESE_MINES]
base = "Mangangruve"

[STR_STATION_MILL]
base = "Bruk"

[STR_STATION_MOULDINGS]
base = "Støperi"

[STR_STATION_OIL_RIG]
base = "Oljefelt"

[STR_STATION_ORCHARDS]
base = "Frukthage"

[STR_STATION_PIT]
base = "Grop"

[STR_STATION_PLANTATION]
base = "Plantasje"

[STR_STATION_POWERHUNGRY]
base = "Verk"

[STR_STATION_PUMPS]
base = "Pumper"

[STR_STATION_PYRITES]
base = "Pyrittåre"

[STR_STATION_REFINERY]
base = "Raffineri"

[STR_STATION_RUBBER_COMPANY]
base = "Gummifabrikk"

[STR_STATION_SALTPETER_WORKS]
base = "Salpeterverk"

[STR_STATION_SHARP_STREET]
base = "Industrivei"

[STR_STATION_SHEEP_FOLD]
base = "Sauekve"

[STR_STATION_SHOALS]
base = "Banke"

[STR_STATION_SILO]
base = "Silo"

[STR_STATION_SMELTER]
base = "Smelteverk"

[STR_STATION_SUGAR_COMPANY]
base = "Sukkerfabrikk"

[STR_STATION_TANK_FARM]
base = "Tankgård"

[STR_STATION_TAPPERS_SHED]
base = "Tapperi"

[STR_STATION_TOWN_1]
base = "Sentrum"

[STR_STATION_TOWN_3]
base = "Marked"

[STR_STATION_TRONA_BEDS]
base = "Natronleie"

[STR_STATION_WATER]
base = "Sandbanke"

[STR_STATION_WELLS]
base = "Brønner"

[STR_STATION_WINERY]
base = "Vingård"
