[GLOBAL_PRAGMA]
grflangid = "0x36"
plural = "0"
gender = "fp f m mp n"

[STR_GRF_DESC]
base = "{ORANGE}FIRS Industrial Replacement Set{}{BLACK}Trazido a você por andythenorth, FooBar, planetmaker, Terkhen and Yexo, com a ajuda de muitos outros. {SILVER}Veja o arquivo readme para mais informações, incluindo como usar o FIRS. {BLACK}Licença: GPL v2."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "A distância máxima da costa de zonas de pesca, plataformas de petróleo e campos de dragagem em blocos."

[STR_PARAM_DESC_ECONOMIES]
base = "Cada economia fornece uma combinação diferente de cargas e indústrias.{}{}Para os jogadores que querem uma jogabilidade simples, economias 'Básica' contém menos indústrias e cargas do que outras economias da FIRS."

[STR_PARAM_DESC_NO_OPENINGS]
base = "Por padrão, novas indústrias abrirão durante o jogo.{}{}Se 'impedir abertura' estiver habilitado, indústrias não abrirão durante o jogo e os jogadores não serão capazes de fundar ou prospectar indústrias."

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Distância máxima costeira das indústrias marinhas em blocos"

[STR_PARAM_NAME_ECONOMIES]
base = "Economia"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Impedir abertura de indústrias durante o jogo"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Sem limite"

[STR_PARAM_DESC_PRIMARY_LEVEL_REQUIREMENT]
base = "Quintas, minas e industrias similares aumentarão producão quando unidades de carga forem entregues, primeiro para {SILVER}Melhorado{BLACK}, e depois para {SILVER}Gung-ho{BLACK}, se as necessárias unidades forem entregues.{}{}Os valores padrão são bons, mas se necessário, podem aqui ser alterados .{}{}Os requerimentos para a carga para industrias do tipo porto serão 8x os valores aqui definidos."

[STR_PARAM_NAME_PRIMARY_LEVEL1_BONUS]
base = "Nível primário de produção Melhorado (%)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_BONUS]
base = "Nível primário de produção Gung-Ho (%)"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TEMPERATE]
base = "Economia Básica Clima Temperado"

[STR_PARAM_VALUE_ECONOMIES_BASIC_ARCTIC]
base = "Economia Básica Clima Ártico"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TROPIC]
base = "Economia Básica Clima Tropical"

[STR_PARAM_VALUE_ECONOMIES_IN_A_HOT_COUNTRY]
base = "Coração das Trevas"

[STR_CARGO_NAME_ALCOHOL]
base = "Álcool"

[STR_CARGO_NAME_BEANS]
base = "Feijões"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "Material de Construção"

[STR_CARGO_NAME_CASSAVA]
base = "Mandioca"

[STR_CARGO_NAME_CHEMICALS]
base = "Produtos Químicos"

[STR_CARGO_NAME_CLAY]
base = "Argila"

[STR_CARGO_NAME_COFFEE]
base = "Café"

[STR_CARGO_NAME_COPPER]
base = "Cobre"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "Peças"

[STR_CARGO_NAME_FISH]
base = "Peixe"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "Fertilizantes"

[STR_CARGO_NAME_FRUITS]
base = "Frutas"

[STR_CARGO_NAME_TIMBER]
base = "Madeira"

[STR_CARGO_NAME_MILK]
base = "Leite"

[STR_CARGO_NAME_NITRATES]
base = "Nitratos"

[STR_CARGO_NAME_PETROL]
base = "Gasolina"

[STR_CARGO_NAME_PIG_IRON]
base = "Liga de Ferro"

[STR_CARGO_NAME_POTASH]
base = "Potássio"

[STR_CARGO_NAME_PYRITE_ORE]
base = "Minério de pirite"

[STR_CARGO_NAME_QUICKLIME]
base = "Cal"

[STR_CARGO_NAME_SALT]
base = "Sal"

[STR_CARGO_NAME_SAND]
base = "Areia"

[STR_CARGO_NAME_SCRAP_METAL]
base = "Sucata"

[STR_CARGO_NAME_SODA_ASH]
base = "Carbonato de sódio"

[STR_CARGO_NAME_STEEL]
base = "Aço"

[STR_CARGO_NAME_AGGREGATES]
base = "Pedra"

[STR_CARGO_NAME_SULPHUR]
base = "Enxofre"

[STR_CARGO_NAME_VEHICLE_PARTS]
base = "Peças de veículos"

[STR_CARGO_NAME_WOOL]
base = "Lã"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} de álcool"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} de materias de construção"

[STR_CARGO_UNIT_CASSAVA]
base = "{WEIGHT} de mandioca"

[STR_CARGO_UNIT_CEMENT]
base = "{WEIGHT} de cimento"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} de produtos químicos"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} de argila"

[STR_CARGO_UNIT_COFFEE]
base = "{SIGNED_WORD} saco{P 0 \"\" s} de café"

[STR_CARGO_UNIT_EDIBLE_OIL]
base = "{VOLUME} de óleo alimentar"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} caixa{P 0 \"\" s} de peças"

[STR_CARGO_UNIT_FERTILISER]
base = "{WEIGHT} de fertilizante"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} de peixe"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} caixa{P 0 \"\" s} de fertilizante"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} de fruta"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} de madeira"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} de leite"

[STR_CARGO_UNIT_NITRATES]
base = "{WEIGHT} de nitratos"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} de gasolina"

[STR_CARGO_UNIT_PHOSPHATE]
base = "{WEIGHT} de fosfato"

[STR_CARGO_UNIT_PIG_IRON]
base = "{WEIGHT} de liga de ferro"

[STR_CARGO_UNIT_PYRITE_ORE]
base = "{WEIGHT} de minério de pirite"

[STR_CARGO_UNIT_SALT]
base = "{WEIGHT} de sal"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} de areia"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} de sucata"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} de pedra"

[STR_CARGO_UNIT_VEHICLES]
base = "{WEIGHT} de veículos"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} fardo{P 0 \"\" s} de lã"

[STR_CID_ACID]
base = "{TINYFONT}AC"

[STR_CID_ALCOHOL]
base = "{TINYFONT}AL"

[STR_CID_BEANS]
base = "{TINYFONT}BN"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}MC"

[STR_CID_CASSAVA]
base = "{TINYFONT}CA"

[STR_CID_CHEMICALS]
base = "{TINYFONT}PQ"

[STR_CID_CLAY]
base = "{TINYFONT}AG"

[STR_CID_COFFEE]
base = "{TINYFONT}CF"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}PÇ"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}FE"

[STR_CID_FISH]
base = "{TINYFONT}PX"

[STR_CID_TIMBER]
base = "{TINYFONT}MA"

[STR_CID_MANGANESE]
base = "{TINYFONT}MN"

[STR_CID_MILK]
base = "{TINYFONT}LE"

[STR_CID_NITRATES]
base = "{TINYFONT}NI"

[STR_CID_NUTS]
base = "{TINYFONT}NT"

[STR_CID_PETROL]
base = "{TINYFONT}GA"

[STR_CID_PYRITE_ORE]
base = "{TINYFONT}PY"

[STR_CID_QUICKLIME]
base = "{TINYFONT}QL"

[STR_CID_SALT]
base = "{TINYFONT}NA"

[STR_CID_SAND]
base = "{TINYFONT}AR"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}SU"

[STR_CID_SLAG]
base = "{TINYFONT}SG"

[STR_CID_AGGREGATES]
base = "{TINYFONT}PE"

[STR_CID_VEHICLE_BODIES]
base = "{TINYFONT}VB"

[STR_CID_VEHICLES]
base = "{TINYFONT}VS"

[STR_CID_WOOL]
base = "{TINYFONT}LÃ"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}FIRS não se destina a ser usado no clima Toyland"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "deve ser colocado abaixo do nível da neve."

[STR_ERR_LOCATION_NOT_BELOW_SNOWLINE]
base = "Deve ser colocado acima da linha de neve."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "deve ser colocado em terra seca."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "deve ser colocado no deserto."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "não pode ser colocado em encostas íngremes."

[STR_ERR_LOCATION_LIMIT_1_PER_TOWN]
base = "Apenas uma indústria deste tipo permitida por cidade."

[STR_IND_ALUMINIUM_PLANT]
base = "Fábrica de Alumínio"

[STR_IND_ARABLE_FARM]
base = "Plantação"

[STR_IND_ASSEMBLY_PLANT]
base = "Oficina de Montagem"

[STR_IND_BIOREFINERY]
base = "Biorefinaria"

[STR_IND_BREWERY]
base = "Destilaria"

[STR_IND_CIDER_MILL]
base = "Destilaria de Cidra"

[STR_IND_BRICK_WORKS]
base = "Olaria"

[STR_IND_BUILDERS_YARD]
base = "Canteiro de Obras"

[STR_IND_BULK_TERMINAL]
base = "Terminal de Granéis"

[STR_IND_CEMENT_PLANT]
base = "Fábrica de Cimento"

[STR_IND_CLAY_PIT]
base = "Poço de Argila"

[STR_IND_COFFEE_ESTATE]
base = "Fazenda de Café"

[STR_IND_COPPER_SMELTER]
base = "Refinaria de Cobre"

[STR_IND_DAIRY]
base = "Leitaria"

[STR_IND_DAIRY_FARM]
base = "Quinta de Gado Leiteiro"

[STR_IND_DREDGING_SITE]
base = "Campo de Dragagem"

[STR_IND_FISHING_GROUND]
base = "Zona de Pesca"

[STR_IND_FISHING_HARBOUR]
base = "Atracadouro de Pesca"

[STR_IND_FISHING_VILLAGE]
base = "Vila De Pesca"

[STR_IND_FOOD_MARKET]
base = "Mercearia"

[STR_IND_FURNITURE_FACTORY]
base = "Marcenaria"

[STR_IND_GENERAL_STORE]
base = "Armazém Geral"

[STR_IND_GLASS_WORKS]
base = "Vidreira"

[STR_IND_HARDWARE_STORE]
base = "Loja de Materias de Construção"

[STR_IND_HOTEL]
base = "Hotel"

[STR_IND_IRON_WORKS]
base = "Siderúrgica"

[STR_IND_SCRAP_YARD]
base = "Ferro Velho"

[STR_IND_LIME_KILN]
base = "Usina de Cal"

[STR_IND_LIMESTONE_MINE]
base = "Mina de Calcário"

[STR_IND_LIQUIDS_TERMINAL]
base = "Terminal de Líquidos"

[STR_IND_TIMBER_YARD]
base = "Madeireira"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "Fábrica de Ferramentas"

[STR_IND_MIXEDFARM]
base = "Fazenda Mesclada"

[STR_IND_ORCHARD_PIGGERY]
base = "Pomares e Suinicultura"

[STR_IND_PETROLPUMP]
base = "Posto de Gasolina"

[STR_IND_PLASTICS_PLANT]
base = "Fabrica de Plastico"

[STR_IND_PORT]
base = "Porto"

[STR_IND_POTASH_MINE]
base = "Mina de Potássio"

[STR_IND_PYRITE_SMELTER]
base = "Fundição de Pirite"

[STR_IND_QUARRY]
base = "Pedreira"

[STR_IND_RANCH]
base = "Rancho"

[STR_IND_RECYCLING_DEPOT]
base = "Depósito de Materias Recicláveis"

[STR_IND_RECYCLING_PLANT]
base = "Fábrica de Materias Recicláveis"

[STR_IND_SHEEPFARM]
base = "Fazenda de Ovelhas"

[STR_IND_SMITHY_FORGE]
base = "Serralheria"

[STR_IND_STOCKYARD]
base = "Matadouro"

[STR_IND_SUGAR_REFINERY]
base = "Refinaria de Açúcar"

[STR_IND_SUPPLY_YARD]
base = "Pátio de Suprimento"

[STR_IND_TEXTILE_MILL]
base = "Indústria Têxtil"

[STR_IND_TRADING_POST]
base = "Entreposto Comercial"

[STR_CARGO_SUBTYPE_DISPLAY_CARGO_SUPPLIED_FLAG]
base = "{BLACK}(fornecido)"

[STR_PRIMARY_PRODUCTION_1X]
base = "{BLACK}Produção atual: {YELLOW}Normal{}{}{BLACK}Para duplicar a produção entregar {SIGNED_WORD} unidades de carga dentro de três meses (ou {SIGNED_WORD} unidades de carga para quadruplicar a produção)"

[STR_PRIMARY_PRODUCTION_2X]
base = "{BLACK}Produção atual: {YELLOW}Aprimorado (duplica){}{}{BLACK}Para manter este nível, entregar {SIGNED_WORD} unidades de carga dentro de três meses, ou {SIGNED_WORD} unidades de carga para quadruplicar a produção"

[STR_PRIMARY_PRODUCTION_4X]
base = "{BLACK}Produção atual: {YELLOW}dedicado (quadriplica){}{}{BLACK}Para manter este nível, entregue {SKIP}{SIGNED_WORD} caixas de suprimentos dentro de três meses"

[STR_PORT_PRODUCTION_1X]
base = "{BLACK}Produção actual: {YELLOW}Normal{}{}{BLACK}Para dobrar a produção entregar {SIGNED_WORD} unidades de carga dentro de três meses{}Para quadruplicar a produção entregar{SIGNED_WORD} unidades de carga dentro de três meses"

[STR_PORT_PRODUCTION_2X]
base = "{BLACK}Produção actual: {YELLOW}Aprimorado (duplica){}{}{BLACK}Para manter este nível, entregar {SIGNED_WORD} unidades de carga dentro de três meses, ou {SIGNED_WORD} unidades de carga quadruplicar a produção"

[STR_PORT_PRODUCTION_4X]
base = "{BLACK}Produção actual: {YELLOW}Zeloso (quadriplica){}{}{BLACK}Para manter este nível, entregar {SKIP}{SIGNED_WORD} unidades de carga dentro de três meses"

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Localização: {YELLOW}Não pode ser fundado na neve ou no deserto."

[STR_FUND_COFFEE_ESTATE]
base = "{}{BLACK}Localização: {YELLOW}Não pode ser fundado na neve ou no deserto."

[STR_FUND_FOREST]
base = "{}{BLACK}Localização: {YELLOW}Não pode ser fundado no deserto."

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Localização: {YELLOW}Não pode ser fundado na neve."

[STR_FUND_ORCHARD_PIGGERY]
base = "{}{BLACK}Localização: {YELLOW}Não pode ser fundado na neve ou no deserto."

[STR_FUND_RUBBER_PLANTATION]
base = "{}{BLACK}Localização: {YELLOW}Não pode ser fundado na neve ou no deserto."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}Disponível a partir de: {YELLOW}{COMMA}"

[STR_FUND_AVAILABLE_UNTIL]
base = "{}{BLACK}Não disponível depois de: {YELLOW}{COMMA}"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING} {STRING}"

[STR_STATION_ANIMALS]
base = "Mercado de Cavalos"

[STR_STATION_AUTOMOTIVE]
base = "Automotivo"

[STR_STATION_BARNS]
base = "Celeiros"

[STR_STATION_CASTINGS]
base = "Moldes"

[STR_STATION_CREOSOTING]
base = "Creosotagem"

[STR_STATION_ESTATE]
base = "Estado"

[STR_STATION_EXCHANGE]
base = "Troca"

[STR_STATION_FARM_1]
base = "Solar"

[STR_STATION_FARM_3]
base = "Rancho"

[STR_STATION_FISHMARKET]
base = "Mercado de Pesca"

[STR_STATION_FOOD_CORPORATION]
base = "Corporação Alimentar"

[STR_STATION_HEAVY_INDUSTRY_2]
base = "Oficinas"

[STR_STATION_INDUSTRY_ESTATE_1]
base = "Parque Industrial"

[STR_STATION_INDUSTRY_HARBOUR_1]
base = "Porto Industrial"

[STR_STATION_IRONSTONE]
base = "Pedra de Ferro"

[STR_STATION_KIMBERLITE_DEPOSITS]
base = "Depósitos de Kimberlite"

[STR_STATION_LIMESTONE_MINES]
base = "Minas de calcário"

[STR_STATION_MARKET]
base = "Mercado"

[STR_STATION_MILL]
base = "Moinho/Fábrica"

[STR_STATION_MINE]
base = "Estrada Tanner"

[STR_STATION_PIT]
base = "Escavação"

[STR_STATION_PLANTATION]
base = "Plantação"

[STR_STATION_POWERHUNGRY]
base = "Central de Energia"

[STR_STATION_PUMPS]
base = "Bombas"

[STR_STATION_PYRITES]
base = "Depósitos de Pirite"

[STR_STATION_REFINERY]
base = "Portland"

[STR_STATION_RUBBER_COMPANY]
base = "Empresa de borracha"

[STR_STATION_SALTPETER_WORKS]
base = "Refinarias de Sal"

[STR_STATION_SHARP_STREET]
base = "Rua Sharp"

[STR_STATION_SHEEP_FOLD]
base = "Curral de Ovelhas"

[STR_STATION_SMELTER]
base = "Fundição"

[STR_STATION_SUGAR_COMPANY]
base = "Companhia de Açucar"

[STR_STATION_TANK_FARM]
base = "Parque de Armazenagem"

[STR_STATION_TOWN_1]
base = "Câmara Municipal antiga"

[STR_STATION_WATER]
base = "Banco de Areia"

[STR_STATION_WINERY]
base = "Adega"
