[GLOBAL_PRAGMA]
grflangid = "0x07"
plural = "6"
gender = "m f n p"
case = "abl acc dat f gen m n nom p pre"

[STR_GRF_DESC]
base = "{ORANGE}Набор FIRS для полной замены предприятий{}{BLACK}Специально для вас от andythenorth, FooBar, planetmaker, Terkhen и Yexo, с помощью многих других. {SILVER}Подробную информацию, включая как пользоваться FIRS, найдёте в инструкции. {BLACK}Лицензия: GPL v2."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Максимальная удалённость местоположения рыболовных промыслов, нефтянных вышек и участков углубления дна от побережья в клетках."

[STR_PARAM_DESC_ECONOMIES]
base = "Грузы и предприятия различны в каждой экономике.{}{}Тарифы на оплату перевозки в каждой экономике также отличаются. Для игроков желающих играть в упрощенный вариант, 'Простая' экономика содержит меньше грузов и предприятий чем другие FIRS экономики."

[STR_PARAM_DESC_NO_OPENINGS]
base = "Без создания новых предприятий во время игры.{}Игроки не смогут профинансировать или разведать предприятия.{}Предприятия будут созданы в начале игры при создании мира (в зависимости от использованных настроек)."

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Макс. удалённость предприятий на море от побережья в клетках"

[STR_PARAM_NAME_ECONOMIES]
base = "Экономика"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Запретить создание предприятий во время игры"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "без ограничений"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TEMPERATE]
base = "Умеренная Простая"

[STR_PARAM_VALUE_ECONOMIES_BASIC_ARCTIC]
base = "Арктическая Простая"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TROPIC]
base = "Тропическая Простая"

[STR_PARAM_VALUE_ECONOMIES_IN_A_HOT_COUNTRY]
base = "Сердце Тьмы"

[STR_CARGO_NAME_ALCOHOL]
base = "{G=n}Спиртное"

["STR_CARGO_NAME_ALCOHOL.acc"]
base = "спиртное"

["STR_CARGO_NAME_ALCOHOL.gen"]
base = "спиртного"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "{G=p}Стройматериалы"

["STR_CARGO_NAME_BUILDING_MATERIALS.acc"]
base = "стройматериалы"

["STR_CARGO_NAME_BUILDING_MATERIALS.gen"]
base = "стройматериалов"

[STR_CARGO_NAME_CEMENT]
base = "Цемент"

[STR_CARGO_NAME_CHEMICALS]
base = "{G=p}Химикаты"

["STR_CARGO_NAME_CHEMICALS.acc"]
base = "химикаты"

["STR_CARGO_NAME_CHEMICALS.gen"]
base = "химикатов"

[STR_CARGO_NAME_CLAY]
base = "{G=f}Глина"

["STR_CARGO_NAME_CLAY.acc"]
base = "глину"

["STR_CARGO_NAME_CLAY.gen"]
base = "глины"

[STR_CARGO_NAME_COFFEE]
base = "{G=m}Кофе"

["STR_CARGO_NAME_COFFEE.acc"]
base = "Кофе"

["STR_CARGO_NAME_COFFEE.gen"]
base = "Кофе"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "{G=n}Оборудование"

["STR_CARGO_NAME_ENGINEERING_SUPPLIES.acc"]
base = "оборудование"

["STR_CARGO_NAME_ENGINEERING_SUPPLIES.gen"]
base = "оборудования"

[STR_CARGO_NAME_FISH]
base = "{G=f}Рыба"

["STR_CARGO_NAME_FISH.acc"]
base = "рыбу"

["STR_CARGO_NAME_FISH.gen"]
base = "рыбы"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "{G=p}Агротехсредства"

["STR_CARGO_NAME_FARM_SUPPLIES.acc"]
base = "агротехсредства"

["STR_CARGO_NAME_FARM_SUPPLIES.gen"]
base = "агротехсредств"

[STR_CARGO_NAME_FRUITS]
base = "{G=p}Фрукты"

["STR_CARGO_NAME_FRUITS.acc"]
base = "фрукты"

["STR_CARGO_NAME_FRUITS.gen"]
base = "фруктов"

[STR_CARGO_NAME_TIMBER]
base = "{G=p}Лесоматериалы"

["STR_CARGO_NAME_TIMBER.acc"]
base = "лесоматериалы"

["STR_CARGO_NAME_TIMBER.gen"]
base = "лесоматериалов"

[STR_CARGO_NAME_MILK]
base = "{G=n}Молоко"

["STR_CARGO_NAME_MILK.acc"]
base = "молоко"

["STR_CARGO_NAME_MILK.gen"]
base = "молока"

[STR_CARGO_NAME_PETROL]
base = "{G=m}Бензин"

["STR_CARGO_NAME_PETROL.acc"]
base = "бензин"

["STR_CARGO_NAME_PETROL.gen"]
base = "бензина"

[STR_CARGO_NAME_SAND]
base = "{G=m}Песок"

["STR_CARGO_NAME_SAND.acc"]
base = "песок"

["STR_CARGO_NAME_SAND.gen"]
base = "песка"

[STR_CARGO_NAME_SCRAP_METAL]
base = "{G=m}Металлолом"

["STR_CARGO_NAME_SCRAP_METAL.acc"]
base = "металлолом"

["STR_CARGO_NAME_SCRAP_METAL.gen"]
base = "металлолома"

[STR_CARGO_NAME_AGGREGATES]
base = "{G=m}Известняк"

[STR_CARGO_NAME_WOOL]
base = "{G=f}Шерсть"

["STR_CARGO_NAME_WOOL.acc"]
base = "шерсть"

["STR_CARGO_NAME_WOOL.gen"]
base = "шерсти"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} спиртного"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} стройматериалов"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} химикатов"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} глины"

[STR_CARGO_UNIT_COFFEE]
base = "{SIGNED_WORD} меш{P 0 ок ка ков} кофе"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} единиц{P 0 а ы \"\"} оборудования"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} рыбы"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} ящик{P 0 \"\" а ов} агротехсредств"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} фруктов"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} лесоматериалов"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} молока"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} бензина"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} песка"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} металлолома"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} известняка"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} тюк{P 0 \"\" а ов} шерсти"

[STR_CID_ALCOHOL]
base = "{TINYFONT}СП"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}СМ"

[STR_CID_CHEMICALS]
base = "{TINYFONT}ХИ"

[STR_CID_CLAY]
base = "{TINYFONT}ГЛ"

[STR_CID_COFFEE]
base = "{TINYFONT}КФ"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}ОБ"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}АГ"

[STR_CID_FISH]
base = "{TINYFONT}РЫ"

[STR_CID_TIMBER]
base = "{TINYFONT}ПМ"

[STR_CID_MILK]
base = "{TINYFONT}МО"

[STR_CID_PETROL]
base = "{TINYFONT}БЕ"

[STR_CID_SAND]
base = "{TINYFONT}ПЕ"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}МЛ"

[STR_CID_AGGREGATES]
base = "{TINYFONT}ИЗ"

[STR_CID_WOOL]
base = "{TINYFONT}ШЕ"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "должно находиться ниже снеговой линии."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "должно находиться на суше."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "не должно находиться в пустыне."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "не может находиться на крутых склонах."

[STR_ERR_LOCATION_LIMIT_1_PER_TOWN]
base = "разрешено только одно предприятие такого типа на город."

[STR_IND_ALUMINIUM_PLANT]
base = "{G=m}Алюминиевый завод"

["STR_IND_ALUMINIUM_PLANT.gen"]
base = "алюминиевого завода"

[STR_IND_ARABLE_FARM]
base = "{G=n}Земледельческое хозяйство"

["STR_IND_ARABLE_FARM.gen"]
base = "земледельческого хозяйства"

[STR_IND_BREWERY]
base = "{G=m}Пивоваренный завод"

["STR_IND_BREWERY.gen"]
base = "пивоваренного завода"

[STR_IND_CIDER_MILL]
base = "{G=f}Пивоварня"

[STR_IND_BRICK_WORKS]
base = "{G=m}Кирпичный завод"

["STR_IND_BRICK_WORKS.gen"]
base = "кирпичного завода"

[STR_IND_BUILDERS_YARD]
base = "{G=m}Склад стройматериалов"

["STR_IND_BUILDERS_YARD.gen"]
base = "склада стройматериалов"

[STR_IND_BULK_TERMINAL]
base = "Портовый Грузовой Терминал"

[STR_IND_CEMENT_PLANT]
base = "{G=m}Цементный завод"

["STR_IND_CEMENT_PLANT.gen"]
base = "цементного завода"

[STR_IND_CLAY_PIT]
base = "{G=m}Глиняный карьер"

["STR_IND_CLAY_PIT.gen"]
base = "глиняного карьера"

[STR_IND_COFFEE_ESTATE]
base = "{G=f}Кофейная плантация"

[STR_IND_DAIRY]
base = "{G=m}Молокозавод"

["STR_IND_DAIRY.gen"]
base = "молокозавода"

[STR_IND_DREDGING_SITE]
base = "{G=m}Участок углубления дна"

["STR_IND_DREDGING_SITE.gen"]
base = "участка углубления дна"

[STR_IND_FISHING_GROUND]
base = "{G=m}Рыболовный промысел"

["STR_IND_FISHING_GROUND.gen"]
base = "рыболовного промысла"

[STR_IND_FISHING_HARBOUR]
base = "{G=m}Рыболовный порт"

["STR_IND_FISHING_HARBOUR.gen"]
base = "рыболовного порта"

[STR_IND_FURNITURE_FACTORY]
base = "{G=f}Мебельная фабрика"

["STR_IND_FURNITURE_FACTORY.gen"]
base = "мебельной фабрики"

[STR_IND_GENERAL_STORE]
base = "{G=m}Магазин"

[STR_IND_GLASS_WORKS]
base = "{G=m}Стекольный завод"

["STR_IND_GLASS_WORKS.gen"]
base = "стекольного завода"

[STR_IND_HARDWARE_STORE]
base = "{G=m}Хозяйственный магазин"

["STR_IND_HARDWARE_STORE.gen"]
base = "хозяйственного магазина"

[STR_IND_HOTEL]
base = "{G=f}Гостинница"

["STR_IND_HOTEL.gen"]
base = "гостинницы"

[STR_IND_SCRAP_YARD]
base = "{G=f}Свалка"

["STR_IND_SCRAP_YARD.gen"]
base = "свалки"

[STR_IND_LIME_KILN]
base = "{G=m}Известковый завод"

["STR_IND_LIME_KILN.gen"]
base = "известкового завода"

[STR_IND_TIMBER_YARD]
base = "{G=m}Склад лесоматериалов"

["STR_IND_TIMBER_YARD.gen"]
base = "склада лесоматериалов"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "{G=m}Механический завод"

["STR_IND_TRACKED_MACHINE_FACTORY.gen"]
base = "механического завода"

[STR_IND_ORCHARD_PIGGERY]
base = "Сады и Скотный Двор"

[STR_IND_PETROLPUMP]
base = "{G=f}Заправочная станция"

["STR_IND_PETROLPUMP.gen"]
base = "заправочной станции"

[STR_IND_PLASTICS_PLANT]
base = "{G=m}Пластмассовый завод"

["STR_IND_PLASTICS_PLANT.gen"]
base = "пластмассового завода"

[STR_IND_PORT]
base = "Порт"

[STR_IND_QUARRY]
base = "{G=m}Карьер"

["STR_IND_QUARRY.gen"]
base = "карьера"

[STR_IND_RANCH]
base = "{G=n}Животноводческое хозяйство"

[STR_IND_SHEEPFARM]
base = "{G=n}Овцеводческое хозяйство"

["STR_IND_SHEEPFARM.gen"]
base = "овцеводческого хозяйства"

[STR_IND_SMITHY_FORGE]
base = "{G=f}Мастерская"

["STR_IND_SMITHY_FORGE.gen"]
base = "мастерской"

[STR_IND_STOCKYARD]
base = "{G=m}Мясокомбинат"

["STR_IND_STOCKYARD.gen"]
base = "скотобойни"

[STR_IND_SUGAR_REFINERY]
base = "{G=m}Сахарный завод"

["STR_IND_SUGAR_REFINERY.gen"]
base = "сахарного завода"

[STR_IND_TEXTILE_MILL]
base = "{G=f}Текстильная фабрика"

["STR_IND_TEXTILE_MILL.gen"]
base = "текстильной фабрики"

[STR_IND_TRADING_POST]
base = "Торговый Причал"

[STR_PRIMARY_PRODUCTION_1X]
base = "{BLACK}Уровень производства: {YELLOW}Нормальный{}{}{BLACK}Доставка {SIGNED_WORD} ящик{P \"\" а ов} материалов в течении трех месяцев удвоит производство (или {SIGNED_WORD} ящик{P \"\" а ов} для учетверения производства)"

[STR_PRIMARY_PRODUCTION_2X]
base = "{BLACK}Уровень производства: {YELLOW}Улучшеный (удвоеный){}{}{BLACK}Для поддержки данного уровня доставте {SIGNED_WORD} ящик{P \"\" а ов} материалов в течении трех месяцев, или {SIGNED_WORD} ящик{P \"\" а ов} для учетверения производства"

[STR_PRIMARY_PRODUCTION_4X]
base = "{BLACK}Уровень производства: {YELLOW}Лучший (учетвененный){}{}{BLACK}Для поддержки данного уровня доставте {SKIP}{SIGNED_WORD} ящик{P \"\" а ов} материалов в течении трех месяцев"

[STR_PORT_PRODUCTION_1X]
base = "{BLACK}Уровень производства: {YELLOW}Нормальный{}{}{BLACK}Доставка {SIGNED_WORD} ящик{P 0 \"\" а ов} материалов в течении трех месяцев удвоит производство (или {SIGNED_WORD} ящик{P 0 \"\" а ов} для учетверения производства)"

[STR_PORT_PRODUCTION_2X]
base = "{BLACK}Уровень производства: {YELLOW}Улучшеный (удвоеный){}{}{BLACK}Для поддержки данного уровня доставте {SIGNED_WORD} ящик{P \"\" а ов} материалов в течении трех месяцев, или {SIGNED_WORD} ящик{P \"\" а ов} для учетверения производства"

[STR_PORT_PRODUCTION_4X]
base = "{BLACK}Уровень производства: {YELLOW}Лучший (учетверенный){}{}{BLACK}Для поддержки данного уровня доставьте {SKIP}{SIGNED_WORD} ящик{P \"\" а ов} материалов в течение трех месяцев"

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Положение: {YELLOW}Нельзя разместить на снегу или в пустыне."

[STR_FUND_COFFEE_ESTATE]
base = "{}{BLACK}Местность: {YELLOW}Не может быть построена на снегу или в пустыне."

[STR_FUND_FOREST]
base = "{}{BLACK}Положение: {YELLOW}Нельзя разместить в пустыне."

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Положение: {YELLOW}Нельзя разместить на снегу."

[STR_FUND_ORCHARD_PIGGERY]
base = "{}{BLACK}Местность: {YELLOW}Не может быть построен на снегу или в пустыне."

[STR_FUND_RUBBER_PLANTATION]
base = "{}{BLACK}Местность: {YELLOW}Не может быть построено на снегу или в пустыне."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}Доступно с: {YELLOW}{COMMA}"

[STR_FUND_AVAILABLE_UNTIL]
base = "{}{BLACK}Недоступно после: {YELLOW}{COMMA}"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING} {STRING}"

[STR_STATION_ANIMALS]
base = "{G=m}Лошадиный рынок"

[STR_STATION_FARM_1]
base = "{G=f}Усадьба"

[STR_STATION_FISHMARKET]
base = "{G=m}Рыбный рынок"

[STR_STATION_INDUSTRY_ESTATE_1]
base = "Промзона"

[STR_STATION_INDUSTRY_HARBOUR_1]
base = "Грузовой причал"

[STR_STATION_MILL]
base = "Мельница"

[STR_STATION_PIT]
base = "Впадина"

[STR_STATION_PLANTATION]
base = "Плантация"

[STR_STATION_POWERHUNGRY]
base = "Электростанция"

[STR_STATION_REFINERY]
base = "{G=f}Нефтяная"

[STR_STATION_TOWN_1]
base = "Старый Город"

[STR_STATION_WATER]
base = "{G=f}Песчаная Набережная"
