[GLOBAL_PRAGMA]
grflangid = "0x0d"
plural = "6"
gender = "muški ženski srednji"
case = "nom big aku vok dat lok ins gen"

[STR_GRF_DESC]
base = "{ORANGE}FIRS Zamenski Skup Industrija{}{BLACK}Kreirali {SILVER}andythenorth{BLACK} i {SILVER}FooBar{BLACK}.{}{BLACK}'sa 1,000 i više izmena...'{BLACK}{}{}Internet stranica: {SILVER}www.tt-foundry.com/sets/FIRS{BLACK}.Licenca: {SILVER}GPL v2{BLACK}.Posebne zahvalnice za {SILVER}Ammler{BLACK}, {SILVER}Core Xii{BLACK}, {SILVER}Irwe{BLACK}, {SILVER}planetmaker{BLACK} and {SILVER}Zephyris{BLACK}.Koristi delove {SILVER}eGRVTS{BLACK}, {SILVER}ISR{BLACK} i {SILVER}OpenGFX{BLACK}."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Najveća udaljenost ribarskih lovišta i iskopa od obale mereno u pločicama"

[STR_PARAM_DESC_ECONOMIES]
base = "Svaka ekonomija nudi različite kombinacije tovara i industrija.{}{}Za igrače koji žele jednostavniju igru, {SILVER}bazične{BLACK} ekonomije sadrže manji broj industrija i tovara od ostalih FIRS ekonomija.{}{} FIRS vebsajt pruža detaljne informacije o svakoj ekonomiji."

[STR_PARAM_DESC_NO_OPENINGS]
base = "Po podrazumevanoj vrednosti, nove industrije biti će otvarane za vreme igre.{}{}Ako {SILVER} je uključeno {BLACK} \"zabrani otvaranje\", industrije neće biti otvarane za vreme igre, i igrači neće biti u mogućnosti finansirati otvaranje ili istraživanje nove industrije"

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Najveća udaljenost fabrika na vodi od obale"

[STR_PARAM_NAME_ECONOMIES]
base = "Ekonomija"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Zabranjena izgradnja fabrika (nedovršeno)"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Bez ograničenja"

[STR_PARAM_NAME_PRIMARY_LEVEL1_REQUIREMENT]
base = "Količina sanduka tovara potrebnih za povećanje nivoa proizvodnje na \"poboljšani\" (zadana vrednost = 16)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_REQUIREMENT]
base = "Količina sanduka tovara potrebnih za povećanje nivoa proizvodnje na \"masovni\" (zadana vrednost = 80)"

[STR_PARAM_DESC_PRIMARY_LEVEL_REQUIREMENT]
base = "Farme, rudnici i slične industrije povećavaju nivo proizvodnje kada se isporučuju sanduci proizvodnog materijala, najpre na {SILVER}poboljšani {BLACK} nivo, a zatim na {SILVER}masovni nivo, ako je isporučeno dovoljno sanduka.{}{} Zadane vrednosti su dovoljno dobre, međutim ako trebate, možete da ih promenite ovde.{}{} Ovo podešavanje ne utiče na industrije u lukama."

[STR_PARAM_NAME_PRIMARY_LEVEL1_BONUS]
base = "\"Poboljšani\" nivo proizvodnje (%)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_BONUS]
base = "\"Masovni\" nivo proizvodnje (%)"

[STR_PARAM_DESC_PRIMARY_LEVEL_BONUS]
base = "Proizvodnja na farmama, u rudnicima i sličnim industrijama kada su potrebe isporuke zadovoljene (kao procenat{SILVER} Normalnog {BLACK} nivoa proizvodnje)."

[STR_PARAM_VALUE_ECONOMIES_BASIC_TEMPERATE]
base = "Bazična - Umerena klima"

[STR_PARAM_VALUE_ECONOMIES_BASIC_ARCTIC]
base = "Bazična - Arktička klima"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TROPIC]
base = "Bazična - Tropska klima"

[STR_PARAM_VALUE_ECONOMIES_IN_A_HOT_COUNTRY]
base = "U vrućoj državi"

[STR_CARGO_NAME_ALCOHOL]
base = "{G=muški}alkohol"

[STR_CARGO_NAME_BEANS]
base = "Pasulj"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "{G=muški}građevinski materijali"

[STR_CARGO_NAME_CASSAVA]
base = "Maniok"

[STR_CARGO_NAME_CHEMICALS]
base = "{G=muški}hemijski proizvodi"

[STR_CARGO_NAME_CLAY]
base = "{G=ženski}glina"

[STR_CARGO_NAME_COFFEE]
base = "Kafa"

[STR_CARGO_NAME_COPPER]
base = "{G=muški}Bakar"

[STR_CARGO_NAME_EDIBLE_OIL]
base = "Jestivo ulje"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "{G=ženski}tehnička oprema"

[STR_CARGO_NAME_FISH]
base = "{G=ženski}riba"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "{G=ženski}poljoprivredna oprema"

[STR_CARGO_NAME_FRUITS]
base = "{G=srednji}voće i povrće"

[STR_CARGO_NAME_TIMBER]
base = "{G=ženski}drvne grede"

[STR_CARGO_NAME_MILK]
base = "{G=srednji}mleko"

[STR_CARGO_NAME_MANGANESE]
base = "Mangan"

[STR_CARGO_NAME_NITRATES]
base = "Nitrati"

[STR_CARGO_NAME_NUTS]
base = "Orasi"

[STR_CARGO_NAME_PETROL]
base = "{G=ženski}benzinska goriva"

[STR_CARGO_NAME_PHOSPHATE]
base = "Fosfati"

[STR_CARGO_NAME_PYRITE_ORE]
base = "Ruda pirita"

[STR_CARGO_NAME_SAND]
base = "{G=muški}pesak"

[STR_CARGO_NAME_SCRAP_METAL]
base = "{G=muški}metalni otpaci"

[STR_CARGO_NAME_AGGREGATES]
base = "{G=muški}kamen"

[STR_CARGO_NAME_VEHICLE_PARTS]
base = "Delovi vozila"

[STR_CARGO_NAME_VEHICLES]
base = "Vozila"

[STR_CARGO_NAME_WOOL]
base = "{G=ženski}vuna"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} alkohola"

[STR_CARGO_UNIT_BEANS]
base = "{WEIGHT} pasulja"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} građevinskog materijala"

[STR_CARGO_UNIT_CASSAVA]
base = "{WEIGHT}manioke"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} hemijskog proizvoda"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} gline"

[STR_CARGO_UNIT_COFFEE]
base = "{SIGNED_WORD} VREĆ{P a e e} kafe"

[STR_CARGO_UNIT_COPPER]
base = "{WEIGHT} bakra"

[STR_CARGO_UNIT_EDIBLE_OIL]
base = "{VOLUME} jestivog ulja"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} sanduka tehničke opreme"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} ribe"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} sanduka poljoprivredne opreme"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} voća i povrća"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} drvne grede"

[STR_CARGO_UNIT_MANGANESE]
base = "{WEIGHT} mangana"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} mleka"

[STR_CARGO_UNIT_NITRATES]
base = "{WEIGHT} nitrata"

[STR_CARGO_UNIT_NUTS]
base = "{SIGNED_WORD} vreć{P a e e} oraha"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} benzinskih goriva"

[STR_CARGO_UNIT_PHOSPHATE]
base = "{WEIGHT} fosfata"

[STR_CARGO_UNIT_PYRITE_ORE]
base = "{WEIGHT}rude pirita"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} peska"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} metalnih otpadaka"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} kamena"

[STR_CARGO_UNIT_VEHICLE_PARTS]
base = "{SIGNED_WORD} sanduk{P \"\" a a} delova vozila"

[STR_CARGO_UNIT_VEHICLES]
base = "{SIGNED_WORD}Vozil{P o a a}"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} bal{P a e a} vune"

[STR_CID_ALCOHOL]
base = "{TINYFONT}AL"

[STR_CID_BEANS]
base = "{TINYFONT}BN"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}GM"

[STR_CID_CASSAVA]
base = "{TINYFONT}CA"

[STR_CID_CHEMICALS]
base = "{TINYFONT}HE"

[STR_CID_CLAY]
base = "{TINYFONT}GL"

[STR_CID_COFFEE]
base = "{TINYFONT}CF"

[STR_CID_COPPER]
base = "{TINYFONT}CR"

[STR_CID_EDIBLE_OIL]
base = "{TINYFONT}EO"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}TP"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}PP"

[STR_CID_FISH]
base = "{TINYFONT}RI"

[STR_CID_TIMBER]
base = "{TINYFONT}DG"

[STR_CID_MANGANESE]
base = "{TINYFONT}MN"

[STR_CID_MILK]
base = "{TINYFONT}ML"

[STR_CID_NITRATES]
base = "{TINYFONT}NI"

[STR_CID_NUTS]
base = "{TINYFONT}NT"

[STR_CID_PETROL]
base = "{TINYFONT}BZ"

[STR_CID_PHOSPHATE]
base = "{TINYFONT}PH"

[STR_CID_PYRITE_ORE]
base = "{TINYFONT}PY"

[STR_CID_SAND]
base = "{TINYFONT}PK"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}MO"

[STR_CID_AGGREGATES]
base = "{TINYFONT}KA"

[STR_CID_VEHICLE_PARTS]
base = "{TINYFONT}VP"

[STR_CID_VEHICLES]
base = "{TINYFONT}VS"

[STR_CID_WOOL]
base = "{TINYFONT}VN"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}FIRS nije namenjen za Zemlju igračaka"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "mora se postaviti ispod snežnog pojasa."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "mora se postaviti na kopnu."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "ne sme se postaviti u pustinji."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "ne može se postaviti na kosinama."

[STR_ERR_LOCATION_LIMIT_1_PER_TOWN]
base = "Dozvoljena je samo jedna industrija ovog tipa po gradu"

[STR_IND_ALUMINIUM_PLANT]
base = "{G=muški}Kombinat aluminijuma"

[STR_IND_ARABLE_FARM]
base = "{G=ženski}Agrarna farma"

[STR_IND_ASSEMBLY_PLANT]
base = "Fabrika vozila"

[STR_IND_BIOREFINERY]
base = "{G=ženski}Biorafinerija"

[STR_IND_BREWERY]
base = "{G=ženski}Pivara"

[STR_IND_CIDER_MILL]
base = "{G=ženski}Tvornica jabukovače"

[STR_IND_BRICK_WORKS]
base = "{G=ženski}Ciglana"

[STR_IND_BUILDERS_YARD]
base = "{G=srednji}Građevinsko skladište"

[STR_IND_BULK_TERMINAL]
base = "Terminal za rasuti tovar"

[STR_IND_CEMENT_PLANT]
base = "{G=ženski}Cementara"

[STR_IND_CHEMICAL_PLANT]
base = "Hemijsko postrojenje"

[STR_IND_CLAY_PIT]
base = "{G=muški}Kop gline"

[STR_IND_COFFEE_ESTATE]
base = "{G=ženski}Plantaža kafe"

[STR_IND_COPPER_SMELTER]
base = "Rafinerija bakra"

[STR_IND_DAIRY]
base = "{G=ženski}Mlekara"

[STR_IND_DREDGING_SITE]
base = "{G=muški}Iskop"

[STR_IND_FISHING_GROUND]
base = "{G=ženski}Ribarska lovišta"

[STR_IND_FISHING_HARBOUR]
base = "{G=ženski}Ribarska luka"

[STR_IND_FISHING_VILLAGE]
base = "Ribarsko selo"

[STR_IND_FLOUR_MILL]
base = "Mlin"

[STR_IND_FOOD_MARKET]
base = "{G=ženski}Prodavnica"

[STR_IND_FOOD_PROCESSOR]
base = "Kombinat za preradu hrane"

[STR_IND_FURNITURE_FACTORY]
base = "{G=muški}Kombinat nameštaja"

[STR_IND_GENERAL_STORE]
base = "Prodavnica"

[STR_IND_GLASS_WORKS]
base = "{G=ženski}Staklara"

[STR_IND_HARDWARE_STORE]
base = "{G=ženski}Gvožđarska radnja"

[STR_IND_HOTEL]
base = "{G=muški}Hotel / Restoran"

[STR_IND_SCRAP_YARD]
base = "{G=muški}Otpad"

[STR_IND_LIME_KILN]
base = "{G=ženski}Krečana"

[STR_IND_LIQUIDS_TERMINAL]
base = "Terminal za tečnosti"

[STR_IND_TIMBER_YARD]
base = "{G=ženski}Drvara"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "{G=ženski}Mašinska radionica"

[STR_IND_MANGANESE_MINE]
base = "Rudnik mangana"

[STR_IND_MIXEDFARM]
base = "{G=ženski}Farma"

[STR_IND_NITRATE_MINE]
base = "Rudnik nitrata"

[STR_IND_ORCHARD_PIGGERY]
base = "Voćnjak i svinjac"

[STR_IND_PETROLPUMP]
base = "{G=ženski}Benzinska pumpa"

[STR_IND_PHOSPHATE_MINE]
base = "Rudnik fosfata"

[STR_IND_PLASTICS_PLANT]
base = "{G=muški}Kombinat plastike"

[STR_IND_PORT]
base = "Luka"

[STR_IND_PYRITE_MINE]
base = "Rudnik pirita"

[STR_IND_PYRITE_SMELTER]
base = "Talionica pirita"

[STR_IND_POWER_PLANT]
base = "Elektrana"

[STR_IND_QUARRY]
base = "{G=muški}Kamenolom"

[STR_IND_RANCH]
base = "Ranč"

[STR_IND_SHEEPFARM]
base = "{G=ženski}Farma ovaca"

[STR_IND_SMITHY_FORGE]
base = "{G=ženski}Kovačnica"

[STR_IND_STOCKYARD]
base = "{G=muški}Mesni kombinat"

[STR_IND_SUGAR_REFINERY]
base = "{G=ženski}Šećerana"

[STR_IND_SUPPLY_YARD]
base = "Dvorište za snabdevanje"

[STR_IND_TEXTILE_MILL]
base = "{G=muški}Tekstilni kombinat"

[STR_IND_TRADING_POST]
base = "Trgovačka kuća"

[STR_IND_TYRE_PLANT]
base = "Fabrika guma"

[STR_IND_VINEYARD]
base = "Vinograd"

[STR_PRIMARY_PRODUCTION_1X]
base = "{BLACK}Trenutna proizvodnja: {YELLOW}Normalna{}{}{BLACK}Za povećanje nivoa proizvodnje na {WHITE}poboljšani {BLACK} isporučite {SIGNED_WORD} sanduka proizvodnog materijala u roku od tri meseca{}Za povećanje nivoa proizvodnje na {WHITE}masovni {BLACK}isporučite {SIGNED_WORD} sanduka proizvodnog materijala"

[STR_PRIMARY_PRODUCTION_2X]
base = "{BLACK}Trenutna proizvodnja: {YELLOW}Poboljšana{}{}{BLACK}Za zadržavanje ovog nivoa proizvodnje, isporučite{SIGNED_WORD} sanduka proizvodnog materijala u roku od tri meseca{}Za povećanje nivoa proizvodnje na {WHITE}masovni {BLACK}isporučite {SIGNED_WORD} sanduka"

[STR_PRIMARY_PRODUCTION_4X]
base = "{BLACK}Trenutna proizvodnja: {YELLOW}Masovna{}{}{BLACK}Za zadržavanje ovog nivoa proizvodnje, isporučite {SKIP}{SIGNED_WORD} sanduka proizvodnog materijala u roku od tri meseca"

[STR_PORT_PRODUCTION_1X]
base = "{BLACK}Trenutna proizvodnja: {YELLOW}Normalna{}{}{BLACK}Za povećanje nivoa proizvodnje na{WHITE} poboljšani {BLACK} isporučite {SIGNED_WORD} jedinica proizvodnog materijala u roku od tri meseca{}Za povećanje nivoa proizvodnje na {WHITE} masovni {BLACK} isporučite {SIGNED_WORD} jedinica proizvodnog materijala"

[STR_PORT_PRODUCTION_2X]
base = "{BLACK}Trenutna proizvodnja: {YELLOW}Poboljšana{}{}{BLACK}Za zadržavanje ovog nivoa proizvodnje, isporučite{SIGNED_WORD} jedinica proizvodnog materijala u roku od tri meseca{}Za povećanje nivoa proizvodnje na{WHITE} masovni{BLACK} isporučite {SIGNED_WORD} jedinica proizvodnog materijala"

[STR_PORT_PRODUCTION_4X]
base = "{BLACK}Trenutna proizvodnja: {YELLOW}Masovna{}{}{BLACK}Za zadržavanje ovog nivoa proizvodnje, isporučite {SKIP}{SIGNED_WORD} jedinica proizvodnog materijala u roku od tri meseca"

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Lokacija: {YELLOW}Ne može se graditi u snežnom/pustinjskom pojasu i na kosinama."

[STR_FUND_COFFEE_ESTATE]
base = "{}{BLACK}Lokacija: {YELLOW} Ne može se graditi na snegu i u pustinjama"

[STR_FUND_DAIRY_FARM]
base = "{}{BLACK}Lokacija: {YELLOW} Ne može se graditi na snegu i u pustinjama"

[STR_FUND_FOREST]
base = "{}{BLACK}Lokacija: {YELLOW}Ne može se graditi u pustinjskom pojasu."

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Lokacija: {YELLOW}Ne može se graditi u snežnom pojasu."

[STR_FUND_ORCHARD_PIGGERY]
base = "{}{BLACK}Lokacija: {YELLOW} Ne može se graditi na snegu i u pustinjama"

[STR_FUND_RUBBER_PLANTATION]
base = "{}{BLACK}Lokacija: {YELLOW} Ne može se graditi na snegu i u pustinjama"

[STR_FUND_VINEYARD]
base = "{}{BLACK}Location: {YELLOW}Cannot be funded on snow or in deserts."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}Dostupno od: {YELLOW}{COMMA}"

[STR_FUND_AVAILABLE_UNTIL]
base = "{}{BLACK}Nije dostupno od: {YELLOW}{COMMA}"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING} {STRING}"

[STR_STATION_ANIMALS]
base = "Pazar konja"

[STR_STATION_FARM_1]
base = "Imanje"

[STR_STATION_FISHMARKET]
base = "Pazar ribe"

[STR_STATION_INDUSTRY_ESTATE_1]
base = "Industrijski park"

[STR_STATION_INDUSTRY_HARBOUR_1]
base = "{G=ženski}Industrijska luka"

[STR_STATION_MILL]
base = "{G=muški}Mlin"

[STR_STATION_PIT]
base = "Jama"

[STR_STATION_PLANTATION]
base = "Plantaža"

[STR_STATION_POWERHUNGRY]
base = "Elektrana"

[STR_STATION_REFINERY]
base = "Portland"

[STR_STATION_TOWN_1]
base = "Stara gradska skupština"

[STR_STATION_WATER]
base = "Sprud"
