[GLOBAL_PRAGMA]
grflangid = "0x16"
plural = "10"
gender = "m z s"
case = "g"

[STR_GRF_DESC]
base = "{ORANGE}FIRS Industry Replacement Set{}{BLACK}Vám prináša andythenorth, FooBar, planetmaker, Terkhen, Yexo a ďalší. {SILVER}Pozri ReadMe pre viac informácií, vrátane ako použiť FIRS. {BLACK}Licencia: GPL v2."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maximálna vzdialenosť lovísk rýb, ropných plošín a bagrovísk od pobrežia v dielcoch."

[STR_PARAM_DESC_ECONOMIES]
base = "Každá ekonomika poskytuje rôzne kombinácie tovaru a priemyslu.{}{}Pre hráčov, ktorý chcú jednoduchšiu hrateľnosť, 'Základná' ekonomika obsahuje menej priemyslu a tovaru ako ostatné FIRS ekonomiky."

[STR_PARAM_DESC_NO_OPENINGS]
base = "V predvolenom nastavení sa bude počas hry otvárať nový priemysel.{}{}Ak zvolíte 'brániť otváraniu' priemysel sa nebude otvárať počas hry, a hráči nebudú mocť založiť priemysel. (players will not be able to fund or prospect for industries.)"

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maximálna pobrežná vzdialenosť morského priemyslu v dielcoch"

[STR_PARAM_NAME_ECONOMIES]
base = "Ekonomika"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Zabrániť otváraniu priemyslu počas hry"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Bez limitu"

[STR_PARAM_NAME_PRIMARY_LEVEL1_REQUIREMENT]
base = "Počet surovín požadovacných pre zvýšenú produkciu (štandardne 16ks)"

[STR_PARAM_NAME_PRIMARY_LEVEL1_BONUS]
base = "Zvýšená úroveň primárnej produkcie (%)"

[STR_PARAM_DESC_PRIMARY_LEVEL_BONUS]
base = "Výroba v poľnohospodárskych podnikoch, v baniach a podobných odvetviach, iba ak sú splnené požiadavky na dodávku. (Ako percento {SILVER}normálnej {BLACK}produkčnej úrovne.)"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TEMPERATE]
base = "Základná ekonomika mierneho podnebia"

[STR_PARAM_VALUE_ECONOMIES_BASIC_ARCTIC]
base = "Základná ekonomika arktického podnebia"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TROPIC]
base = "Základná ekonomika tropického podnebia"

[STR_PARAM_VALUE_ECONOMIES_IN_A_HOT_COUNTRY]
base = "V Teplej Krajine"

[STR_CARGO_NAME_ALCOHOL]
base = "Alkohol"

[STR_CARGO_NAME_BEANS]
base = "Fazule"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "Stavebné materiály"

[STR_CARGO_NAME_CASSAVA]
base = "Maniok"

[STR_CARGO_NAME_CHEMICALS]
base = "Chemikálie"

[STR_CARGO_NAME_CLAY]
base = "Hlina"

[STR_CARGO_NAME_COFFEE]
base = "Káva"

[STR_CARGO_NAME_COKE]
base = "Koks"

[STR_CARGO_NAME_COPPER]
base = "Meď"

[STR_CARGO_NAME_EDIBLE_OIL]
base = "Jedlý Olej"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "Strojárske potreby"

[STR_CARGO_NAME_EXPLOSIVES]
base = "Výbušniny"

[STR_CARGO_NAME_FISH]
base = "Ryby"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "Poľnohospodárske potreby"

[STR_CARGO_NAME_FERTILISER]
base = "Hnojivo"

[STR_CARGO_NAME_FRUITS]
base = "Ovocie a Zelenina"

[STR_CARGO_NAME_TIMBER]
base = "Stavebné drevo"

[STR_CARGO_NAME_MILK]
base = "Mlieko"

[STR_CARGO_NAME_MANGANESE]
base = "Mangán"

[STR_CARGO_NAME_NITRATES]
base = "Dusičnany"

[STR_CARGO_NAME_NUTS]
base = "Orechy"

[STR_CARGO_NAME_PEAT]
base = "Rašelina"

[STR_CARGO_NAME_PETROL]
base = "Benzín"

[STR_CARGO_NAME_PYRITE_ORE]
base = "Pyritová Ruda"

[STR_CARGO_NAME_SAND]
base = "Piesok"

[STR_CARGO_NAME_SCRAP_METAL]
base = "Kovový šrot"

[STR_CARGO_NAME_SODA_ASH]
base = "Uhličitan sodný"

[STR_CARGO_NAME_AGGREGATES]
base = "Kameň"

[STR_CARGO_NAME_SULPHUR]
base = "Síra"

[STR_CARGO_NAME_VEHICLE_BODIES]
base = "Karosérie vozidiel"

[STR_CARGO_NAME_VEHICLE_PARTS]
base = "Náhradné diely pre vozidlá"

[STR_CARGO_NAME_WOOL]
base = "Vlna"

[STR_CARGO_NAME_ZINC]
base = "Zinok"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} alkoholu"

[STR_CARGO_UNIT_BEANS]
base = "{WEIGHT} faz{P uľa ule úľ}"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} stavebného materiálu"

[STR_CARGO_UNIT_CASSAVA]
base = "{WEIGHT} manioku"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} chemikálií"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} hliny"

[STR_CARGO_UNIT_COPPER]
base = "{WEIGHT} medi"

[STR_CARGO_UNIT_EDIBLE_OIL]
base = "{VOLUME} jedlého oleja"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} debn{P 0 a y ien} strojárskych potrieb"

[STR_CARGO_UNIT_EXPLOSIVES]
base = "{SIGNED_WORD} debn{P 0 a y ien} výbušnín"

[STR_CARGO_UNIT_FERTILISER]
base = "{WEIGHT} hnojiva"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} rýb"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} deb{P 0 na ny ien} poľnohospodárskych potrieb"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} ovocia a zeleniny"

[STR_CARGO_UNIT_KAOLIN]
base = "{WEIGHT} kaolínu"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} stavebného dreva"

[STR_CARGO_UNIT_MANGANESE]
base = "{WEIGHT} mangánu"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} mlieka"

[STR_CARGO_UNIT_NITRATES]
base = "{WEIGHT} dusičnanov"

[STR_CARGO_UNIT_NUTS]
base = "{SIGNED_WORD} vr{P ece ecia iec} orechov"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} benzínu"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} piesku"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} kovového šrotu"

[STR_CARGO_UNIT_STEEL]
base = "{WEIGHT} ocele"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} kameňa"

[STR_CARGO_UNIT_SULPHUR]
base = "{WEIGHT} síry"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} balík{P 0 \"\" y ov} vlny"

[STR_CARGO_UNIT_ZINC]
base = "{WEIGHT} zinku"

[STR_CID_ALCOHOL]
base = "{TINYFONT}AL"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}BM"

[STR_CID_CEMENT]
base = "{TINYFONT}CE"

[STR_CID_CHEMICALS]
base = "{TINYFONT}CH"

[STR_CID_CLAY]
base = "{TINYFONT}CY"

[STR_CID_EDIBLE_OIL]
base = "{TINYFONT}JO"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}ES"

[STR_CID_EXPLOSIVES]
base = "{TINYFONT}VB"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}FS"

[STR_CID_FERTILISER]
base = "{TINYFONT}FL"

[STR_CID_FISH]
base = "{TINYFONT}FI"

[STR_CID_TIMBER]
base = "{TINYFONT}LU"

[STR_CID_MANGANESE]
base = "{TINYFONT}MN"

[STR_CID_MILK]
base = "{TINYFONT}MK"

[STR_CID_NITRATES]
base = "{TINYFONT}NI"

[STR_CID_PEAT]
base = "{TINYFONT}RŠ"

[STR_CID_PETROL]
base = "{TINYFONT}PT"

[STR_CID_PYRITE_ORE]
base = "{TINYFONT}PY"

[STR_CID_SAND]
base = "{TINYFONT}SA"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}SM"

[STR_CID_AGGREGATES]
base = "{TINYFONT}ST"

[STR_CID_SULPHUR]
base = "{TINYFONT}SÍ"

[STR_CID_VEHICLE_BODIES]
base = "{TINYFONT}KS"

[STR_CID_VEHICLES]
base = "{TINYFONT}VZ"

[STR_CID_WOOL]
base = "{TINYFONT}WL"

[STR_CID_ZINC]
base = "{TINYFONT}ZN"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}FIRS nie je určený pre použitie v Toylande"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "musí byť umiestnená pod hranicou snehu."

[STR_ERR_LOCATION_NOT_BELOW_SNOWLINE]
base = "musí byť umiestnená nad hranicou snehu."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "musí byť umiestnená na pevnine."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "nemôže byť umiestnená na púšti."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "nemôže byť umiestnená na strmom svahu."

[STR_ERR_LOCATION_LIMIT_1_PER_TOWN]
base = "len jeden typ tohto priemyslu je povolený v meste."

[STR_IND_ALUMINIUM_PLANT]
base = "Závod na výrobu hliníka"

[STR_IND_ARABLE_FARM]
base = "Orná pôda"

[STR_IND_ASSEMBLY_PLANT]
base = "Montážny Závod"

[STR_IND_BASIC_OXYGEN_FURNACE]
base = "Kyslíková pec"

[STR_IND_BIOREFINERY]
base = "Biorafinéria"

[STR_IND_BLAST_FURNACE]
base = "Vysoká pec"

[STR_IND_BREWERY]
base = "Pivovar"

[STR_IND_BRICK_WORKS]
base = "Tehelňa"

[STR_IND_BUILDERS_YARD]
base = "Stavebniny"

[STR_IND_CEMENT_PLANT]
base = "Cementáreň"

[STR_IND_CLAY_PIT]
base = "Hlinená baňa"

[STR_IND_COFFEE_ESTATE]
base = "Kaviareň"

[STR_IND_COPPER_SMELTER]
base = "Medená rafinéria"

[STR_IND_DAIRY]
base = "Mliekareň"

[STR_IND_DREDGING_SITE]
base = "Bagrovisko"

[STR_IND_ELECTRIC_ARC_FURNACE]
base = "Elektrická Oblúková Pec"

[STR_IND_FISHING_GROUND]
base = "Lovisko rýb"

[STR_IND_FISHING_HARBOUR]
base = "Rybí prístav"

[STR_IND_FISHING_VILLAGE]
base = "Rybárska Dedinka"

[STR_IND_FOOD_MARKET]
base = "Obchod s potravinami"

[STR_IND_FOOD_PROCESSOR]
base = "Závod na spracovanie jedla"

[STR_IND_FURNITURE_FACTORY]
base = "Závod na výrobu nábytku"

[STR_IND_GENERAL_STORE]
base = "Obchod so Zmiešaným Tovarom"

[STR_IND_GLASS_WORKS]
base = "Skláreň"

[STR_IND_HARDWARE_STORE]
base = "Železiarstvo"

[STR_IND_HOTEL]
base = "Hotel"

[STR_IND_IRON_WORKS]
base = "Železiareň"

[STR_IND_SCRAP_YARD]
base = "Smetisko"

[STR_IND_LIME_KILN]
base = "Vápenka"

[STR_IND_TIMBER_YARD]
base = "Obchod s drevom"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "Strojársky závod"

[STR_IND_MANGANESE_MINE]
base = "Mangánová Baňa"

[STR_IND_MIXEDFARM]
base = "Zmiešaná farma"

[STR_IND_NITRATE_MINE]
base = "Dusičnanová Baňa"

[STR_IND_PEATLANDS]
base = "Rašeliniská"

[STR_IND_PETROLPUMP]
base = "Čerpacia stanica"

[STR_IND_PLASTICS_PLANT]
base = "Závod na výrobu plastu"

[STR_IND_PORT]
base = "Prístav"

[STR_IND_PYRITE_MINE]
base = "Pyritová Baňa"

[STR_IND_POWER_PLANT]
base = "Elektráreň"

[STR_IND_QUARRY]
base = "Lom"

[STR_IND_RANCH]
base = "Ranč"

[STR_IND_RECYCLING_DEPOT]
base = "Recyklačná skládka"

[STR_IND_RECYCLING_PLANT]
base = "Závod na recykláciu"

[STR_IND_REINDEER_FARM]
base = "Sobia Farma"

[STR_IND_SHEEPFARM]
base = "Ovčia farma"

[STR_IND_SLAG_GRINDING_PLANT]
base = "Závod na spracovanie škávry"

[STR_IND_SMITHY_FORGE]
base = "Kováčska dielňa"

[STR_IND_SODA_ASH_MINE]
base = "Baňa uhličitanu sodného"

[STR_IND_STOCKYARD]
base = "Bitúnok"

[STR_IND_SUGAR_REFINERY]
base = "Cukrovar"

[STR_IND_TEXTILE_MILL]
base = "Odevný závod"

[STR_IND_VINEYARD]
base = "Vinič"

[STR_EXTRA_TEXT_SECONDARY_NON_COMBINATORY]
base = "{BLACK}Produkuje maximálnou rýchlosťou, ak {WHITE}je akýkoľvek {BLACK}požadovaný tovar dodaný."

[STR_PRIMARY_PRODUCTION_1X]
base = "{BLACK}Súčasná produkcia: {YELLOW}normálna{}{}{BLACK}Na zdvojenie produkcie dodajte {SIGNED_WORD} debien potrieb do troch mesiacov (alebo {SIGNED_WORD} debien pre štvornásobnú produkciu)"

[STR_PRIMARY_PRODUCTION_2X]
base = "{BLACK}Súčasná produkcia: {YELLOW}zvýšená (2x){}{}{BLACK}Na udržanie úrovne výroby, dodajte {SIGNED_WORD} debien potrieb do troch mesiacov,{}{WHITE}alebo {SIGNED_WORD} debien pre zvýšenie na štvornásobnú produkciu"

[STR_PRIMARY_PRODUCTION_4X]
base = "{BLACK}Súčasná produkcia: {YELLOW}vynikajúca (4x){}{}{BLACK}Na udržanie úrovne výroby, dodajte {SKIP}{SIGNED_WORD} debien potrieb do troch mesiacov"

[STR_PORT_PRODUCTION_4X]
base = "{BLACK}Súčasná produkcia: {YELLOW}vynikajúca (4x){}{}{BLACK}Na udržanie úrovne výroby, dodajte {SKIP}{SIGNED_WORD} jednotiek nákladu do troch mesiacov"

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Umiestnenie: {YELLOW}Nemôže byť založená na snehu alebo na púšti."

[STR_FUND_COFFEE_ESTATE]
base = "{}{BLACK}Umiestnenie: {YELLOW}Nemôže byť založená na snehu alebo na púšti."

[STR_FUND_FOREST]
base = "{}{BLACK}Umiestnenie: {YELLOW}Nemôže byť založený na púšti."

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Umiestnenie: {YELLOW}Nemôže byť založená na snehu."

[STR_FUND_HERDING_COOP]
base = "{}{BLACK}Umiestnenie: {YELLOW}Môže byť založená iba na snehu."

[STR_FUND_RUBBER_PLANTATION]
base = "{}{BLACK}Umiestnenie: {YELLOW}Nemôže byť založená na snehu alebo na púšti."

[STR_FUND_VINEYARD]
base = "{}{BLACK}Umiestnenie: {YELLOW}Nemôže byť založená na snehu alebo na púšti."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}Dostupné od: {YELLOW}{COMMA}"

[STR_FUND_AVAILABLE_UNTIL]
base = "{}{BLACK}Nedostupné po: {YELLOW}{COMMA}"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING} {STRING}"

[STR_STATION_BARNS]
base = "Stodola"

[STR_STATION_BASE]
base = "Základňa"

[STR_STATION_DAIRY_LANE]
base = "Mliekareň"

[STR_STATION_EXCHANGE]
base = "Prekládka"

[STR_STATION_FARM_1]
base = "Vidiecke sídlo"

[STR_STATION_FISHMARKET]
base = "pri Rybárskom prístave"

[STR_STATION_FOREST]
base = "Spracovanie Dreva"

[STR_STATION_FORGE]
base = "pri Kováčovi"

[STR_STATION_FURNACE]
base = "pri vysokej peci"

[STR_STATION_HEAVY_INDUSTRY_2]
base = "Továreň"

[STR_STATION_INDUSTRY_HARBOUR_3]
base = "Prístavný mostík"

[STR_STATION_IRONSTONE]
base = "Železná ruda"

[STR_STATION_JOINERS_SHOP]
base = "Tesárstvo"

[STR_STATION_MANGANESE_MINES]
base = "Mangánové Bane"

[STR_STATION_MARKET]
base = "Obchod"

[STR_STATION_MILL]
base = "Mlyn"

[STR_STATION_MINE]
base = "Garbiarska Cesta"

[STR_STATION_MOULDINGS]
base = "Lišty"

[STR_STATION_OIL_RIG]
base = "Ropné pole"

[STR_STATION_PIT]
base = "Jama"

[STR_STATION_PLANTATION]
base = "Plantáž"

[STR_STATION_POWERHUNGRY]
base = "Elektráreň"

[STR_STATION_PUMPS]
base = "Pumpa"

[STR_STATION_PYRITES]
base = "Pyritové Sklady"

[STR_STATION_REFINERY]
base = "Rafinéria"

[STR_STATION_RUBBER_COMPANY]
base = "Spoločnosť Spracujúca Gumové produkty"

[STR_STATION_SHARP_STREET]
base = "Ostrá Ulica"

[STR_STATION_SHEEP_FOLD]
base = "Košiar"

[STR_STATION_SMELTER]
base = "Zlievareň"

[STR_STATION_SUGAR_COMPANY]
base = "Cukrárska Spoločnosť"

[STR_STATION_TANK_FARM]
base = "Ložisko ropy"

[STR_STATION_TOWN_1]
base = "Stará radnica"

[STR_STATION_TOWN_2]
base = "na diaľnici"

[STR_STATION_TOWN_3]
base = "Obchody"

[STR_STATION_WEAVE_AND_DYE]
base = "Tkaniny a Farbivá"

[STR_STATION_WELLS]
base = "pri Studniach"
