[GLOBAL_PRAGMA]
grflangid = "0x2e"
plural = "0"

[STR_GRF_DESC]
base = "{ORANGE}FIRS Industry Replacement Set{}{BLACK}Skapat av andythenorth, FooBar, planetmaker, Terkhen och Yexo, med hjälp av många andra. {SILVER}Se \"readme\"-filen för mer information, inklusive om hur man använder FIRS. {BLACK}Licens: GPL v2."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maximalt avstånd mellan fångstområden, oljeriggar och mudderverk, och kusten, i antal rutor."

[STR_PARAM_DESC_ECONOMIES]
base = "Varje ekonomi har egen kombination av godstyper och industrier.{}{}För spelare som vill ha en mer okomplicerad spelupplevelse innehåller {SILVER}bas{BLACK}-ekonomierna färre industrier och godstyper än andra FIRS-ekonomier.{}{}Detaljerad information om varje ekonomityp finns på FIRS hemsida."

[STR_PARAM_DESC_NO_OPENINGS]
base = "FIRS är förinställt att låta nya industrier öppna under spelets gång.{}{}Om {SILVER}förhindra öppning{BLACK} slås på kommer inga industrier öppnas och spelare kommer inte ha möjlighet att bygga eller prospektera för nya industrier."

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Maximalt avstånd mellan kusten och marina industrier, i antal rutor"

[STR_PARAM_NAME_ECONOMIES]
base = "Ekonomi"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Förhindra att industrier öppnar under spelets gång"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Ingen begränsning"

[STR_PARAM_NAME_PRIMARY_LEVEL1_REQUIREMENT]
base = "Antal lådor som krävs för förhöjd primär produktion (standard är 16)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_REQUIREMENT]
base = "Antal lådor som krävs för Gung-ho primär produktion (standard är 80)"

[STR_PARAM_DESC_PRIMARY_LEVEL_REQUIREMENT]
base = "När lådor med materiel levereras till bondgårdar, gruvor och liknande industrier, kommer produktionen först att ändras till {SILVER}Förhöjd (dubbel){BLACK} och sedan till {SILVER}Gung-ho{BLACK} ifall det levereras tillräckligt med lådor.{}{}Standardvärdet är bra men du kan ändra det här ifall behov skulle uppstå.{}{}Behovet av antal lådor som fraktas till hamnliknande industrier kommer att bli 8x högre och det värdet kan ändras här."

[STR_PARAM_NAME_PRIMARY_LEVEL1_BONUS]
base = "Förhöjd primär produktionsnivå (%)"

[STR_PARAM_NAME_PRIMARY_LEVEL2_BONUS]
base = "Gung-ho primär produktionsnivå (%)"

[STR_PARAM_DESC_PRIMARY_LEVEL_BONUS]
base = "Produktion på bondgårdar, gruvor och liknande industrier när leveranskraven är uppnådda (i procent av {SILVER}Normal {BLACK} produktionsnivå)."

[STR_PARAM_VALUE_ECONOMIES_BASIC_TEMPERATE]
base = "Tempererad bas-ekonomi"

[STR_PARAM_VALUE_ECONOMIES_BASIC_ARCTIC]
base = "Arktisk bas-ekonomi"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TROPIC]
base = "Tropisk bas-ekonomi"

[STR_PARAM_VALUE_ECONOMIES_IN_A_HOT_COUNTRY]
base = "I ett varmare land"

[STR_PARAM_VALUE_ECONOMIES_STEELTOWN]
base = "Stålstaden"

[STR_CARGO_NAME_ACID]
base = "Syra"

[STR_CARGO_NAME_ALCOHOL]
base = "Alkohol"

[STR_CARGO_NAME_BEANS]
base = "Bönor"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "Byggmaterial"

[STR_CARGO_NAME_CASSAVA]
base = "Kassava"

[STR_CARGO_NAME_CEMENT]
base = "Cement"

[STR_CARGO_NAME_CHEMICALS]
base = "Kemikalier"

[STR_CARGO_NAME_CHLORINE]
base = "Klorin"

[STR_CARGO_NAME_CLAY]
base = "Lera"

[STR_CARGO_NAME_COFFEE]
base = "Kaffe"

[STR_CARGO_NAME_COKE]
base = "Koks"

[STR_CARGO_NAME_COPPER]
base = "Koppar"

[STR_CARGO_NAME_EDIBLE_OIL]
base = "Matolja"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "Ingenjörsmateriel"

[STR_CARGO_NAME_EXPLOSIVES]
base = "Explosivämnen"

[STR_CARGO_NAME_FISH]
base = "Fisk"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "Lantbruksmateriel"

[STR_CARGO_NAME_FERTILISER]
base = "Gödningsmedel"

[STR_CARGO_NAME_FRUITS]
base = "Frukt"

[STR_CARGO_NAME_KAOLIN]
base = "Kaolin"

[STR_CARGO_NAME_LIMESTONE]
base = "Kalksten"

[STR_CARGO_NAME_TIMBER]
base = "Virke"

[STR_CARGO_NAME_MILK]
base = "Mjölk"

[STR_CARGO_NAME_MANGANESE]
base = "Mangan"

[STR_CARGO_NAME_NITRATES]
base = "Nitrat"

[STR_CARGO_NAME_NUTS]
base = "Nötter"

[STR_CARGO_NAME_PEAT]
base = "Torv"

[STR_CARGO_NAME_PETROL]
base = "Bensin"

[STR_CARGO_NAME_PHOSPHATE]
base = "Fosfat"

[STR_CARGO_NAME_PIG_IRON]
base = "Tackjärn"

[STR_CARGO_NAME_POTASH]
base = "Pottaska"

[STR_CARGO_NAME_PYRITE_ORE]
base = "Pyritmalm"

[STR_CARGO_NAME_QUICKLIME]
base = "Osläckt kalk"

[STR_CARGO_NAME_SALT]
base = "Salt"

[STR_CARGO_NAME_SAND]
base = "Sand"

[STR_CARGO_NAME_SCRAP_METAL]
base = "Metallskrot"

[STR_CARGO_NAME_SLAG]
base = "Slagg"

[STR_CARGO_NAME_SODA_ASH]
base = "Natriumkarbonat"

[STR_CARGO_NAME_STEEL]
base = "Stål"

[STR_CARGO_NAME_AGGREGATES]
base = "Sten"

[STR_CARGO_NAME_SULPHUR]
base = "Sulfat"

[STR_CARGO_NAME_VEHICLE_BODIES]
base = "Karosser"

[STR_CARGO_NAME_VEHICLE_PARTS]
base = "Fordonsdelar"

[STR_CARGO_NAME_VEHICLES]
base = "Fordon"

[STR_CARGO_NAME_WOOL]
base = "Ull"

[STR_CARGO_NAME_ZINC]
base = "Zink"

[STR_CARGO_UNIT_ACID]
base = "{VOLUME} av syra"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} alkohol"

[STR_CARGO_UNIT_BEANS]
base = "{WEIGHT} bönor"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} byggmaterial"

[STR_CARGO_UNIT_CASSAVA]
base = "{WEIGHT} kassava"

[STR_CARGO_UNIT_CEMENT]
base = "{WEIGHT} av cement"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} kemikalier"

[STR_CARGO_UNIT_CHLORINE]
base = "{VOLUME} av klorin"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} lera"

[STR_CARGO_UNIT_COFFEE]
base = "{SIGNED_WORD} säck{P 0 \"\" ar} med kaffe"

[STR_CARGO_UNIT_COKE]
base = "{WEIGHT} av koks"

[STR_CARGO_UNIT_COPPER]
base = "{WEIGHT} koppar"

[STR_CARGO_UNIT_EDIBLE_OIL]
base = "{VOLUME} matolja"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} låd{P 0 a or} med ingenjörsmateriel"

[STR_CARGO_UNIT_EXPLOSIVES]
base = "{SIGNED_WORD} låd{P 0 a or} med explosivämnen"

[STR_CARGO_UNIT_FERTILISER]
base = "{WEIGHT} av gödning"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} fisk"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} låd{P 0 a or} med lantbruksmateriel"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} frukt"

[STR_CARGO_UNIT_KAOLIN]
base = "{WEIGHT} av kaolin"

[STR_CARGO_UNIT_LIMESTONE]
base = "{WEIGHT} av kalksten"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} virke"

[STR_CARGO_UNIT_LYE]
base = "{VOLUME} of lut"

[STR_CARGO_UNIT_MANGANESE]
base = "{WEIGHT} mangan"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} mjölk"

[STR_CARGO_UNIT_NICKEL]
base = "{WEIGHT} av nickel"

[STR_CARGO_UNIT_NITRATES]
base = "{WEIGHT} nitrat"

[STR_CARGO_UNIT_NUTS]
base = "{SIGNED_WORD} säck{P 0 \"\" ar} av nötter"

[STR_CARGO_UNIT_PEAT]
base = "{WEIGHT} av torv"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} bensin"

[STR_CARGO_UNIT_PHOSPHATE]
base = "{WEIGHT} fosfat"

[STR_CARGO_UNIT_PIG_IRON]
base = "{WEIGHT} av tackjärn"

[STR_CARGO_UNIT_POTASH]
base = "{WEIGHT} av pottaska"

[STR_CARGO_UNIT_PYRITE_ORE]
base = "{WEIGHT} pyritmalm"

[STR_CARGO_UNIT_QUICKLIME]
base = "{WEIGHT} av osläckt kalk"

[STR_CARGO_UNIT_SALT]
base = "{WEIGHT} av salt"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} sand"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} metallskrot"

[STR_CARGO_UNIT_SLAG]
base = "{WEIGHT} av slagg"

[STR_CARGO_UNIT_SODA_ASH]
base = "{WEIGHT} av natriumkarbonat"

[STR_CARGO_UNIT_STEEL]
base = "{WEIGHT} av stål"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} sten"

[STR_CARGO_UNIT_SULPHUR]
base = "{WEIGHT} av sulfat"

[STR_CARGO_UNIT_VEHICLE_BODIES]
base = "{WEIGHT} av karosser"

[STR_CARGO_UNIT_VEHICLE_PARTS]
base = "{WEIGHT} av fordonsdelar"

[STR_CARGO_UNIT_VEHICLES]
base = "{WEIGHT} av fordon"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} bal{P 0 \"\" ar} med ull"

[STR_CARGO_UNIT_ZINC]
base = "{WEIGHT} av zink"

[STR_CID_ACID]
base = "{TINYFONT}SY"

[STR_CID_ALCOHOL]
base = "{TINYFONT}AL"

[STR_CID_BEANS]
base = "{TINYFONT}BN"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}BM"

[STR_CID_CASSAVA]
base = "{TINYFONT}KA"

[STR_CID_CEMENT]
base = "{TINYFONT}CE"

[STR_CID_CHEMICALS]
base = "{TINYFONT}KE"

[STR_CID_CHLORINE]
base = "{TINYFONT}KL"

[STR_CID_CLAY]
base = "{TINYFONT}LE"

[STR_CID_COFFEE]
base = "{TINYFONT}KF"

[STR_CID_COKE]
base = "{TINYFONT}KK"

[STR_CID_COPPER]
base = "{TINYFONT}KR"

[STR_CID_EDIBLE_OIL]
base = "{TINYFONT}VO"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}IM"

[STR_CID_EXPLOSIVES]
base = "{TINYFONT}EX"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}LM"

[STR_CID_FERTILISER]
base = "{TINYFONT}GM"

[STR_CID_FISH]
base = "{TINYFONT}FI"

[STR_CID_KAOLIN]
base = "{TINYFONT}KA"

[STR_CID_LIMESTONE]
base = "{TINYFONT}KS"

[STR_CID_TIMBER]
base = "{TINYFONT}VI"

[STR_CID_LYE]
base = "{TINYFONT}LT"

[STR_CID_MANGANESE]
base = "{TINYFONT}MN"

[STR_CID_MILK]
base = "{TINYFONT}MK"

[STR_CID_NICKEL]
base = "{TINYFONT}NK"

[STR_CID_NITRATES]
base = "{TINYFONT}NI"

[STR_CID_NUTS]
base = "{TINYFONT}NT"

[STR_CID_PEAT]
base = "{TINYFONT}TV"

[STR_CID_PETROL]
base = "{TINYFONT}BN"

[STR_CID_PIG_IRON]
base = "{TINYFONT}TJ"

[STR_CID_PHOSPHATE]
base = "{TINYFONT}FF"

[STR_CID_POTASH]
base = "{TINYFONT}PA"

[STR_CID_PYRITE_ORE]
base = "{TINYFONT}PY"

[STR_CID_QUICKLIME]
base = "{TINYFONT}OL"

[STR_CID_SALT]
base = "{TINYFONT}SA"

[STR_CID_SAND]
base = "{TINYFONT}SA"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}MS"

[STR_CID_SLAG]
base = "{TINYFONT}SG"

[STR_CID_SODA_ASH]
base = "{TINYFONT}NK"

[STR_CID_STEEL]
base = "{TINYFONT}SL"

[STR_CID_AGGREGATES]
base = "{TINYFONT}ST"

[STR_CID_SULPHUR]
base = "{TINYFONT}SF"

[STR_CID_VEHICLE_BODIES]
base = "{TINYFONT}KR"

[STR_CID_VEHICLE_PARTS]
base = "{TINYFONT}FD"

[STR_CID_VEHICLES]
base = "{TINYFONT}FN"

[STR_CID_WOOL]
base = "{TINYFONT}UL"

[STR_CID_ZINC]
base = "{TINYFONT}ZN"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "måste placeras nedanför snögränsen."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "måste placeras på torra land."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "får inte placeras i öknen."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "kan inte placeras på branta sluttningar."

[STR_ERR_LOCATION_LIMIT_1_PER_TOWN]
base = "bara en industri av den här typen är tillåten per stad."

[STR_IND_ALUMINIUM_PLANT]
base = "Aluminiumverk"

[STR_IND_AMMONIA_PLANT]
base = "Ammoniakfabrik"

[STR_IND_ARABLE_FARM]
base = "Jordbruk"

[STR_IND_ASSEMBLY_PLANT]
base = "Fordonsfabrik"

[STR_IND_BASIC_OXYGEN_FURNACE]
base = "Enkel syrgasugn"

[STR_IND_BLAST_FURNACE]
base = "Smältugn"

[STR_IND_BREWERY]
base = "Bryggeri"

[STR_IND_CIDER_MILL]
base = "Musteri"

[STR_IND_BRICK_WORKS]
base = "Tegelbruk"

[STR_IND_BUILDERS_YARD]
base = "Byggföretag"

[STR_IND_BULK_TERMINAL]
base = "Bulkhamn"

[STR_IND_CEMENT_PLANT]
base = "Cementfabrik"

[STR_IND_CHEMICAL_PLANT]
base = "Kemifabrik"

[STR_IND_CLAY_PIT]
base = "Lertäkt"

[STR_IND_COFFEE_ESTATE]
base = "Kaffeplantage"

[STR_IND_COKE_OVEN]
base = "Koksugn"

[STR_IND_COPPER_SMELTER]
base = "Kopparraffinaderi"

[STR_IND_DAIRY]
base = "Mejeri"

[STR_IND_DAIRY_FARM]
base = "Mjölkgård"

[STR_IND_DREDGING_SITE]
base = "Mudderverk"

[STR_IND_ELECTRIC_ARC_FURNACE]
base = "Ljusbågesmältverk"

[STR_IND_FISHING_GROUND]
base = "Fångstområde"

[STR_IND_FISHING_HARBOUR]
base = "Fiskehamn"

[STR_IND_FLOUR_MILL]
base = "Mjölkvarn"

[STR_IND_FOOD_PROCESSOR]
base = "Livsmedelstillverkningsfabrik"

[STR_IND_FURNITURE_FACTORY]
base = "Möbelfabrik"

[STR_IND_GENERAL_STORE]
base = "Affär"

[STR_IND_GLASS_WORKS]
base = "Glasbruk"

[STR_IND_HARDWARE_STORE]
base = "Byggvaruhus"

[STR_IND_HOTEL]
base = "Hotell"

[STR_IND_HERDING_COOP]
base = "Vallningsfålla"

[STR_IND_SCRAP_YARD]
base = "Skrotupplag"

[STR_IND_LIME_KILN]
base = "Kalkbruk"

[STR_IND_LIMESTONE_MINE]
base = "Kalkstensgruva"

[STR_IND_LIQUIDS_TERMINAL]
base = "Vätsketerminal"

[STR_IND_TIMBER_YARD]
base = "Brädgård"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "Maskinfabrik"

[STR_IND_MANGANESE_MINE]
base = "Mangangruva"

[STR_IND_NITRATE_MINE]
base = "Nitratgruva"

[STR_IND_ORCHARD_PIGGERY]
base = "Fruktträdgård och svinfarm"

[STR_IND_PEATLANDS]
base = "Torvmark"

[STR_IND_PETROLPUMP]
base = "Bensinstation"

[STR_IND_PHOSPHATE_MINE]
base = "Fosfatgruva"

[STR_IND_PLASTICS_PLANT]
base = "Plastfabrik"

[STR_IND_PORT]
base = "Handelshamn"

[STR_IND_POTASH_MINE]
base = "Pottaskegruva"

[STR_IND_PYRITE_MINE]
base = "Pyritgruva"

[STR_IND_PYRITE_SMELTER]
base = "Pyritsmältverk"

[STR_IND_POWER_PLANT]
base = "Kraftverk"

[STR_IND_QUARRY]
base = "Grustäkt"

[STR_IND_RANCH]
base = "Ranch"

[STR_IND_SHEEPFARM]
base = "Fårfarm"

[STR_IND_SLAG_GRINDING_PLANT]
base = "Slaggmalningsanläggning"

[STR_IND_SMITHY_FORGE]
base = "Smedja"

[STR_IND_SODA_ASH_MINE]
base = "Natriumkarbonatgruva"

[STR_IND_STOCKYARD]
base = "Slakteri"

[STR_IND_SUGAR_REFINERY]
base = "Sockerbruk"

[STR_IND_SUPPLY_YARD]
base = "Materielförråd"

[STR_IND_TEXTILE_MILL]
base = "Textilfabrik"

[STR_IND_TRADING_POST]
base = "Handelshamn"

[STR_IND_TYRE_PLANT]
base = "Däcksfabrik"

[STR_IND_VINEYARD]
base = "Vingård"

[STR_IND_WHARF]
base = "Kaj"

[STR_CARGO_SUBTYPE_DISPLAY_CARGO_SUPPLIED_FLAG]
base = "{BLACK}(mottagen)"

[STR_EXTRA_TEXT_SECONDARY_NON_COMBINATORY]
base = "{BLACK}Producerar maximalt när {WHITE}någon {BLACK} erforderlig last levereras."

[STR_PRIMARY_PRODUCTION_1X]
base = "{BLACK}Nuvarande produktion: {YELLOW}Normal{}{}{BLACK}Leverera {SIGNED_WORD} lådor med materiel inom tre månader för {WHITE}Förhöjd{BLACK} produktion{}Leverera  {SIGNED_WORD} lådor för {WHITE}Gung-ho {BLACK}produktion."

[STR_PRIMARY_PRODUCTION_2X]
base = "{BLACK}Nuvarande produktion: {YELLOW}Förhöjd{}{}{BLACK}Leverera {SIGNED_WORD} lådor med materiel inom tre månader för att behålla den här nivån{}Leverera {SIGNED_WORD}  lådor för {WHITE}Gung-ho {BLACK}produktion."

[STR_PRIMARY_PRODUCTION_4X]
base = "{BLACK}Nuvarande produktion: {YELLOW}Gung-ho{}{}{BLACK}Leverera {SKIP}{SIGNED_WORD} lådor med materiel inom tre månader för att behålla den här nivån."

[STR_PORT_PRODUCTION_1X]
base = "{BLACK}Nuvarande produktion: {YELLOW}Normal{}{}{BLACK}Leverera {SIGNED_WORD} enheter med last inom tre månader för {WHITE}Förhöjd{BLACK} produktion{}Leverera {SIGNED_WORD} enheter för {WHITE}Gung-ho {BLACK}produktion."

[STR_PORT_PRODUCTION_2X]
base = "{BLACK}Nuvarande produktion: {YELLOW}Förhöjd{}{}{BLACK}Leverera {SIGNED_WORD} enheter med last inom tre månader för att behålla den här nivån.{}Leverera {SIGNED_WORD} enheter för {WHITE}Gung-ho {BLACK}produktion."

[STR_PORT_PRODUCTION_4X]
base = "{BLACK}Nuvarande produktion: {YELLOW}Gung-ho{}{}{BLACK}Leverera {SKIP}{SIGNED_WORD} enheter last inom tre månader för att behålla den här nivån."

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Placering: {YELLOW}Kan inte byggas på snö eller i öknar."

[STR_FUND_COFFEE_ESTATE]
base = "{}{BLACK}Placering: {YELLOW}Kan inte byggas på snö eller i öknar."

[STR_FUND_DAIRY_FARM]
base = "{}{BLACK}Placering: {YELLOW}Kan inte byggas på snö eller i öknar."

[STR_FUND_FOREST]
base = "{}{BLACK}Placering: {YELLOW}Kan inte byggas i öknar."

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Placering: {YELLOW}Kan inte byggas på snö."

[STR_FUND_HERDING_COOP]
base = "{}{BLACK}Placering: {YELLOW}Kan enbart byggas på snö."

[STR_FUND_ORCHARD_PIGGERY]
base = "{}{BLACK}Placering: {YELLOW}Kan inte byggas på snö eller i öknar."

[STR_FUND_RUBBER_PLANTATION]
base = "{}{BLACK}Placering: {YELLOW}Kan inte byggas på snö eller i öknar."

[STR_FUND_VINEYARD]
base = "{}{BLACK}Placering: {YELLOW}Kan inte byggas på snö eller i öknar."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}Tillgänglig från: {YELLOW}{COMMA}"

[STR_FUND_AVAILABLE_UNTIL]
base = "{}{BLACK}Ej tillgänglig efter: {YELLOW}{COMMA}"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING} {STRING}"

[STR_STATION_ANIMALS]
base = "Hästmarknad"

[STR_STATION_AUTOMOTIVE]
base = "Bilar"

[STR_STATION_BAR_GRILL_AND_ROOMS]
base = "Bar, Grill och Rum"

[STR_STATION_BARNS]
base = "Ladugårdar"

[STR_STATION_BARREL_AND_KEG]
base = "Tunna och Kagge"

[STR_STATION_BASE]
base = "Bas"

[STR_STATION_BONEYARD]
base = "Bengård"

[STR_STATION_BANK_TOP]
base = "Banktoppen"

[STR_STATION_COLLIERY]
base = "Kolgruva"

[STR_STATION_COPPER_LODE]
base = "Kopparåder"

[STR_STATION_CREOSOTING]
base = "Timberstapling"

[STR_STATION_DAIRY_LANE]
base = "Mejerigränd"

[STR_STATION_ESTATE]
base = "Egendom"

[STR_STATION_FARM_1]
base = "Herrgård"

[STR_STATION_FARM_2]
base = "Äng"

[STR_STATION_FARM_3]
base = "Ranch"

[STR_STATION_FISHMARKET]
base = "Fiskemarknad"

[STR_STATION_FOOD_CORPORATION]
base = "Livsmedelsföretag"

[STR_STATION_FOREST]
base = "Stocklastning"

[STR_STATION_FURNACE]
base = "Masugn"

[STR_STATION_HEAVY_INDUSTRY_2]
base = "Verkstad"

[STR_STATION_HERDING_COOP]
base = "Stuga"

[STR_STATION_INDUSTRY_ESTATE_1]
base = "Industriområde"

[STR_STATION_INDUSTRY_HARBOUR_1]
base = "Industrihamn"

[STR_STATION_INDUSTRY_HARBOUR_2]
base = "Strand"

[STR_STATION_INDUSTRY_HARBOUR_3]
base = "Landningsbrygga"

[STR_STATION_IRONSTONE]
base = "Malmberg"

[STR_STATION_KILNS]
base = "Smältugnar"

[STR_STATION_KIMBERLITE_DEPOSITS]
base = "Kimberfyndighet"

[STR_STATION_LIMESTONE_MINES]
base = "Kalkstensgruvor"

[STR_STATION_MANGANESE_MINES]
base = "Mangangruvor"

[STR_STATION_MILL]
base = "Kvarn"

[STR_STATION_MOULDINGS]
base = "Lister"

[STR_STATION_OIL_RIG]
base = "Oljefält"

[STR_STATION_ORCHARDS]
base = "Fruktträdgård"

[STR_STATION_PIT]
base = "Dagbrott"

[STR_STATION_PLANTATION]
base = "Plantage"

[STR_STATION_POWERHUNGRY]
base = "Elkraftverk"

[STR_STATION_PUMPS]
base = "Pumpar"

[STR_STATION_PYRITES]
base = "Pyritfyndighet"

[STR_STATION_REFINERY]
base = "Raffinaderi"

[STR_STATION_RUBBER_COMPANY]
base = "Gummibolag"

[STR_STATION_SALTPETER_WORKS]
base = "Saltpeterbruk"

[STR_STATION_SHARP_STREET]
base = "Skarpgatan"

[STR_STATION_SHEEP_FOLD]
base = "Fårfålla"

[STR_STATION_SHOALS]
base = "Grund"

[STR_STATION_SILO]
base = "Silo"

[STR_STATION_SMELTER]
base = "Smältverk"

[STR_STATION_SUGAR_COMPANY]
base = "Sockerbolag"

[STR_STATION_TANK_FARM]
base = "Tankgård"

[STR_STATION_TAPPERS_SHED]
base = "Tappareskjul"

[STR_STATION_TOWN_1]
base = "Gamla bystugan"

[STR_STATION_TOWN_3]
base = "Butiker"

[STR_STATION_TRONA_BEDS]
base = "Tronabädd"

[STR_STATION_WATER]
base = "Sandbank"

[STR_STATION_WELLS]
base = "Källor"

[STR_STATION_WINERY]
base = "Vingård"
