[GLOBAL_PRAGMA]
grflangid = "0x0a"
plural = "0"

[STR_PARAM_NAME_ECONOMIES]
base = "பொருளாதாரம்"

[STR_CARGO_NAME_ALCOHOL]
base = "மதுசாரம்"

[STR_CARGO_NAME_BEANS]
base = "அவரை"

[STR_CARGO_NAME_CHEMICALS]
base = "இரசாயனங்கள்"

[STR_CARGO_NAME_CLAY]
base = "களிமண்"

[STR_CARGO_NAME_COFFEE]
base = "காப்பி"

[STR_CARGO_NAME_COPPER]
base = "செப்பு"

[STR_CARGO_NAME_FISH]
base = "மீன்"

[STR_CARGO_NAME_FRUITS]
base = "பழம்"

[STR_CARGO_NAME_MILK]
base = "பால்"

[STR_CARGO_NAME_MANGANESE]
base = "மாங்கனீசு"

[STR_CARGO_NAME_NUTS]
base = "கொட்டைகள்"

[STR_CARGO_NAME_PETROL]
base = "பெட்ரோலியம் எரிபொருட்கள்"

[STR_CARGO_NAME_PHOSPHATE]
base = "பாஸ்பேட்டு"

[STR_CARGO_NAME_SAND]
base = "மண்"

[STR_CARGO_NAME_AGGREGATES]
base = "கல்"

[STR_CARGO_NAME_VEHICLE_PARTS]
base = "வாகன பாகங்கள்"

[STR_CARGO_NAME_WOOL]
base = "கம்பளி"

[STR_IND_ASSEMBLY_PLANT]
base = "வாகன தொழிற்சாலை"

[STR_IND_MIXEDFARM]
base = "கலப்புப் பண்ணை"

[STR_TOWN]
base = "{STRING}"

[STR_STATION]
base = "{STRING} {STRING}"

[STR_STATION_ANIMALS]
base = "குதிரை சந்தை"
