[GLOBAL_PRAGMA]
grflangid = "0x3e"
plural = "1"
case = "tamlanan"

[STR_PARAM_VALUE_ECONOMIES_BASIC_TEMPERATE]
base = "Basit Ilıman"

[STR_CARGO_NAME_ALCOHOL]
base = "Alkol"

[STR_CARGO_NAME_BEANS]
base = "Fasulye"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "Yapı Malzemesi"

[STR_CARGO_NAME_CHEMICALS]
base = "Kimyasal"

[STR_CARGO_NAME_CLAY]
base = "Kil"

[STR_CARGO_NAME_COFFEE]
base = "Kahve"

[STR_CARGO_NAME_COPPER]
base = "Bakır"

[STR_CARGO_NAME_FISH]
base = "Balık"

[STR_CARGO_NAME_FRUITS]
base = "Meyve"

[STR_CARGO_NAME_TIMBER]
base = "Kereste"

[STR_CARGO_NAME_MILK]
base = "Süt"

[STR_CARGO_NAME_NITRATES]
base = "Nitrat"

[STR_CARGO_NAME_PETROL]
base = "Benzin"

[STR_CARGO_NAME_PHOSPHATE]
base = "Fosfat"

[STR_CARGO_NAME_PYRITE_ORE]
base = "Pirit"

[STR_CARGO_NAME_SAND]
base = "Kum"

[STR_CARGO_NAME_SCRAP_METAL]
base = "Hurda Metal"

[STR_CARGO_NAME_AGGREGATES]
base = "Taş"

[STR_CARGO_NAME_VEHICLE_PARTS]
base = "Yedek Parça"

[STR_CARGO_NAME_VEHICLES]
base = "Araç"

[STR_CARGO_NAME_WOOL]
base = "Yün"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} alkol"

[STR_CARGO_UNIT_BEANS]
base = "{WEIGHT} fasulye"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} yapı malzemesi"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} kimyasal"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} kil"

[STR_CARGO_UNIT_COFFEE]
base = "{SIGNED_WORD} çuval kahve"

[STR_CARGO_UNIT_COPPER]
base = "{WEIGHT} bakır"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} balık"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} meyve"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} kereste"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} süt"

[STR_CARGO_UNIT_NITRATES]
base = "{WEIGHT} nitrat"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} benzin"

[STR_CARGO_UNIT_PHOSPHATE]
base = "{WEIGHT} fosfat"

[STR_CARGO_UNIT_PYRITE_ORE]
base = "{WEIGHT} pirit"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} kum"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} hurda metal"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} taş"

[STR_CARGO_UNIT_VEHICLE_PARTS]
base = "{SIGNED_WORD} kasa yedek parça"

[STR_CARGO_UNIT_VEHICLES]
base = "{SIGNED_WORD} araç"

[STR_CARGO_UNIT_WOOL]
base = "{SIGNED_WORD} balya yün"

[STR_CID_ALCOHOL]
base = "{TINYFONT}AL"

[STR_CID_BEANS]
base = "{TINYFONT}FA"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}YM"

[STR_CID_CHEMICALS]
base = "{TINYFONT}KM"

[STR_CID_CLAY]
base = "{TINYFONT}KL"

[STR_CID_COFFEE]
base = "{TINYFONT}KA"

[STR_CID_COPPER]
base = "{TINYFONT}BA"

[STR_CID_FISH]
base = "{TINYFONT}BA"

[STR_CID_TIMBER]
base = "{TINYFONT}KE"

[STR_CID_MILK]
base = "{TINYFONT}ST"

[STR_CID_NITRATES]
base = "{TINYFONT}NI"

[STR_CID_PHOSPHATE]
base = "{TINYFONT}FO"

[STR_CID_SAND]
base = "{TINYFONT}KU"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}HM"

[STR_CID_AGGREGATES]
base = "{TINYFONT}TŞ"

[STR_CID_VEHICLE_PARTS]
base = "{TINYFONT}YP"

[STR_CID_WOOL]
base = "{TINYFONT}YN"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}FIRS Oyuncak yer biçeminde kullanılamaz"

[STR_IND_BREWERY]
base = "Bira Fabrikası"

[STR_IND_CEMENT_PLANT]
base = "Çimentocusu"

[STR_IND_CHEMICAL_PLANT]
base = "Kimya Tesisi"

[STR_IND_CLAY_PIT]
base = "Kil Çukuru"

[STR_IND_COPPER_SMELTER]
base = "Bakır Rafinerisi"

[STR_IND_FURNITURE_FACTORY]
base = "Mobilya Fabrikası"

[STR_IND_HARDWARE_STORE]
base = "Hırdavatçısı"

[STR_IND_HOTEL]
base = "Oteli"

[STR_IND_SCRAP_YARD]
base = "Hurdacısı"

[STR_IND_TIMBER_YARD]
base = "Kereste Deposu"

[STR_IND_NITRATE_MINE]
base = "Nitrat Madeni"

[STR_IND_PETROLPUMP]
base = "Benzin İstasyonu"

[STR_IND_PHOSPHATE_MINE]
base = "Fosfat Madeni"

[STR_IND_PYRITE_MINE]
base = "Pirit Madeni"

[STR_IND_QUARRY]
base = "Taş ve Kum Ocağı"

[STR_IND_SHEEPFARM]
base = "Kuzu Çiftliği"

[STR_IND_SUGAR_REFINERY]
base = "Şeker Rafinerisi"

[STR_IND_TEXTILE_MILL]
base = "Tekstil Atölyesi"

[STR_TOWN]
base = "{STRING}"
