[GLOBAL_PRAGMA]
grflangid = "0x0f"
plural = "0"

[STR_GRF_DESC]
base = "{ORANGE}Set Amnewid Diwidiannau FIRS{}{BLACK}Gan {SILVER}andythenorth{BLACK} a {SILVER}FooBar{BLACK}.{}{BLACK}'1,000 o ddiweddariadau a mwy...'{BLACK}{}{}Gwefan: {SILVER}www.tt-foundry.com/sets/FIRS{BLACK}.Trwydded: {SILVER}GPL v2{BLACK}.Diolch arbennig i {SILVER}Ammler{BLACK}, {SILVER}Core Xii{BLACK}, {SILVER}Irwe{BLACK}, {SILVER}planetmaker{BLACK} a {SILVER}Zephyris{BLACK}.Defnyddir elfennau o {SILVER}eGRVTS{BLACK}, {SILVER}ISR{BLACK} a {SILVER}OpenGFX{BLACK}."

[STR_PARAM_DESC_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Pellter uchafsymol o'r arfordir ar gyfer meusydd pysgota, rigiau olew a mannau carthu fishing grounds, oil rigs and dredging sites, mewn teiliau."

[STR_PARAM_DESC_ECONOMIES]
base = "Pan fydd wedi ei orffen, bydd FIRS yn cynnwys dewis o economíau. Mae'r cargo a diwydiannau'n amrywio o economi i economi, ynghyd â'r cyfraddau tâl llwythi.{}{}{SILVER}Dim on un economi sydd ar gael ar hyn o bryd :)"

[STR_PARAM_DESC_NO_OPENINGS]
base = "Ni agorir diwydiannau newydd yn ystod y gêm.{}Ni chaiff chwareuwyr mwynchwilio na ariannu diwydiannau newydd.{}Adeiladir diwydiannau ar ddechrau'r gêm gan y cynhyrchydd map (yn ôl y gosodiadau map a ddefnyddir)."

[STR_PARAM_NAME_COAST_DISTANCE_MARINE_INDUSTRY]
base = "Pellter o'r arfordir ar gyfer diwydiannau morol (mewn teiliau)"

[STR_PARAM_NAME_ECONOMIES]
base = "Economi"

[STR_PARAM_NAME_NO_OPENINGS]
base = "Nadu diwydiannau rhag agor yn ystod y gêm"

[STR_PARAM_VALUE_SECONDARY_NEVER_CLOSE_0]
base = "Dim terfyn"

[STR_CARGO_NAME_ALCOHOL]
base = "Alcohol"

[STR_CARGO_NAME_BUILDING_MATERIALS]
base = "Deunyddiau Adeiladu"

[STR_CARGO_NAME_CHEMICALS]
base = "Cemegion"

[STR_CARGO_NAME_CLAY]
base = "Clai"

[STR_CARGO_NAME_COPPER]
base = "Copr"

[STR_CARGO_NAME_ENGINEERING_SUPPLIES]
base = "Deunyddiau Peirianneg"

[STR_CARGO_NAME_FISH]
base = "Pysgod"

[STR_CARGO_NAME_FARM_SUPPLIES]
base = "Deunyddiau Fferm"

[STR_CARGO_NAME_FRUITS]
base = "Frwythau"

[STR_CARGO_NAME_TIMBER]
base = "Pren"

[STR_CARGO_NAME_MILK]
base = "Llefrith"

[STR_CARGO_NAME_MANGANESE]
base = "Manganîs"

[STR_CARGO_NAME_PETROL]
base = "Petrol"

[STR_CARGO_NAME_SAND]
base = "Tywod"

[STR_CARGO_NAME_SCRAP_METAL]
base = "Metel Sgrap"

[STR_CARGO_NAME_AGGREGATES]
base = "Carreg"

[STR_CARGO_NAME_WOOL]
base = "Gwlân"

[STR_CARGO_UNIT_ALCOHOL]
base = "{VOLUME} o alcohol"

[STR_CARGO_UNIT_BUILDING_MATERIALS]
base = "{WEIGHT} o ddeunyddiau adeiladu"

[STR_CARGO_UNIT_CHEMICALS]
base = "{VOLUME} o gemegion"

[STR_CARGO_UNIT_CLAY]
base = "{WEIGHT} o glai"

[STR_CARGO_UNIT_ENGINEERING_SUPPLIES]
base = "{SIGNED_WORD} crât o ddeunyddiau peirianneg"

[STR_CARGO_UNIT_FISH]
base = "{WEIGHT} o bysgod"

[STR_CARGO_UNIT_FMSP]
base = "{SIGNED_WORD} crât o ddeunyddiau fferm"

[STR_CARGO_UNIT_FRUITS]
base = "{WEIGHT} o ffrwythau"

[STR_CARGO_UNIT_TIMBER]
base = "{WEIGHT} o bren"

[STR_CARGO_UNIT_MILK]
base = "{VOLUME} o lefrith"

[STR_CARGO_UNIT_PETROL]
base = "{VOLUME} o betrol"

[STR_CARGO_UNIT_SAND]
base = "{WEIGHT} o dywod"

[STR_CARGO_UNIT_SCRAP_METAL]
base = "{WEIGHT} o fetel sgrap"

[STR_CARGO_UNIT_AGGREGATES]
base = "{WEIGHT} o garreg"

[STR_CARGO_UNIT_WOOL]
base = "{WEIGHT} o wlân"

[STR_CID_ALCOHOL]
base = "{TINYFONT}ALC"

[STR_CID_BUILDING_MATERIALS]
base = "{TINYFONT}ADL"

[STR_CID_CHEMICALS]
base = "{TINYFONT}CEM"

[STR_CID_CLAY]
base = "{TINYFONT}CLI"

[STR_CID_COPPER]
base = "{TINYFONT}CR"

[STR_CID_ENGINEERING_SUPPLIES]
base = "{TINYFONT}PEI"

[STR_CID_FARM_SUPPLIES]
base = "{TINYFONT}FRM"

[STR_CID_FISH]
base = "{TINYFONT}PSG"

[STR_CID_TIMBER]
base = "{TINYFONT}PRN"

[STR_CID_MILK]
base = "{TINYFONT}LLF"

[STR_CID_PETROL]
base = "{TINYFONT}PTL"

[STR_CID_SAND]
base = "{TINYFONT}TYW"

[STR_CID_SCRAP_METAL]
base = "{TINYFONT}SGP"

[STR_CID_AGGREGATES]
base = "{TINYFONT}CRG"

[STR_CID_WOOL]
base = "{TINYFONT}GWL"

[STR_ERR_CLIMATE_TOYLAND]
base = "{ORANGE}Ni ddyluniwyd FIRS i weithio gyda'r hinsawdd Toyland"

[STR_ERR_LOCATION_NOT_ABOVE_SNOWLINE]
base = "rhaid fod islaw'r llinell eira."

[STR_ERR_LOCATION_NOT_ON_WATER]
base = "rhaid for ar dir sych."

[STR_ERR_LOCATION_NOT_IN_DESERT]
base = "ni gaiff fod mewn anialwch."

[STR_ERR_LOCATION_NOT_ON_STEEP_SLOPE]
base = "ni gaiff fod ar lethrau serth."

[STR_IND_ALUMINIUM_PLANT]
base = "Gwaith Alwminiwm"

[STR_IND_ARABLE_FARM]
base = "Fferm Âr"

[STR_IND_BIOREFINERY]
base = "Purfa Fiolegol"

[STR_IND_BREWERY]
base = "Bragdy"

[STR_IND_BRICK_WORKS]
base = "Gwaith Brics"

[STR_IND_BUILDERS_YARD]
base = "Iard Adeiladu"

[STR_IND_BULK_TERMINAL]
base = "Terfynfa Swmpiau"

[STR_IND_CEMENT_PLANT]
base = "Gwaith Sment"

[STR_IND_CLAY_PIT]
base = "Pwll Clai"

[STR_IND_DAIRY]
base = "Hufenfa"

[STR_IND_DREDGING_SITE]
base = "Safle Carthu"

[STR_IND_FISHING_GROUND]
base = "Maes Pysgota"

[STR_IND_FISHING_HARBOUR]
base = "Porthladd Pysgota"

[STR_IND_FOOD_MARKET]
base = "Marchnad Fwyd"

[STR_IND_FURNITURE_FACTORY]
base = "Ffatri Dodrefn"

[STR_IND_GLASS_WORKS]
base = "Gwaith Gwydr"

[STR_IND_HARDWARE_STORE]
base = "Siop Nwyddau Haearn"

[STR_IND_HOTEL]
base = "Hotel"

[STR_IND_SCRAP_YARD]
base = "Iard Sgrap"

[STR_IND_LIME_KILN]
base = "Cylyn Calch"

[STR_IND_LIQUIDS_TERMINAL]
base = "Terfynfa Hylifau"

[STR_IND_TIMBER_YARD]
base = "Iard Goed"

[STR_IND_TRACKED_MACHINE_FACTORY]
base = "Siop Beirianwaith"

[STR_IND_MIXEDFARM]
base = "Fferm Cymysg"

[STR_IND_NITRATE_MINE]
base = "Mwynglawdd Nitradau"

[STR_IND_PETROLPUMP]
base = "Pwmp Petrol"

[STR_IND_PLASTICS_PLANT]
base = "Gwaith Plastigion"

[STR_IND_PORT]
base = "Porthladd"

[STR_IND_QUARRY]
base = "Chwarel"

[STR_IND_SHEEPFARM]
base = "Fferm Ddefaid"

[STR_IND_SMITHY_FORGE]
base = "Gefail"

[STR_IND_STOCKYARD]
base = "Iard Nwyddau"

[STR_IND_SUGAR_REFINERY]
base = "Purfa Siwgr"

[STR_IND_TEXTILE_MILL]
base = "Melin Wlân"

[STR_PORT_PRODUCTION_4X]
base = "{BLACK}Cynnyrch presennol: {YELLOW}Gung-ho{}{}{BLACK}I gadw'r lefel yma, rhaid anfon {SKIP}{SIGNED_WORD} uned o gargo o fewn tair mis"

[STR_GENERIC_NEWLINE]
base = "{}"

[STR_FUND_ARABLE_FARM]
base = "{}{BLACK}Location: {YELLOW}Ni ellir ei ariannu ar eira, mewn anialwch nac ar lethrau."

[STR_FUND_FOREST]
base = "{}{BLACK}Location: {YELLOW}Ni ellir ei ariannu mewn anialwch."

[STR_FUND_FRUIT_PLANTATION]
base = "{}{BLACK}Location: {YELLOW}Ni ellir ei ariannu ar eira."

[STR_FUND_VINEYARD]
base = "{}{BLACK}Lleoliad: {YELLOW}Ni ellir ei ariannu ar eira neu anialwch."

[STR_FUND_AVAILABLE_FROM]
base = "{}{BLACK}Ar gael o: {YELLOW}{COMMA}"

[STR_STATION_POWERHUNGRY]
base = "Gorsaf Bŵer"
